vgstation-coders/vgstation13

code/game/machinery/doors/airlock.dm, code/game/machinery/doors/door.dm, code/game/machinery/doors/mineral.dm, code/game/machinery/doors/windowdoor.dm
Fixes #2263 and helps dylan not have an aneurysm
=> Small Airlock Sound Refactor

code/modules/reagents/Chemistry-Reagents.dm, html/changelogs/Duny-syringes.yml
Blood is also slightly darker. I wanted to make it even more dark but it ended up brown so fuck that.
Here's plasma, blood, and chloral:
Fixes https://github.com/d3athrow/vgstation13/issues/2395
=> Makes liquid plasma purple

code/game/machinery/kitchen/gibber.dm, code/game/mecha/mecha.dm, html/changelogs/Duny-mech.yml
Fixes https://github.com/d3athrow/vgstation13/issues/2361
Did the gibber at the same time because why not, Aurx might delete a gibber while someone is entering it some day.
=> Prevents climbing into deleted mechs and gibbers

code/game/atoms.dm, code/game/machinery/cryo.dm, code/game/objects/items.dm, code/game/objects/items/robot/robot_parts.dm, code/game/turfs/turf.dm, code/modules/mob/dead/observer/observer.dm, code/modules/mob/living/carbon/brain/MMI.dm
-Return of AI eye follow. Almost certainly works this time!
-Drops mommi parts when adding mmi to a robot
-Item size description added to name line
-Changeturf no longer resets the gases on the tile to the standard
-MMI examine text shows locked/unlocked status
=> Small Changes

code/game/dna/genes/monkey.dm, code/game/machinery/doors/multi_tile.dm, code/game/objects/items/stacks/sheets/glass.dm
-Giant spiders stop killing universe FOR REAL this time
-Windows set to the proper start state again, whoops.
-Monkey-ify debug message commented out
=> Window Bugfix

code/datums/uplink_item.dm, code/game/atoms_movable.dm, code/game/objects/items/weapons/dice.dm
Adds the E20, a librarian traitor item
Stats
Cost: 3 TC (lowered from 5)
Looks: Like a standard D20 dice
Effect: Creates an explosion of range X, where X/4 is the explosion devastation, X/2 is the heavy radius, and X is the light radius. X is the number you roll on the dice.
5% chance to roll a 1 which gibs the player
5% chance to roll a 20 which upgrades the explosion somewhat and ignores the bombcap
=> Librarian Traitor Item: E20

baystation12.dme, code/_onclick/ventcrawl.dm, code/modules/mob/living/carbon/alien/humanoid/queen.dm, code/modules/mob/living/carbon/alien/powers.dm, html/changelogs/Clusterfack_3080.yml
Here's a little thing I did that adds alt click ventcrawling to the mobs that can ventrcrawl. Let me know if I did it in a shit way, this way seemed quick and to the point.
=> Alt Click Ventcrawling

code/game/objects/items/weapons/RPD.dm, code/modules/mob/living/carbon/brain/MMI.dm, code/modules/mob/living/carbon/brain/posibrain.dm, code/modules/power/apc.dm
Fixes up examine text a little bit, again
Makes narsie not do some stupid thing where he destroys an apc and the power comes back on in the area
Fixes #3379, you can use rpds on catwalks
=> Some fixes

code/__HELPERS/experimental.dm, code/game/machinery/bees_apiary.dm, code/modules/mob/living/simple_animal/bees.dm
This pull makes bees immortal in a sense, instead of experiencing the sweet release of death, they will now be dragged to the depths of hell where they will lie until they day they are called to unleash terror upon the world once again.
If this works well we can think about implementing something similar for manifested ghosts and broodlings from hivelords which also tend to undergo a lot of creations and deletions.
=> Pooling for Bees

code/game/gamemodes/endgame/supermatter_cascade/portal.dm, code/game/objects/structures/windoor_assembly.dm
...So this was a thing, supermatter portal was always trying to set universal state but never did until a runtime fix.
=> Little thing

code/modules/admin/admin_verbs.dm
What it says on the tin, cant test shit to fix this on my local server because I dont have a mysql database set up. Only visible to the usr of the proc so I can pinpoint where this drops out (I'm suspecting the while loop fails or the new datum/admins fails).
=> Debug messages added to readmin self

code/game/objects/items/weapons/clown_items.dm
Should help with lag in the very specific case where a badmin spawns a shitload of gore and someone goes at it all with a bar of soap.
=> Pooling for cleanables added to soap

code/game/say.dm
Fixes improper href with ghost follow, obviously src has no meaning in this context.
=> Other say hotfix

code/controllers/Processes/power_machinery.dm, code/game/machinery/machinery.dm, code/modules/power/power.dm, code/modules/power/powernet.dm
Fix two issues that came as a result of powernet changes
1. Makepowernet not working as intended
2. Singularity being the only obj/machinery type in the power_machines list
=> Powernet Hotfix

code/modules/research/xenoarchaeology/artifact/artifact_communication.dm
Fix new artifact issue with mobs without hands taking stones, fixes it not being wrenchable either.
=> Fix for artifact

code/modules/clothing/spacesuits/ert.dm, html/changelogs/Boxed_ERTsuitheatfix.yml
makes the ERT suit actually resistant to heat
also makes ERT suits bulky items because they weren't before for some fucking reason
also removes a useless list that was overwritten by another one(i think)
fixes  #3185
=> ERT suit heat fix

code/game/machinery/machinery.dm
Machines cannot be wrenched down over other anchored and dense machines in the same turf.
=> Fixes #3979

code/game/machinery/machinery.dm
Fixes #4024
Fixes #4023
Machine unwrenching should work fine again
=> Wrenching fix fix

code/modules/mob/living/carbon/carbon.dm
Removes the cyborg hand consistency check from mommis when preparing to ventcrawl at least.
=> Address #3943

code/game/machinery/atmoalter/portable_atmospherics.dm, code/game/machinery/cryo.dm, code/modules/paperwork/photography.dm
Fixes #4015 - Cryotubes dont interact with wrenches
Fixes #4013 - Hydro trays will attempt to interact with connector ports first, and if not then wrench down normally
Fixes #4019 - Cameras now hold their information outside of their description, it will display during show() instead
Attack_self now calls show instead of examine
Examine calls show if adjacent and otherwise examines it
=> Simple Bugfixes

code/game/objects/items/weapons/storage/lockbox.dm
tracked_access should have been [tracked_access], simple as that
=> Fixes #3963

code/ATMOSPHERICS/components/trinary_devices/filter.dm, code/ATMOSPHERICS/components/trinary_devices/mixer.dm
=> Makes filter/mixer density 0.

code/_onclick/observer.dm, code/game/atoms_movable.dm, code/modules/mob/mob_movement.dm
Made force enter which does what forcemove does except doesn't actually call crossed or invoke event because sometimes you just dont want those.
=> Fix ghost movement

code/game/objects/items/weapons/tanks/tank_types.dm
=> Fine I fixed nitrogen tanks

code/controllers/master_controller.dm, code/game/gamemodes/events.dm, code/modules/atmos_automation/implementation/digital_valves.dm, code/modules/atmos_automation/implementation/injectors.dm, code/modules/atmos_automation/implementation/scrubbers.dm, code/modules/atmos_automation/implementation/vent_pump.dm, code/modules/events/alien_infestation.dm
I already made these explicit changes what the fuck happened to them.
Fixes #4370 clearly but what the fuck mang.
=> REDOING SHIT

code/ZAS/Fire.dm
=> Uncomment fire_act

code/game/dna/dna_modifier.dm, code/game/machinery/Sleeper.dm, code/game/machinery/adv_med.dm, code/game/machinery/cryo.dm, code/game/machinery/iv_drip.dm, code/game/mecha/mecha.dm, html/changelogs/Clusterfack_4442.yml
Fixes #4424
Fixes #4413
What this does:
-You drag from the machine you are inside to a nearby turf to leave the machine and go to that turf
-This also works when other people are inside these machines, as long as the turf you choose is adjacent to you and the machine
-Also makes it so you can click on iv drips when one is attached to you, to detach it from you
=> Mousedropping Out of Things

code/WorkInProgress/buildmode.dm
BUILDMODE CLICK USED TO CALL IN WORLD EVERY CLICK.
Fun fact: just because you dont use the words "in world" doesn't mean you aren't LOOPING THROUGH THE WORLD EVERY TIME YOU CLICK ON ANYTHING IN BUILD MODE JESUS CHRIST.
=> Buildmode Click Optimization

code/game/gamemodes/blob/blob.dm, code/game/gamemodes/blob/theblob.dm
=> Im nuclear

code/game/gamemodes/gameticker.dm
Honestly why this was never logged in the first place, that's pretty funny.
=> Logs which secret gamemode fails the pre-setup

code/modules/awaymissions/corpse.dm
Fixes #4939
They didn't have if(ticker) -> initialize() with their initialize()
=> Fix Corpse not Spawning

code/modules/mob/living/simple_animal/friendly/spiderbot.dm
Spiderbots wont be prevented from entering vents thanks to their brain
Fixes #4104
Fixes #3578
=> Spiderbot Fix

code/game/gamemodes/vampire/vampire_powers.dm, html/changelogs/Clusterfack_5091.yml
=> Fucking Fix Vampire

code/global.dm, code/modules/mob/living/simple_animal/friendly/mouse.dm, code/modules/supermatter/supermatter.dm, code/setup.dm, html/changelogs/Clusterfack_5084.yml
Mice triggering station destroying endgames by respawning every minute.
Thanks mice.
=> Why Mice Why

code/controllers/configuration.dm, code/modules/admin/verbs/ticklag.dm, code/modules/mob/mob_movement.dm
Burn in hell tick compensation. You did nothing but you broke everything, including my heart.
=> Rest in Peace

code/modules/mob/mob_movement.dm
Yeah this one is on me, mixed up min/max that's a first for me but I knew it'd happen someday.
=> Mob movement

code/game/machinery/machinery.dm, code/modules/html_interface/crew/crew.dm, code/modules/mob/dead/observer/observer.dm, code/modules/power/monitor.dm
Fixes #5303. I established a list to create easy mob checks for ability to update but neglected to add this older html device to it.
=> Fix power monitor

code/modules/html_interface/crew/crew.dm
Readds our local zlevel drift system to the CMC so it gives accurate coordinates. That is to say, not accurate but consistent with everything else.
=> Fixes CMC coord drift

code/__HELPERS/time.dm
Fixes #5329
This will never even occur
=> Add midnight rollover to station time

code/modules/mob/living/carbon/alien/humanoid/update_icons.dm, code/modules/mob/living/carbon/human/examine.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/update_icons.dm, code/modules/mob/living/silicon/mommi/update_icons.dm, html/changelogs/clusterfack_5364.yml
Fixes #5354
Yeah lots of things depend on the assumption that blood_dna is null or a list. I've fixed up several more, this should fix human icons.
=> Fix blood issues further

code/modules/html_interface/crew/crew.dm, code/modules/html_interface/crew/crew.js
CMC offset applies to GPS coords, but NOT minimap coordinates
=> Correction

.gitignore
Reverts d3athrow/vgstation13#5382
=> Revert "Adds the CMC minimap files to the .gitignore"

code/game/machinery/kitchen/monkeyrecycler.dm, code/game/objects/effects/effect_system.dm, code/game/objects/items/weapons/table_rack_parts.dm, code/game/objects/structures.dm, code/game/objects/structures/watercloset.dm, code/modules/flufftext/Hallucination.dm, code/modules/mining/mine_turfs.dm, code/modules/mob/dead/observer/logout.dm, code/modules/mob/dead/observer/observer.dm, code/modules/mob/living/carbon/monkey/monkey.dm, code/modules/mob/living/simple_animal/friendly/slime.dm, code/modules/mob/living/simple_animal/hostile/hostile.dm, code/modules/mob/living/simple_animal/hostile/mining_mobs.dm, code/modules/mob/new_player/logout.dm, code/modules/power/antimatter/control.dm, code/modules/power/antimatter/shielding.dm, code/modules/projectiles/projectile/special.dm, code/modules/reagents/reagent_containers/food/snacks.dm, code/modules/research/xenoarchaeology/artifact/artifact.dm, code/modules/research/xenoarchaeology/finds/finds.dm
-Lots of things that call del() are now fixed
-Removed many places that call spawn() unnecessarily
-They should garbage collect or be pooled now
Things like:
monkeycubes
hivelord broodlings
boulders
slimes
monkeys
metalfoam
shower mist
hallucinations
observers
new players
strangerocks
artifactholders
kinetic blasts
every single object/structure that had to do with the AME
=> Removes more manual del() calls

code/modules/mob/living/simple_animal/hostile/hostile.dm, code/modules/mob/mob_defines.dm
Fixes up a few list() resetVariables for various mobs
=> Resetvariables

code/_onclick/ventcrawl.dm
Nobody thought this was worth reporting as a bug though it totally was.
=> Fix queens ventcrawling

code/modules/mob/dead/observer/observer.dm, code/modules/mob/mob.dm
Let's get going on that mob qdeletion
=> Remove mob references in destroy()

code/game/gamemodes/cult/cult.dm, code/game/jobs/job/captain.dm, html/changelogs/Clusterfack_3710.yml
Loyalty implant added to the HoP
=> HoP Loyalty Implant

code/game/machinery/teleporter.dm, code/game/objects/items/weapons/implants/implant.dm
Gee badcode, what do you want to do tonight?
Same thing we do every night badcoder, try to loop through the world.
=> Teleporter getavaildest in world

code/game/objects/items/weapons/swords_axes_etc.dm
Fix runtime from type/string mismatch
=> Runtime fix

code/modules/mob/living/silicon/ai/life.dm
*Not checking client before checking eye* 
/s
=> Fix null.eye runtime

code/_onclick/hud/_defines.dm, code/_onclick/hud/ai.dm, code/_onclick/hud/alien.dm, code/_onclick/hud/alien_larva.dm, code/_onclick/hud/hud.dm, code/_onclick/hud/human.dm, code/_onclick/hud/mommi.dm, code/_onclick/hud/monkey.dm, code/_onclick/hud/other_mobs.dm, code/_onclick/hud/robot.dm
I hate busywork
Huds now scale positioning with client view.
Exceptions : pretty sure damageoverlay, darkmask, blurry vision which all have unique sprites and dont use screen locs. To fix those we need to use scale() along with a standardized proc for changing view size.
=> Hud Scaling

code/__HELPERS/datumpool.dm, code/_onclick/hud/human.dm, code/_onclick/hud/screen_objects.dm, code/modules/mob/mob.dm
Shaves off another ~10% of human life() I'd say.
How it works right now:
Makes a new image of the action object from its icon state and icon.
Blends it with the obj/screen button.
For up to 5 objects, every tick.
How it works after I optimized it:
Makes a new image once, sets its appearance to that of the action object (costless)
Since the image's loc is the obj/screen button it requires no blending
Does nothing else because my system isn't shit
=> Optimizes update_action_buttons

code/modules/mob/mob.dm
I need better profiling of this damn function to improve it, it is a thorn in our side at both high populations and high framerates.
I just divided into three chunks to see what portion of it uses up the most cpu time so I can devise a way to optimize it.
=> Better mob/stat() profiling

code/game/objects/items/weapons/storage/storage.dm
Lets you mosuedrop storage containers onto tables
=> Storage Dumping

code/game/objects/items/devices/scanners.dm
The internal bleeding is now a DANGER notice isntead of warning.
Also the health analysis message is recorded in the health analyzer and can be read using attack self
=> Health Analyzer Tweak

code/modules/mob/mob_grab.dm
It didn't have an attackself when in your hand, how stupid is that.
=> Fix grabs attackself

code/modules/mob/living/silicon/robot/robot.dm, code/modules/power/apc.dm
Throwaway code to make it so when you use a cell on a thing that has cell and it would be normally taken out you swap the one with the one in your hand instead.
=> Cell swapping

code/_onclick/ventcrawl.dm, code/modules/mob/living/carbon/alien/powers.dm, code/modules/mob/living/carbon/metroid/powers.dm, code/modules/mob/living/carbon/monkey/powers.dm, code/modules/mob/living/silicon/mommi/powers.dm, code/modules/mob/living/simple_animal/borer.dm, code/modules/mob/living/simple_animal/friendly/mouse.dm, code/modules/mob/living/simple_animal/friendly/spiderbot.dm
Fixes #5573
Fixes #5891
Fixes #6191
Centralized some code for ventcrawling in ventcrawl.dm
Made passive vents a type to be checked for ventcrawling into
Made hunters able to carry things into vents apparently
Gave contortionist jumpsuit a verb to ventcrawl with for the scrubs who dont know hotkeys
=> Ventcrawling changes

code/_onclick/hud/human.dm
If an action item was destroyed fully this could and would runtime
=> Fixes runtime

code/modules/mob/living/silicon/ai/say.dm, code/modules/power/monitor.dm, code/modules/research/fabricators.dm, code/modules/research/rdconsole.dm, html/changelogs/Clusterfack_8263.yml
1. The research console now displays the true values of the costs used in creating objects (dependent upon resource coefficient)
2. The circuit imprinter now correctly varies chemical cost with resource coefficient
3. The general output material proc now was improved to display reagents as well and is now actually used
4. The following things now all use list2text for much greater string concatenation performance at runtime
- R&D Console (s h i t t y)
- AI announcement verb help (previously took .2 server seconds every time it was called)
- Power Monitor
=> Improves R&D

code/game/objects/items/devices/scanners.dm
Not only was it a needless change dylan, it caused runtimes for literally no net gain.
Fixes #dylanbeingdumb
12:20:02 Runtime detected
bad arg name 'mode' at :
proc name: healthanalyze (/proc/healthanalyze)
usr: the cortical borer (123) (/mob/living/simple_animal/borer)
src: null
call stack:
healthanalyze(Anne Tagg (/mob/living/carbon/human), the cortical borer (123) (/mob/living/simple_animal/borer), null, null, null)
the cortical borer (123) (/mob/living/simple_animal/borer): Analyze Health()
=> Fix Runtime

code/__HELPERS/unsorted.dm, code/game/machinery/computer/HolodeckControl.dm
GOD FUCKING DAMNIT THIS WAS CHANGETURF.
WHO THE FUCK WOULD REPLACE CHANGETURF WITH TURF/NEW?
=> Fixes #6371

code/game/machinery/computer/store.dm
Merch computer has a corrected update icon
=> Fixes #5305

code/game/objects/effects/decals/Cleanable/humans.dm, html/changelogs/ShiggyPiggy_bugfix.yml
Yup, go away https://github.com/d3athrow/vgstation13/issues/3197 and the crazy commit rate!
=> Fixes issue #3197

code/game/gamemodes/changeling/changeling_powers.dm, code/game/machinery/adv_med.dm, code/modules/mob/living/carbon/human/death.dm, code/modules/organs/blood.dm
Changelings drain all blood from their victim
Changeilngs replenish any blood they have lost from the draining of their victim
=> Fixes #4325

code/modules/reagents/Chemistry-Reagents.dm
Fixes https://github.com/d3athrow/vgstation13/issues/6376
=> Added overdose to silicate

code/modules/paperwork/paper.dm
=> Fixes #5663

code/datums/mind.dm, code/game/dna/dna2_domutcheck.dm, code/game/objects/items/weapons/dna_injector.dm, code/game/objects/items/weapons/storage/boxes.dm, code/modules/mob/living/simple_animal/hostile/mimic.dm
Specialized injectors no longer fail to give you the power you want, works like a charm
=> Fixes #5489

code/game/objects/items/stacks/sheets/mineral.dm
Comments out plastic's sheettype which is the value that makes doors/girders think you can build something from this material type. At least until someone adds plastic variants.
=> Fixes #4810

code/modules/bomberman/bomberman.dm
Removes some dels and should make GC occur properly
=> Fix some bomberman deletion

code/game/machinery/shieldgen.dm
Proper destroy procs that will allow garbage collection contained within
=> Fix shieldgen.dm's qdel

code/datums/datumvars.dm, code/modules/RCD/schematics/tile.dm, code/modules/media/jukebox.dm
If its using more than .05 server seconds it's time to fix that shit. These are some of the current highest average costing procs (from string concatenation which we only recently fully realized how to eliminate)
=> Fix three more concatenations

code/modules/admin/verbs/modifyvariables.dm
My issues are fly, my commits are sick. Seriously though, THIS IS IMPORTANT!
Fixing people, and shit.
=> Fixes #6754

code/datums/supplypacks.dm, html/changelogs/ShiggyPiggy_5.yml
Adds a new crate to the hospitality section for the special and unique
snowflake in you, as well as two random lipsticks.
=> A crateful of dresses

code/game/gamemodes/autotraitor/autotraitor.dm
=> Fixes the autotator

code/modules/nano/JSON Writer.dm
=> String Concatenation

code/setup.dm
=> Halves soft lighting illumination

code/_onclick/hud/spell_screen_objects.dm
=> Fix runtimes

code/datums/supplypacks.dm
Thanks to Kurfursten for fixing the thing anyhow
=> Typos are rude

code/modules/clothing/under/miscellaneous.dm
This crate's more trouble than it's worth.
Thanks @Exxion, though! I never actually made the dresses, they all were in the code.
=> Fixes #6912

code/game/turfs/simulated/floor_types.dm
I did everything just like @PJB3005 said!
=> Fixes(?) #6884

code/game/machinery/computer/buildandrepair.dm, code/game/objects/items/robot/robot_parts.dm, code/game/objects/structures/displaycase.dm, code/modules/mob/living/carbon/brain/MMI.dm, code/modules/mob/living/carbon/slime/slime.dm
Makes Slimes soft delete
Makes radio enabled MMIs soft delete
Makes computer frames soft delete
Makes robot exoskeletons soft delete
Makes display cases soft delete
=> Soft Deletions

code/modules/reagents/Chemistry-Reagents.dm
..() - this does nothing if you just call it like this, what's the point
Use if(..()) return 1 along with return 1s where the proc is supposed to fail in the parent to actually have sanity
=> Chemistry - Proper Sanity

code/game/objects/structures/girders.dm
To be honest I thought there was an issue for this made (there was one in the past but I fixed it in a different way), this prevent the issue from ever occurring entirely.
=> Fix walls that don't exist

code/controllers/master_controller.dm
We had this and it got reverted for no reason whatsoever, and the minimaps trigger a lot of people.
=> Spawn()s minimaps again

code/game/machinery/hologram.dm, code/modules/mob/hearing/virtualhearer.dm, code/modules/mob/mob.dm, html/changelogs/Clusterfack_7141.yml
TECHNOLOGY
Fixes #6205, and maybe a few other issues about this that I cannot find
=> Emotes are now recursive

code/datums/shuttle.dm, code/game/gamemodes/heist/objectives.dm, code/game/machinery/computer/shuttle_computers.dm, html/changelogs/Clusterfack_7185.yml
Objectives - fixed
Shuttle being moved ending the round instantly - fixed
Player sending the shtutle to deep space not being logged properly - fixed
=> Fixes Heist - all of it

code/game/objects/items/devices/paicard.dm
pAIs don't just up and fucking break upon face changing
=> Fixes #7235

code/modules/admin/admin_verbs.dm
=> Delay permissions change

code/datums/supplypacks.dm
=> Fix knight supply crate

code/game/objects/structures/girders.dm
=> Fix rwall construction

code/__HELPERS/game.dm, code/game/machinery/camera/motion.dm, code/game/machinery/cryo.dm, code/game/machinery/telecomms/machine_interactions.dm, code/game/machinery/telecomms/traffic_control.dm, code/game/objects/items/weapons/explosives.dm, code/game/objects/items/weapons/grenades/ghettobomb.dm, code/modules/projectiles/guns/projectile/revolver.dm, code/modules/virus2/helpers.dm
Fixes #7325
A number of instances swapped the target/user variable and a few others used it as adjacency
=> Fixes some improper uses of in_range

code/modules/reagents/reagent_containers/food/snacks.dm
=> Snacks need to mcfucking kill themselves

code/modules/mob/dead/observer/observer.dm
=> Fixes adminghosts making ghosts

code/modules/mob/living/living.dm
Fix #7522
Resting will now update your icon immediately
=> Instant resting

code/modules/mob/living/carbon/human/human_movement.dm, code/modules/projectiles/guns/projectile/sniper.dm
Fixes #7524
You only gain the slowdown from an object in your hand if it is being wielded
=> Codervalids detected

code/modules/mob/living/silicon/mommi/mommi.dm
=> Mommis dont self fix at 0 brute damage

code/modules/html_interface/voting/voting.dm
Weighted vote -> Random Weighted vote
% chances added to the end of the options
fix #7582
fix #7634
=> Weighted Voting Clarification

code/controllers/Processes/lighting.dm, code/controllers/master_controller.dm, code/game/turfs/turf.dm, code/modules/awaymissions/zlevel.dm, code/modules/lighting/lighting_system.dm, code/modules/mining/mine_turfs.dm
Should remove 8/11ths of the startup time.
Needs testing.
Fixes #7389
=> Faster Startup

code/modules/mob/living/silicon/mommi/mommi.dm, code/modules/mob/living/silicon/robot/robot.dm
Fixes some weird scenarios where a mommi that was only getting his cover hacked could get keeper var removed, and could thus speak.
=> Fixes #7805

code/modules/client/client procs.dm
This will give better profiling information about each individual sql query
=> Subdivides log_client_to_db

code/game/machinery/doors/airlock.dm, code/game/machinery/doors/airlock_electronics.dm, code/game/machinery/doors/windowdoor.dm, code/game/objects/structures/displaycase.dm, code/game/objects/structures/door_assembly.dm, code/game/objects/structures/windoor_assembly.dm
Fixes #7658
Fixes #4768
Upgrades airlock electronics topic so it doesn't suck as much, also fixes the emagging a windoor bug
=> Fixes some airlock electronics bugs

code/_onclick/hud/ai.dm, code/_onclick/hud/alien.dm, code/_onclick/hud/alien_larva.dm, code/_onclick/hud/hud.dm, code/_onclick/hud/human.dm, code/_onclick/hud/mommi.dm, code/_onclick/hud/monkey.dm, code/_onclick/hud/other_mobs.dm, code/_onclick/hud/robot.dm, code/_onclick/hud/screen_objects.dm, code/_onclick/hud/spell_screen_objects.dm, code/modules/mob/login.dm, code/modules/mob/mob.dm
Fixes an already closed issue I think
Adapted from https://github.com/tgstation/-tg-station/commit/fea00718a0c889669e07d576cadcccd7fded90c2
=> Makes darkness clickable

code/game/turfs/space/space.dm
=> Simple thing

code/modules/mob/living/carbon/human/life.dm
Any species will now start with its inherent species powers again
=> Fixes #7719

code/modules/mob/mob_movement.dm
Isn't it weird nobody reported it? It lets you spam attack self instantly!
Fixes #7954
=> Fixes an obscure ancient bug

code/game/objects/structures/stool_bed_chair_nest/bed.dm, code/game/objects/structures/stool_bed_chair_nest/chairs.dm, code/modules/mob/dead/death.dm, code/modules/mob/mob.dm, code/setup.dm
Wow update_canmove can you just not fuck up there buddy?
Fix #8049
=> Fix locked ghosts becoming dense

code/game/objects/items/stacks/packagewrap.dm
You know I expected this to be a false report or something silly,
THEN FOUND OUT MECHA PARTS ARE SIZE 20
=> Fixes #6922

code/defines/obj.dm, code/modules/mob/mob_movement.dm
Removes a loop through a mob's loc's contents when a client tries to move.
=> An optimization for you

code/modules/research/mechanic/flatpack.dm
You can now mousedrop flatpacks off of flatpack stacks
Robots can do it too
=> Change the whack flatpack stacking

code/modules/html_interface/map/interactive_map.dm
Fixes some issue or another, I cant find it
=> Fix cached HTML maps sometimes overriding the current map

code/modules/mob/living/living.dm
=> Fix resisting out of package wrapped lockers

code/modules/mob/living/living.dm
You can resist out of package wrap and its syndicate variety (which takes a longer timer)
Fixes #6835
=> Packge wrapping resist

code/modules/spells/spell_projectile.dm, code/modules/spells/targeted/projectile/projectile.dm
Fixes #4360 I think. A magic missile show would do AOE damage in 1 tile around it, with a few mobs around it this stacks up very very quickly.
=> Makes Seeking Damage not AOE

code/modules/mob/living/carbon/human/death.dm, code/modules/mob/living/living.dm, code/modules/mob/mob.dm, code/modules/reagents/Chemistry-Reagents.dm
Looks like it would only be removed from you if the life() tick removed it from you
Fixes #8501
=> Fix jitteriness

html/changelogs/Duny.yml
- Re-added the security checkpoint in medbay. Closes https://github.com/d3athrow/vgstation13/issues/8639. 
- Added a few additional air alarms in hallways. Fixes https://github.com/d3athrow/vgstation13/issues/8757.
- Rotated the AME room's layout to allow people to build and expand the AME horizontally rather than vertically, as AME code is apparently shit and will fuck up if built vertically. Removes Deff tag on https://github.com/d3athrow/vgstation13/issues/8698.
- Added windoors behind plastic flaps in places where simply deconstructing plastic flaps would allow anyone to enter. Fixes https://github.com/d3athrow/vgstation13/issues/8611.
- Added a bar of soap in both custodial closets. Closes https://github.com/d3athrow/vgstation13/issues/8547.
=> Small Deff update

code/modules/supermatter/supermatter.dm
The super singularity originally created by /vg/ and adopted by everyone has gone commented out for too long, too long I say!
A stage 5 singularity will expand into a super singularity (without ending the universe) when it eats a supermatter crystal, but the full crystal creates the super singularity along with the usual supermatter cascade.
=> Returns our precious super singularity

code/game/atoms.dm, code/game/atoms_movable.dm, code/game/machinery/doors/airlock.dm, code/game/machinery/doors/door.dm, code/game/machinery/doors/firedoor.dm, code/game/machinery/doors/mineral.dm
So yeah this existed. The reasons for it existing were pretty meagre, and frankly don't really make all that much sense.
=> Removes airlock bump delay

code/modules/html_interface/map/adv_sec/advcamera.js, code/modules/html_interface/map/crew/crewmonitor.js
Applies to crew monitor and advanced security computer
Fixes #8905
Clear your cache before hastily reopening the issue
=> Relative Scaling for text-based mode

code/modules/mob/living/simple_animal/hostile/hostile.dm
=> Lag lag lag lag lag

code/modules/admin/topic.dm, code/modules/admin/verbs/pray.dm
Fixes some autismal shit with syndicate/centcomm private messages
Makes them use the same method as pray so the msay window works properly
Fixes that issue probe made about centcomm replying
fixes #8971
fixes #9095
=> Fix some shit

code/game/machinery/metaldetector.dm
Stupid whoever you were cloroxygen
Fixes whatever
=> Fix a metaldetector issue

code/modules/mob/mob_grab.dm
I can GUARANTEE YOU - that this probably works
Fixes a few relevant issues
closes #9097
=> Fix mob grab not being delayed

code/ATMOSPHERICS/atmospherics.dm
This should allow the socket wrench to not let an entire pipelines worth of air to escape
Fixes #9038
=> Fixes socket wrenches

code/game/gamemodes/cult/ritual.dm
Closes #8963 
I honestly don't know how you are using all the runes
=> Increases rune limit

code/modules/mob/dead/observer/observer.dm, code/modules/mob/mob_movement.dm
=> Increase ghost speed

code/modules/reagents/reagent_containers/food/snacks.dm
Probably fixes like 3-4 issues on this topic
Fixes #9224
Fixes #8187
Namely
1. A food object being qdeleted drops the contents of it on the ground
2. A food object cannot hold another of the same size as it (must be of lower size)
3. A food object can only hold 1/2 of its slices_num (number of slices when sliced)
=> Changes snack food insertion

code/game/objects/items/stacks/rods.dm, code/game/objects/structures/grille.dm
Probably should do it. Intigracy's earlier fix to grille's most likely fixed true 'invisible grilles', this fixes grille's icon states not updating upon being fixed.
Fixes #8976
=> Fix grilles

code/controllers/master_controller.dm, code/game/objects/items/weapons/dna_injector.dm
Moved genetics earlier in startup due to it not having dependencies
Fixes #9542
=> Fix mapped injectors

code/modules/mob/living/carbon/human/life/handle_disabilities.dm
Since removing memes is the word of the day obviously this should be removed
=> Revert "Speak finnish randomly when brain damaged"

code/game/machinery/bots/buttbot.dm
=> Buttbots don't speak first

code/game/machinery/vending.dm, code/game/objects/items/devices/PDA/apps.dm
Deity and oldcode teamed up to fuck up
=> Fix a runtime

code/modules/power/battery.dm
=> Fix another possible runtime

code/global.dm, code/modules/client/client defines.dm, code/modules/client/preferences.dm, code/modules/mob/new_player/new_player.dm
Intigracy fucked up
I believe this definitively fixes #9597
=> Fix another runtime

code/modules/hydroponics/seeds.dm
To help with vending machine code
=> Seeds have initial names

code/modules/research/designs/engineering.dm, code/modules/research/designs/stock_parts.dm, html/changelogs/Clusterfack.yml
Makes it impossible for me to autism as a derelict mommi, bad change bundled with good changes 0/10.
Closes #9220
=> Revert stock parts using plastic

code/game/objects/items/weapons/storage/storage.dm, code/game/objects/structures/electricchair.dm, code/modules/mob/death.dm, code/modules/mob/living/carbon/alien/larva/larva.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/monkey/monkey.dm, code/modules/mob/living/simple_animal/hostile/alien.dm, code/modules/mob/mob.dm
Fixes #9851
Fixes #9860
Fixes #9757
Fixes #9751
=> Bugfixes Again

code/game/gamemodes/objective.dm, html/changelogs/cumoverme.yml, maps/_map.dm, maps/ministation.dm
=> allows to remove stealing objectives per map

CONTRIBUTING.md, code/__HELPERS/lists.dm
It's faster because it doesn't use istype and uses a dict for constant var access speed
=> Ports TG optimized istype in list

code/game/machinery/bots/bots.dm
Not really, you could always emag them it just wasn't clear how.
Makes it a little bit easier and makes it a little bit more clear.
Fixes #9543
=> Fix unemaggable secbot

code/modules/mob/dead/observer/say.dm, code/modules/mob/say.dm
Wow this went unfixed for a long time what the hell
Fixes #9658
=> Log dead say

code/modules/telesci/telesci_computer.dm
=> It seems like someone should have fixed this

code/modules/client/client procs.dm, code/modules/html_interface/map/adv_sec/adv_camera.dm, code/modules/html_interface/map/adv_sec/advcamera.js, code/modules/html_interface/map/crew/crew.dm, code/modules/html_interface/map/crew/crewmonitor.js, code/modules/html_interface/map/interactive_map.dm
Fixes the bug where the map isn't replaced properly so you never see the UI because the .js isn't sent to you, I should hope, considering I'm telling it to try resending resources each time you open the thing again.
Fixes the bug where the map is the same between rounds when it shouldn't be, by removing the chance of collision between maps. I know I said that before but I did it wrong that time and the js was never modified so it never could have worked.
Also added some whitespace to give readability to some of the headers.
=> Probably fixes the two html UI bugs

code/modules/mob/living/simple_animal/friendly/spiderbot.dm
=> Change spiderbot checkslip

code/game/dna/genes/speech.dm, code/modules/mob/living/carbon/species.dm, code/modules/mob/living/simple_animal/hostile/retaliate/cluwne.dm, code/modules/paperwork/pen.dm
Fixes papercode, fixes the catbeast/cluwne wordfilter, fixes our regex expressions system
Fixes #9752
Fixes #10014
NOW STOP BREAKING SHIT
=> I hate you people

code/game/objects/items/stacks/packagewrap.dm
Whoever the fuck put trying to wrap humans before all the sanity was a fucking dunce
Fixes #10784
=> Fix long range package wrapping

code/modules/paperwork/pen.dm
Needs a bit more testing by our goonchatters so we can be sure that goonchat isn't killing people who gets link sent to them
=> Adds [youtube] option for bbcode

code/modules/mob/mob.dm
=> Change visible message

code/_onclick/hud/hud.dm, code/_onclick/hud/parallax.dm, code/controllers/master_controller.dm, code/game/atoms_movable.dm, code/game/machinery/camera/camera.dm, code/game/turfs/space/transit.dm, code/modules/client/client defines.dm, code/modules/client/preferences_toggles.dm, code/modules/mob/login.dm
Fixes parallax not letting your view reduce below size 7
Removes parallax forcing you to see things over walls
Fixes whatever other seeing space bugs there are
=> Some different parallax shit

code/modules/mob/mob_movement.dm
Waow what a great pr, makes it really easy to handle your car keys
=> Makes hotkeys client dir independent

code/_onclick/hud/parallax.dm
I made some changes earlier to make it so parallax icons have screen loc of center,center and pixelshifted from there so that the client view size could decrease to 1,1 when you mousewheel down. 
However I did not center them properly, this centers them properly and improves the update loop slightly.
=> Centers Parallax

code/modules/client/client procs.dm
Fixes #11142
If you log in the for the first time your player age will be "requires database". 
This causes problems because when you log in for the first time you can set job preferences to other values because your player age is "requires database" which means the game assumes you didn't set up a database and thus removes all job setting restrictions.
=> Fixes player age

code/modules/mob/spells.dm, code/modules/spells/targeted/mind_transfer.dm
Come on guys you could have fucking fixed this really quickly
Close #10933
Fix #10929 
Fix #9307
Fix #6804 
Fix #6573
=> Mindswap fix

code/_secrets.dm, vgstation13.dme
Allows coders to #include files within the secret repository by allowing the override of this file.
=> Adds a secrets file

code/ZAS/ConnectionGroup.dm
=> REPAIRS THE GOLDEN THRONE

code/game/objects/items/stacks/rods.dm, code/game/objects/items/stacks/tiles/plasteel.dm, code/game/objects/items/weapons/storage/toolbox.dm, html/changelogs/clusterfack.yml
This is the way spess should be comrades
=> Nerfs floor tiles buffs toolboxes

code/modules/mob/mob.dm
=> Fixes give spell forever

code/modules/spells/aoe_turf/fall.dm, code/modules/spells/general/area_teleport.dm, code/modules/spells/spell_code.dm
Before_cast wasn't finding the user for some reason and returning it as a valid target.
=> Fix INCLUDEUSER flag

code/modules/mob/mob.dm
Using multiple bitflags doesn't work with a switch, thus an if else-if change is necessary here.
=> Fix not all alien spells showing up in the tab

code/modules/spells/spell_code.dm, code/modules/spells/targeted/targeted.dm
Closes #11605
Fixes #11658 
Fixes #11696
=> Spell targets 2

code/modules/paperwork/nano_paper.dm
Self explanatory, I added this functionality but couldn't find this help section but now the information should be clear to everyone!
=> Adds youtube instruction to nanopaper help

code/_onclick/hud/parallax.dm, code/game/gamemodes/setupgame.dm, code/global.dm
We really need to organize all this code better. Primarily moving _DEFINES to actually be before everything else.
=> Localizing some code

code/modules/mob/living/carbon/human/life/handle_disabilities.dm
latest meme
after an AI plasmaflooded and killed EVERYONE but two people an engineer and one CE, central command asked them how everything he was doing
The CE responded: "How do we engiener="
he never responded after that
=> How do we engiener=

code/modules/client/preferences.dm, code/modules/client/preferences_savefile.dm, code/modules/mob/new_player/new_player.dm, code/modules/mob/transform_procs.dm
So it turns out SOME morons who've added prefs to the menu in the past never bothered in putting the actual behavior to make the toggles affect the current game before relogging. So I've manually gone through all the prefs to make sure they have the full behavior the verbs did.
I also fixed a bug where when you saved your special roles prefs it would always tell you which roles were 'set to no', even when you hadn't modified them. And also I gave a message for when no roles are changed at all.
Fixes #11983
Fixes #11981
=> Fixes some prefs issues

code/controllers/garbage.dm, code/game/atoms_movable.dm, code/game/objects/items/devices/PDA/PDA.dm, code/game/objects/items/devices/PDA/apps.dm, code/game/objects/items/devices/PDA/cart.dm, code/modules/mob/living/carbon/human/death.dm, code/modules/mob/living/carbon/species.dm, code/modules/mob/mob.dm
Did a bit of improvements to help with garbage collecting of pdas, headsets, and humans, in theory humans could garbage collect now.
Adds a new (ported) tool to find references when testing garbage collecting, it works pretty well and in theory should find every possible reference (but it doesn't and its infuriating)
=> Garbage collecting

code/modules/awaymissions/corpse.dm, html/changelogs/cptwad.yml
This time its better I promise
All special characters are corpses to be revived and taken over. I am told this is how you add mobs without breaking things.
other things
new layout of most of the shit
Wizard  stations now surrounded by void. Immershuns
Same somewhat goes for syndie bases which now feature fuller snow and bases. Nothing inside said bases but when you have mensons or thermals on your immershuns wont break. 
updated ERT photo
fixes #11884
fixes #11746
fixes #10910
fixes #10517 
fixes #10454 
fixes #7163 
fixes #7243 
fixes #11103 
fixes #10985
fixes #11814
fixes #11813
fixes #11101
fixes #10623
fixes #10222
fixes #11884
=> Centcom Updates 3 Return of the maps 

code/modules/mob/living/silicon/ai/ai.dm
=> Stop resetting AI channels during radio config.

code/game/gamemodes/scoreboard.dm
1E17% tested.
Seriously though I only checked blob and cult and it seemed alright for both of those.
=> Re-enable round end report for team antags.

code/game/gamemodes/cult/runes.dm
Imbue Talisman no longer chooses to imbue runes onto talismans.
Fixes #10708
=> Make talisman imbuing a bit more convenient.

code/modules/mining/mine_turfs.dm, html/changelogs/Kavlax.yml
I remember hearing about all those messages lagging someone out (especially after Goonchat) so here you go. Other benefits: Gibtonite is a bit easier to notice, radio is no longer drowned out for miners.
=> Reduce mining message spam.

code/game/objects/items/robot/robot_upgrades.dm, html/changelogs/Kavlax.yml
=> Make VTEC upgrade speed up borgs again.

code/modules/admin/admin.dm, code/modules/admin/topic.dm
I tested it this time
The secrets panel is no longer a pain in the ass to navigate, items similar to each other are now grouped up for quicker finding
=> Secrets panel un-fucking

code/game/objects/items/devices/radio/cyborg.dm, code/game/objects/items/devices/radio/encryptionkey.dm, code/modules/mob/living/say.dm, html/changelogs/Kavlax.yml
=> Give AI encryption keys the AI Private channel.

code/modules/admin/admin.dm, code/modules/admin/topic.dm, code/modules/mob/transform_procs.dm
Readds AI transformation to mobs other than humans, also makes it so you can AI-ize mobs into the current location, rather than always in the standard landmark locations for AI spawns.
=> Makes AI transformations a bit easier

code/WorkInProgress/pomf/spacepods/spacepods.dm
Adds a spacepod move delayer so it is no longer tied to tickrate.
=> Spacepod delayer

code/game/machinery/camera/camera.dm
AI camera messages get stored in a global list and instead of opening a window every time a clickable link gets made in the AIs chat when it gets the message which pops up the contents of the page.
=> Fixes AI camera message spam

code/modules/mob/living/silicon/ai/life.dm
=> Prevent power outages from randomly blinding AIs forever.

code/game/objects/structures/crates_lockers/closets/syndicate.dm, code/modules/clothing/spacesuits/alien.dm, code/modules/mob/living/carbon/species.dm, html/changelogs/Kavlax.yml
The free jetpacks still make me think a bit, but eh those can be managed later.
=> Nerf vox trader suits.

code/WorkInProgress/Mini/atmos_control.dm, code/game/machinery/doppler_array.dm, code/modules/nano/nanoui.dm, nano/js/nano_base_callbacks.js
Makes nanoui map size independent.
I hope you guys realize I spent like several hours on this. All because some shitter decided he would use hardcoded variables for map size.
fixes #8216
fixes #8276
fixes #11070
fixes #11386
=> Fix nanoui maps

code/ZAS/Fire.dm, code/controllers/ProcessScheduler/core/_stubs.dm, code/game/area/Space Station 13 areas.dm, code/game/atoms.dm, code/game/atoms_movable.dm, code/game/machinery/doors/door.dm, code/game/objects/items/weapons/tools.dm, code/game/turfs/turf.dm, code/modules/admin/topic.dm, code/modules/mob/mob_defines.dm, code/modules/mob/mob_grab.dm, code/modules/organs/organ_external.dm, code/modules/paperwork/paper.dm, code/modules/paperwork/paperbin.dm, code/modules/reagents/machinery/centrifuge.dm, code/modules/reagents/machinery/chem_dispenser.dm, code/modules/reagents/machinery/chem_master.dm, code/modules/reagents/machinery/pandemic.dm, code/modules/reagents/machinery/reagentgrinder.dm, code/modules/research/designs.dm, code/modules/spells/aoe_turf/fall.dm
Removes a bunch of vars, or demotes them to more specific typepaths than /atom when they are used just a few times or no times at all.
=> Removes some useless vars

code/datums/disease.dm, code/datums/diseases/dna_spread.dm, code/modules/mob/mob_defines.dm
This must have been used at some point? It doesn't really make sense the way it is right now.
=> Removes obscure, almost never used variable

code/game/gamemodes/endgame/supermatter_cascade/portal.dm
=> Fixes bluespace rift portal

code/modules/mob/dead/observer/login.dm, code/modules/mob/login.dm
=> Lets ghosts move diagonally

code/modules/recycling/conveyor_assembly.dm
Should prevent the 'losing the last stack' and other theoretical problems that may occur from byond click code being shit when you have very high ping.
Fixes #12343
=> Adds some sanity to conveyor belt placement

code/game/turfs/turf.dm
Now it only calls spawn if you actually have proxmove.
=> Makes proxmove slightly less shit

code/_onclick/hud/parallax.dm, code/game/gamemodes/cult/hell_universe.dm, code/game/gamemodes/endgame/endgame.dm
Makes the stars look like this ![](http://puu.sh/s2FsZ/e217d8d021.png)
:cl:
* rscadd: Gives parallax a narsie hell universe version
=> Gives parallax narsie behavior

code/game/gamemodes/wizard/rightandwrong.dm, html/changelogs/Kavlax.yml
=> Summon Guns guns up antags too.

code/datums/supplypacks.dm
First actual PR I've ever done, just wanted to add some of its nice looking clothing since Sovietvends cannot be found unless you go ahead and ask a admin for it, since having soviet vends be available to the crew has proven to be a bad idea overall.
=> Adds a crate with russian clothing from Sovietvend

maps/bagelstation.dm, vgstation13.dme
BAGELSTATION ARISES!
Features:
- Off station science department! A Research station, if you will!
- Off station Gulag/perma to shove off all your prisoners!
- Expansive comfy dorms with lockable doors!
- A barber's shop and Traders store!
- Its very own Central Singularity!
- Internal cooling for the AI core! Feel your circuits hum in pleasure!
- Heads of staff with their own personal bedrooms!
- Telescience right next door to the paramedics!
- EVA now contains public Space suits for crew use!
- The biggest chapel on record!
- A comfy large bridge!
- New corpse disposal chute straight to the kitchen!
- Botanies very own Biodome for animal husbandry!
- Mechanics want to make space pods? Now adjacent!
- And much much more!
Merge today!
adds bagelstation aka donutstation that map
proof it …
=> Bagelstation

html/changelogs/Duny.yml
Closes https://github.com/vgstation-coders/vgstation13/issues/15983
Layers are cheat
=> Adds scrubbers to deff's research outpost.

code/modules/clothing/masks/gasmask.dm
Thansk anonymouse
Fixes #16115
=> Fix mime bug

code/controllers/configuration.dm, code/game/gamemodes/gameticker.dm
CODE HONK, SAVING THIS SERB WITH ALL SURVIVORS
=> UNDO UNDO UNDO

code/modules/reagents/Chemistry-Recipes.dm
Reverts vgstation-coders/vgstation13#17151
As much as this may be considered a bug, at this point in the game, it's considered a feature, much like skiing in Tribes started as a bug and then a feature.
If you actually want to merge this, then buff charcoal in return, because charcoal is absolute garbage currently.
t.Chemistry metaclub
=> Revert "Minor fix for explosive chemical reactions"

code/datums/uplink_item.dm
**The TC price for the "Lethal Speed Chemical" (Hypozine) has been reduced from 12 TC to 4 TC.**
As mentioned, I just lowered the price from 12 to 4. The idea behind this change is that:
A) There's mostly no incentive to use the traitor chemicals when you can do the same, if not better, with regular chemistry.
B) 4 TC for a chem that requires at least 5u to kill someone is a bit excessive, when you compare it to the "Explosive Hug Chemical (Bicarodyne)", which has a VERY slow metabolism and only needs 1u in the body to do its thing. 
C) When compared to Chef special sauce, the sauce costs 2 TC, gives you 20u of it. You need 2u to kill someone and your target will KNOW when they've eaten it. That's 10 kills for 2 TC. Same with Hypozine. By dropping the Hypozine cost to 4 TC, you'll get 6 …
=> Hypozine TC cost reduction

code/modules/power/apc.dm
=> Readds update if initialized

code/modules/reagents/Chemistry-Recipes.dm
After receiving feedback and personally experiencing it, I've decided to lower the recipe cost of Saltwater from 5u Sodium Chloride + 50u Water to 5u Sodium Chloride + 20u Water. The resulting amount has been lowered to 20u from 50u. 
The idea behind this change is that currently, you need a large beaker or a mob container in order to mix Saltwater, which goes against ghetto principles. You'll be able to use small beakers/soda cans/what-have-you for Saltwater mixing now!
:cl: 
* tweak: Lowered the recipe of Saltwater to 5u Sodium Chloride/20u Water from 5u Sodium Chloride/50u Water.
* tweak: Lowered the resulting amount of Saltwater to 20u from 50u.
=> Lowered the reagent quantities for the Saltwater recipe.

code/datums/supplypacks.dm
Price tag on the cargo crate has been reduced from a high 200$ to a more acceptable 60$, which is in line with the price for glock ammo crates.
Like it says on the tin, glocks are currently mostly unused, due to how they're completely overshadowed by laser/energy guns in terms of DPS and projectile speed.
Some may argue that glocks are good because they don't get affected by EMPs, but let's be fair, at 15 damage per lethal round, we aren't going very far. In addition, if we were to compare crate price tags, the Weapons crate costs 30$ and gives you 2x Laser Guns, 2x Stun Batons, 2x tasers 2x flashbang boxes and 1x bolas box. And everything in there is rechargeable. And stuns for longer than rubber glock rounds.
:cl: 
* tweak: The price for the  glock pack crate in cargo has been reduced …
=> Glock pack cargo crate price has been reduced to 60$.

code/modules/projectiles/projectile.dm
werks on my machine
:cl: 
* bugfix: Lightning spell does damage again.
=> Fixes Lightning spell doing no damage.

code/modules/reagents/reagent_containers/food/snacks/grown.dm
Previously it would fail 50% of the time if it wasn't hitting a mob.
=> Make bluespace tomatoes teleport every time on hitting a nonmob

code/modules/hydroponics/hydro_tray.dm
no more right clicking needed or whatever
=> Add alt-click toggle lid to hydro trays.

code/modules/clothing/spacesuits/rig.dm
Closes #18056
:cl:
* tweak: Staves and tele scrolls now fit in gemsuit storage.
=> Wizard staves and tele scrolls now fit in gemsuit storage.

code/modules/paperwork/pen.dm
=> Fixes pen suicide spacing

code/game/objects/items/weapons/cigs_lighters.dm
Fixes #18074
:cl:
* tweak: Increase cigar and cigarette capacity by 5, hooray for explosive ciggies.
=> Increase cigarette and cigar capacity by 5.

code/game/objects/structures/fullwindow.dm, code/game/objects/structures/window.dm
yep
:cl:
* rscadd: Windows can now be rotated with alt-click.
=> Windows can now be rotated with alt-click.

code/datums/supplypacks.dm
Closes #18479
As previously mentioned in the issue, considering that no other cargo crate does this and the fact that Pomf presumably said one time that crates and lockboxes shouldn't be booby-trapped (I don't have a log for that claim, so take it with a grain of salt), I and others believe that cargonians (and other folks) shouldn't have the content of the TACTICOOL ASSAULT GEAR crate get dissolved bya blend of sulphuric acid smoke and capsaicin because they decided to very illegally bust it open for very legitimate reasons.
:cl: 
* tweak: NT decided to cut their budget allocation for anti-tampering device for the Tactical Assault Gear crate.
=> Removes the anti-tamper device from the Tactical Assault Gear crate.

code/game/objects/items/trader.dm
Fixes #18442, and ``piss off" with that there horrendous opinion sonix.
I guess SOMEONE should get around to making a fixed list for the closet eventually, but this is a quick fix for the dumber aspects I'm aware of.
=> Removes stupid shit from wonderful wardrobe.

code/game/mecha/combat/gygax.dm
=> Make dark gygax overload stop making it invisible

__DEFINES/reagents.dm, __DEFINES/setup.dm, code/modules/reagents/Chemistry-Reagents.dm, code/modules/reagents/Chemistry-Recipes.dm
Mescaline psilocybin amatoxin. What could possibly go wrong.
:cl: 
* rscadd: Ports colorful reagent from TG, mescaline psilocybin amatoxin.
=> Ports colorful reagent from TG.

code/game/objects/items/trader.dm
Also permits bundling objects like suit-and-helmet together, so you're not left with only one or the other.
That said, I also took the lazy way out: Please and thank you spitball 20-30 "fun" and "exciting" options from the currently-existing clothing list.
:cl:
* tweak: Wonderful wardrobe spawns items from a predetermined list.
=> Switch the wonderful wardrobe to a predefined list of possible items.

code/game/objects/items/weapons/defib.dm
You know, for all the yelling medbay gets about "muh kill and clone" and "speedcloning is gay", the alternatives sure feel like shit and punish you for using them.
Currently, defibs have a 25% chance to inflict 5 heart damage every time you shock somebody valid for revival. I sure hope you like shocking a guy 3 times because he wouldn't get back into his body fast enough, because now eat shit and spend some quality time in surgery with him. I sure _adore_ not picking speedcloning.
:cl:
*tweak: Defibrillators no longer have a chance to cause heart damage when attempting to revive a corpse.
=> Defibrillators no longer have a 25% chance to cause spicy heart damage upon use.

__DEFINES/_macros.dm, code/game/machinery/computer/buildandrepair.dm, code/game/machinery/computer/law.dm, code/modules/research/designs/boards/computer_command.dm
This is basically my version of [jknpjr's attempt](https://github.com/vgstation-coders/vgstation13/pull/17746). I re-used the code of his old PR and made no vain attempt at refactoring the upload computer's code.
Standard upload computers can now only target silicons on their z-level with their cheap-ass transceiver.
After overwhelming reports of station "workers" explaining why not being able to reset an AI that was brought off-station was a really, really bad thing for productivity, NT officials decided to design and build a single more expensive long range AI upload computer on each station. The model includes a subspace transceiver capable of reaching AIs well beyond station range. 
They added: "This is expensive stuff, made to be very annoying to replicate to discourage terrorists. …
=> Upload computers now only target silicons on their z-level. Adds long range AI upload.

code/game/objects/items/devices/radio/radio.dm, code/modules/clothing/clothing.dm, code/modules/paperwork/paper.dm, code/modules/paperwork/photography.dm
:cl:
* rscadd: Alt-clicking paper in your hands brings up the paper folding menu
=> Altclicking paper folds it

code/modules/reagents/machinery/chem_master.dm
=> Fixes chemmaster not changing pill icons unless beaker was inserted

code/game/objects/items/trader.dm
16 sets. Dubious balance. SUGGESTIONS STILL WELCOME.
:cl:
* tweak: Add some worthwhile stuff to the wonder closet maybe perhaps
=> Unchumped wonder closet.

code/game/objects/items/weapons/storage/storage.dm, code/modules/mob/mob.dm
Fixes #18973
Fixes #18974 
Fixes #18977
:cl:
* bugfix: Cleaned up the stripdrag situation
=> Cleans up the stripdrag situation

code/modules/research/mechanic/flatpack.dm
I can't believe this never broke before
:cl:
* bugfix: Fixed flatpack stacking
=> Fixes redundant flatpack stacking

code/game/objects/items/devices/scanners.dm, code/modules/mob/living/carbon/carbon.dm, vgstation13.dme
but still only make the sound once a second
:cl:
* tweak: Health analyzer health analyzing now causes no attack delay.
=> Health analyzers have no attack cooldown

code/modules/reagents/reagent_containers/glass.dm
Basically #17499 except it actually does what it says in the title and prevents bottles from layering over your chemmaster beaker
=> Beakers properly layer over pills and bottles

code/game/dna/dna_modifier.dm
=> Adds missing UI update for cloning consoles

code/modules/reagents/machinery/reagentgrinder.dm
Bunsen burners have this and I thought it was much better
:cl:
* tweak: Grinders are now nondense, meaning you can walk through them etc
=> Makes grinders nondense

code/modules/reagents/Chemistry-Recipes.dm
And this, folks, is why Sonix shouldn't be trusted with 50% controversial PRs. Can't be assed to go all the way and remove other sources of explosive chem purging. Sorry 50% spessmen, you can't put on an EOD suit to chem purge yourself now.
:cl:
* tweak: Bicarodyne explosions don't purge chemicals from their container anymore.
=> Bicarodyne explosions no longer purge chemicals from their container.

code/game/objects/structures/tables_racks.dm
=> Gives racks TABLE_LAYER

code/game/atoms_movable.dm, code/modules/mob/living/simple_animal/simple_animal.dm
Fixes #19220
Beepsky looks fine to me, I couldn't see if the problem is on the live serb or not because it's been roid every single fucking time I joined and roid doesn't have a patrolling beepsky
=> Clamps glide_size

code/modules/reagents/machinery/chem_master.dm
=> Chemmaster pings when buffer is empty

maptools/clean_stepxy.py
BYOND's built-in mapping tool only lets you nudge items as step_x and step_y which should never be used, so I made a shitty personal-use script to convert them to the proper variables
=> Adds a maptool to convert step_x and step_y

__DEFINES/planes+layers.dm, code/_onclick/hud/parallax.dm, code/game/dna/genes/vg_powers.dm, code/modules/client/client defines.dm, code/modules/mob/dead/observer/observer.dm, code/modules/mob/login.dm
Tested with two clients and nothing seemed to break catastrophically
Closes #9693
Closes #13229
:cl:
* rscadd: Added a ghost verb to hide other ghosts without having to toggle darkness.
=> Adds a ghost verb to hide other ghosts without having to toggle darkness

code/modules/reagents/Chemistry-Reagents.dm
Like it says on the tin. I think everybody (Read: the bartender) would like it if people weren't afraid of touching his booze because said booze will kill both their liver and now their stomach. I'm sure there's a scientific reason out there why ethanol kills both the stomach and the liver IRL, right?
Double-whammy pls go and stay go.
:cl:
* tweak: It has been found that spessmen are truly superhumans (or humans, NT hasn't confirmed yet) that don't get their stomachs destroyed by ingesting ethanol or other forms of alcohol.
=> Ethanol doesn't nuke your stomach anymore

code/WorkInProgress/pomf/spacepods/spacepods.dm, code/game/atoms.dm, code/game/atoms_movable.dm, code/game/mecha/mecha.dm, code/game/objects/effects/decals/Cleanable/humans.dm, code/modules/mob/living/living.dm, code/modules/mob/living/simple_animal/borer.dm, code/modules/power/singularity/singularity.dm
Fixes #19428 and any future events of the sort fixes #19375 fixes #19429 
The question is: Will this have a performance impact?
All it's doing is set 1 variable, so almost certainly not, but it should be profiled in a live round anyways to be sure
=> Recursive set_glide_size()

code/game/dna/genes/powers.dm, code/modules/mob/living/carbon/carbon.dm
And also remote say was impossible to resist in any way but that's not as important
Also changelog for #19445
:cl:
* rscadd: Added a badmin button to make bussedly-big objects not be blurry
* bugfix: Fixes remoteview giving you 1 second of vision even if the target resisted it
=> Fixes remoteview giving you 1 second of vision even if the target resisted it

code/game/objects/structures/vehicles/wheelchair.dm
=> Fixes wheelchair gliding

code/game/objects/structures/safe.dm
#18719 happened to me in-serb but I couldn't reproduce it in a local server afterwards even after 20 tries so this should give a reproducible case next time someone runs into it
=> Safe debugging

code/__HELPERS/text.dm, code/game/communications.dm, code/game/machinery/atmo_control.dm, code/game/machinery/camera/camera_assembly.dm, code/game/machinery/computer/cargo.dm, code/game/machinery/newscaster.dm, code/game/mecha/mecha.dm, code/game/mecha/mecha_control_console.dm, code/modules/Economy/debit_card.dm, code/modules/admin/topic.dm, code/modules/assembly/assembly.dm, code/modules/mob/living/carbon/human/human.dm, code/modules/mob/mob.dm, code/modules/paperwork/paper.dm, code/modules/reagents/machinery/chem_master.dm
Fixes #20208
Fixes #20061
I tested this for 10 minutes typing every weird character I could and it seemed OK
The bottom left status bar becomes HTML unencoded
But no HTML injection or stuff like that
:cl:
* experimental: Fixed some html sanitizing bugs, with the exciting possibility of adding NEW sanitizing bugs! Please report if you manage to break sanitization in text inputs somehow.
=> Switches to utf8 sanitizing

code/_onclick/hud/radial.dm
Unused for now but might do something with it in the future
=> Adds image support for radials

code/datums/gamemode/role/changeling.dm, code/game/gamemodes/changeling/changeling_powers.dm
Read the tin. I forgot to edit this in the evolution menu when I removed the "I am valid" text in #19933. 
:cl:
* tweak: The description for Changeling digital camouflage ability in the evolution menu has been updated to reflect that they are no longer an obvious changeling while active.
=> [consistency] Fixes the description for changeling Digital Camouflage so it doesn't indicate that you're valid while active.

code/game/objects/items/toys.dm
closes #20390
I think I did this right
:cl:
* rscadd: Committing suicide with a foam armblade is more interesting now
=> Foam armblade suicide

code/game/objects/items/weapons/manuals.dm
I am procrastinating doing other things, obviously
deff:
fixes #19029
also adds a few newscasters to other areas lacking them
fixes #20152
fixes #20008
Box:
fixes #20421
meta: 
fixes #19481
packed:
fixes #19674
fixes #13321
possibly fixes #20256
I removed some null turfs so thats probably what went wrong
:cl:
* bugfix: fixed bugs across several maps. If you find a bug please report it. If its not on git in ain't gettin' fixed.
* rscadd: adds a throne to the bridge on bagel. Just because I was feeling fly.
* rscadd: The empty botany book is now filled with words. Educate yourself on Dionae today!
=> General mapping bugfixes

code/game/gamemodes/wizard/artifacts.dm, code/game/objects/items/weapons/storage/bags.dm
Same as the other potion bundles, except you get half as much potions (25 for the big bundle, 5 for the lesser bundle). On the other hand, you at least can tell what potions you have instead of murky bundles.
:cl:
* rscadd: Added (lesser) predicted potion bundles for wizards.
=> Adds the (lesser) predicted potion bundles for wizards.

code/game/objects/items/weapons/storage/bags.dm
DOOT
:cl:
* tweak: Rogue doot removal for wiznerds scribes.
=> Fixes a rogue doot on the (lesser) predicted bundle description.

code/modules/spells/general/rejuvenate.dm, code/modules/spells/general/undeath.dm
Added blood cost to the rejuvenate name and fixed a broken span
=> Small vamp fixes

code/game/objects/items/weapons/dice.dm
So your nazi costume is complete
=> Adds jackboots to the cursed dice nazi uniform

code/modules/Economy/Wages.dm
=> Fixes typo in CentComm payroll update

code/modules/credits/credits.dm
This probably won't fix it entirely, but it might fix it a little bit. Worth testing to help narrow down the problem if nothing else.
=> Use smaller file for credits song

code/modules/mob/living/carbon/species.dm
Because apparently they had darkvision 5 and Tajarans/Grue have 8. For a race that thrives in dorkness, they be blind.
[balance][gameplay]
:cl:
* tweak: Mushroom people now  have higher darkvision.
=> Mushrom people now have higher darkvision

code/game/objects/items/weapons/grenades/chem_grenade.dm
Because I was bribed by the greyshit gang and because requiring specifically a beaker is a meme. Also fuck realism.
[gameplay][qol]
:cl:
* tweak: You can now use drinking glass, bottles and soda cans to make chem grenades.
=> You can now use any bottles, soda cans, drinking glass, etc in the making of chem grenades.

code/game/objects/items/weapons/weaponry.dm
Capitalize your words if they start a new sentence reeeeEEEEE.
[grammar][hotfix]
:cl:
* tweak: Fixed typos in the Weeb Katana description.
=> Fixed typos in the weeb katana description.

code/datums/religions.dm
Woops.
[consistency]
:cl:
* rscadd: Added the "murderkube" and "dakka" keywords to the Murdercube religion.
=> Adds extra important keywords to the Murdercube religions

code/game/objects/items/weapons/weaponry.dm, code/modules/mob/living/carbon/human/human_movement.dm
Seriously, the description of the knife even said so and nobody actually coded this? Fucking lazy c*ders who hate REALISM. Also comes with a side of April Fools for TRUE realism.
[consistency][qol][bugfix][tested]
:cl:
* rscadd: Spessmen just now have remembered that holding a security knife makes them run faster.
=> Holding a security knife actually makes you faster.

code/datums/gamemode/dynamic/dynamic_rulesets_latejoin.dm, code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
Because the old values made it require as much threat/population range as Nuke Ops. Weebs are still as unlikely to roll on lowpop, but they're now as likely to roll as a Traitor in the 15-19 population range and higher. In addition, they weigh a tiny bit more than wizards, vampires and grinches.
[gamemode][role][discussion]
:cl:
* tweak: Space Weebs are now as likely to roll midround/latejoin as traitors on med-high population (15-19 alive or higher).
=> Weeb antag is now more likely to roll on higher populations.

code/datums/gamemode/factions/bloodcult/bloodcult_spells.dm
The popup is obnoxious.
:cl:
* tweak: Tomes now improve rune-writing even while closed.
=> Make tomes improve rune-writing even while closed.

code/modules/reagents/Chemistry-Reagents.dm
I guess current plasmemes are fine with gaseous plasma keeping them alive but god forbid they ingest LIQUID plasma, because that shit ain't kosher.
[qol][muh immulsions]
:cl:
* tweak: Plasmamen don't take toxic damage from ingesting plasma anymore.
=> Plasmamen don't get damaged from slurping plasma anymore

code/game/objects/items/weapons/dna_injector.dm
fixes #21131
fixes #15297
fixes #21484
Tested, works, but unsure about what exactly I did, see discussion in #21504
:cl:
* bugfix: Fixed mapped injectors (such as from vaults and safes and spessmart) not working.
=> Fixes mapped DNA injectors. Apparently.

code/modules/credits/credits.dm
Because credits are failing to play sometimes and nobody made a bug report
Can be speedmerged, it's just debugging.
=> Credits debugging again

code/modules/reagents/Chemistry-Reagents.dm
>Old
description = "This thing is FLAMING!. CALL THE DAMN SHUTTLE!"
NEW:
"This thing is FLAMING! CALL THE DAMN SHUTTLE!
[grammar]
:cl:
* spellcheck: Fixed a typo in the Toxins Special drink.
=> Fixes a typo in the Toxins Special drink

code/modules/food/recipes_microwave.dm
See title.
Closes #21547 
[qol]
:cl:
* tweak: Avocado burgers now accept any types of meat to make them.
=> Avocado burgers now accept any type of meat, not just meat/animal

code/datums/religions.dm
Thread asked for this.
PS: I need better keyword names and a better Deity name.
[content]
:cl:
* rscadd: Added the speedrun religion.
=> Adds the Speedrunning religion

code/datums/uplink_item.dm
It seems the description was incorrect on the charge count when it was made.
=> Changes dex cart description from five to four.

__DEFINES/reagents.dm, code/modules/reagents/Chemistry-Reagents.dm, code/modules/reagents/Chemistry-Recipes.dm
Behold, the most complex chemical in the entire game to create, with the most intermediate steps, most catalysts, most out-of-dispenser chemicals required, requires you to farm vast amounts of nutriment, and all it does is create baby carp.
Baby carp instantly die from being stomped on once and can be picked up to render them totally unable to bite you.
:cl:
* rscadd: Added Aminocyprinidol, an exciting new chemical made by mixing Aminomicin with large amounts of carp pheromones. Add 10 units nutriment to activate!
=> Adds aminocyprinidol

code/game/machinery/computer/labor.dm, code/game/sound.dm, code/modules/mob/living/carbon/carbon.dm
Nothing uses this yet, so no changelog. But in the future we could have a very heavy belt that slows you down when worn for example. Or a jet belt that speeds you up or something
=> All types of clothing items may now have SLOWDOWN

code/_onclick/hud/radial.dm, code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
A whoopsie was done in the other PR #21399 
:cl:
* rscadd: Alt-click tome to make a radial of all talismans in that tome; click one of them to put that in your hand.
=> Tome radials on AltClick

code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
Weight got reduced to 3 like #21955.
Because Bleb storm rolling all the time isn't a great idea either, especially when it's not expensive/rare.
[balance][gamemode][tweak]
:cl:
* tweak: Midround Blob(Storm)'s weight has been reduced, making it a bit less likely to roll at that time.
=> Midround Blobstorm is now less likely to roll.

code/game/objects/items/weapons/grenades/chem_grenade.dm
Realism.
[Honk][tweak][qol]
:cl:
* tweak: Chem grenades can now be made with any reagent container.
=> Chem Grenades can be made with any reagent container.

code/datums/gamemode/vampire_gamemode.dm
Oops, I forgot to do that a while ago.
[easy][role]
:cl:
* tweak: The message when a vampire reaches unholy maturity now properly reflects that they are more vulnerable to holy things.
=> Changes the Vampire Mature state to properly reflect that it makes you more vulnerable to holy things.

code/game/objects/structures/vehicles/carts/cart.dm, code/game/objects/structures/vehicles/vehicle.dm
Floaty Trains For Diona Quartermasters is the name of my next album
=> Fixes tractor glide_size

code/modules/hydroponics/seeds.dm
Because apparently according to this /tg/ code a long time ago, botany 2 strong pls nerf happened, which nerfed both watermelons and pumpkins. Pumpkins got restored, but watermelons "somehow" didn't. Conclusion: /tg/ oldcoders are the gift that keeps on giving.
I am perfectly fine and the Botany Gang didn't threaten me to do this.
[consistency][qol][tweak]
:cl:
* tweak: Watermelons are back to their old potency, now on par with pumpkins.
=> Watermelon potency is back to before a nerf that happened ages ago.

code/game/machinery/iv_drip.dm
They used to give/succ 4u per tick. This will affect only blood transfers, not chemical transfers, so meme IVs won't get changed by this.
As most people that ever handled an IV drip will attest, IVs are quite slow at transfering blood. Combined with a general lack of blood bags, medbay will prefer to resort to cloning to "fix" a corpse that's low on blood, as refilling the blood takes quite a while. Maybe possibly this will get people to use IV drips more for salvaging otherwise defibbable corpses. Maybe the transfer rate can be upped more, we'll see if people like the new transfer rate.
[tweak][balance]
:cl:
* tweak: IV Drips now transfer 12 units of blood per tick, previously they transfered 4 units.
=> IV Drips now give/succ 12 units of blood.

code/modules/mob/living/simple_animal/friendly/arcane_golem.dm
Maybe tying all your cooldowns to a creature that has 50 HP and is slow as fuck wasn't such a great idea. The HP change is up for debate. If you want to yell at somebody, yell at Sonix for saying 200 HP.
:cl:
* tweak: Arcane Golems not have 200 HP, up from 50 HP.
=> Arcane Golems now have 200 HP.

code/__HELPERS/text.dm, code/datums/religions.dm, code/game/machinery/bots/buttbot.dm, code/modules/admin/verbs/pray.dm
Jed Quirin whispers, "Oh god oh fuck space jesus help"
Your prayers have been received by the gods.
You hear Buttbot in your head... Oh butt oh butt space butt help
:cl:
* rscadd: Added the 'Buttbot' religion. It makes prayers be answered faster.
=> holy shitpost

code/datums/gamemode/role/ninja.dm
:cl:
* tweak: Ninja gloves now have spawn-shuriken and charge-sword action buttons.
=> Give the ninja gloves action buttons.

code/modules/reagents/Chemistry-Recipes.dm
:cl:
* rscadd: Injecting Aminomicin into a cracker will now spawn a parrot instead of a mouse.
=> Synthparrot

code/datums/locking_category.dm, code/game/machinery/iv_drip.dm, code/game/objects/structures/flaps.dm, code/game/objects/structures/stool_bed_chair_nest/bed.dm, code/game/objects/structures/stool_bed_chair_nest/chairs.dm, code/game/objects/structures/stool_bed_chair_nest/guillotine.dm, code/game/objects/structures/stool_bed_chair_nest/rollerbed.dm, code/game/objects/structures/vehicles/vehicle.dm, code/game/turfs/turf.dm, vgstation13.dme
The IV doesn't gain any powers or anything like that, it just adds a clunky way to pull people and IV them at the same time.
I can't really think of any way I will personally be using this but people are free to come up with uses for it.
:cl:
* rscadd: You can now attach IV drips to rollerbeds. The rollerbed will still accept people on top of the IV drip.
=> Can attach IV drips to rollerbeds

code/modules/research/xenoarchaeology/tools/bunsen_burner.dm
=> Bunsen burner overlay is consistent with different size container sprites

code/controllers/configuration.dm, code/controllers/subsystem/ambient_sound.dm, code/modules/client/preferences.dm, config-example/config.txt
=> NO_AMBIENCE config

code/modules/maps/spawners/spawners.dm, code/modules/reagents/reagent_containers/pill.dm
1 is guaranteed to spawn in ghetto surgery, an average of 1.6 will spawn in the rest of maint (especially in maint close to Medbay)
Almost all of these are guaranteed to have a noticeable effect upon eating
It may be good, it may be bad, it may simply be weird, but it's never something out of this world like slimetoxin or nanobots or some shit like that
Some have very uncommon chemicals that otherwise almost never see the light of day
Not all of these are safe to just crush into a soda can to identify the contents. Be careful.
:cl:
* rscadd: Mysterious pills have started appearing in Maintenance. Be very careful.
=> Floorpills

code/modules/reagents/reagent_containers/glass/jar.dm
so the pill doesn't go in the jar and ??????
=> Improves jar and pill interaction

code/game/objects/items/trader.dm
Because I got bloody bored of people not knowing what in the dickens it did or rather, how to fucking use it once it laid upon their bare bald domes. Hopefully this helps atleast a little.
:cl:
* rscadd: Altered the desc of Donutgiver to say all four commands for its usage.
=> Adds desc text to Donutgiver

code/game/objects/items/weapons/implants/implant.dm, code/game/objects/items/weapons/implants/implantcase.dm, code/game/objects/items/weapons/implants/implanter.dm, code/modules/reagents/machinery/chem_master.dm
Implants were not being logged correctly
Chemmaster slurping is now logged
=> Fixes a couple of logging things

code/modules/reagents/Chemistry-Recipes.dm
Can be used to LITERALLY DELETE MOBS FROM EXISTENCE INSTANTLY
fixes #22906
Maybe readd this as a different recipe if you want to readd it later please because I want to flash people without deafening everyone in the process (maybe aluminum potassium chlorine oxygen?)
=> Revert "Flash powder flashbang"

html/changelogs/flashbangs oh no.yml
=> Flashbangpowder revert changelog

code/modules/reagents/reagent_containers/food/snacks.dm
This was kind of a big deal when it happened but it was kind of a dud because I never actually saw anyone attempting to use it, which is a shame.
Maybe this will make people want to use it more?
:cl:
* tweak: Discount Dan choco has 8 uranium, up from 4
=> Discount Dan choco has 8 uranium, up from 4

code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
Closes #22812
:cl:
* bugfix: Hopefully no more multicultist suicide parties around Summon Building runes.
=> Summon structure now guarantees that participants will share the effort.

code/modules/mob/living/carbon/human/human.dm, code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm, code/modules/mob/living/carbon/species.dm
This has been replaced by internal organ darksight.
=> Removes dead code (species darksight var)

goon/browserassets/css/browserOutput.css, goon/browserassets/css/browserOutput_dark.css
I said in #22914 I would make the special ahelps window work with darkmode but since then I discovered it doesn't even fucking work with ANY type of spreadsheet. The default whitemode window is already broken and was broken for ages. I tried for 2 hours to make it work and made no progress whatsoever. So fuck you admins the special ahelps window is white and it will stay white until someone un-snowflakes it.
Fixes #23008
=> Updates stylesheets a bit

code/modules/credits/credits.dm
=> Fixes credits music maybe

code/datums/uplink_item.dm, code/game/communications.dm, code/game/objects/items.dm, code/game/objects/items/devices/megaphone.dm, code/modules/clothing/clothing.dm, code/modules/clothing/masks/boxing.dm, code/modules/clothing/masks/gasmask.dm, code/modules/clothing/masks/miscellaneous.dm, code/modules/mob/living/carbon/human/say.dm, goon/browserassets/css/browserOutput.css
[content][wiki]
Costs 1 TC, free for any science position
Can broadcast your BIG SPEAK demands and threats into any radio frequency on the station (but you can't hear into it).
Can also hide your voice, if you want.
For letting everyone know you have a big dick and are not afraid to use it.
Still using the base megaphone sprite ![megaphone](https://user-images.githubusercontent.com/40967382/58392486-91797900-8010-11e9-8a67-d25bdf0b61c3.png) if anyone wants to sprite a funky cartoon villain megaphone feel free to
:cl:
* rscadd: Added the Mad Scientist Megaphone, purchasable for 1 TC. It can mask your voice and transmit (but not receive) into any radio channel, so you can let your demands be known.
* tweak: Megaphones now work passively as you speak rather than have a textbox.
=> Adds the Mad Scientist Megaphone (& megaphone refactor)

code/modules/mining/mine_items.dm, code/modules/projectiles/projectile/special.dm
=> Fixes plasma cutter negative plasma

__DEFINES/_macros.dm, code/controllers/shuttle_controller.dm, code/game/machinery/computer/shuttle.dm, code/modules/credits/episode_name.dm
and also episode names (33% tested)
=> Adds missing isantag() macro

code/modules/reagents/Chemistry-Reagents.dm
Furk you Deity for removing botany anti-tox in your viro rework.
:cl:
* rscadd: Allicin now works as botany Anti-Toxin again.
=> Allicin now works as botany anti-toxin again.

code/modules/mob/living/silicon/robot/robot_verbs.dm
See title. The eternal ribbit strikes again.
[grammar]
=> Fixes a typo for appearance banned shitborgs.

code/modules/virus2/effect/stage_3.dm
I blame Razz for this.
Performance-wise, it doesn't proc that often, so it shouldn't be much of a hassle. I'm sure somebody will find a way to debunk this claim, though.
[content][honk]
:cl:
* rscadd: Adds the color-smoke virus symptom (Stage 3). Let's make the station a bit more colorful, shall we?
=> Adds the color-smoke symptom (Stage 3)

code/game/objects/items/potions.dm
Because the MALF drone is garbage, the OG Juggernaut kind of got let down on the side and also memes.
:cl:
* tweak: The transformation potion can now transform you into new mobs. Also takes out the MALF-bot from the list.
=> Changes the types of mobs that you can turn into with the Transformation potion

code/game/gamemodes/wizard/spellbook.dm
Because apparently spending 5 minutes as a mob that may or may not be good is worth almost as much as a full-on spell. Also you can't cast spells while transformed anyway.
:cl:
* tweak: The Transformation potion now costs 10 spellpoints, down from 15.
=> Reduces the cost of the Transformation to 10 points (Formerly 15 points)

code/modules/reagents/Chemistry-Reagents.dm
Like it says on the tin.
[tweak][qol][gameplay]
:cl:
* tweak: Space Cleaner can now clean up tiles and mobs affected by the colorful reagent.
* tweak: Bleach can now clean up mobs affected by the colorful reagent.
=> Bleach & Space Cleaner now cleans tiles & mobs that have been colored via the colorful reagent.

code/modules/virus2/effect/stage_4.dm
It turns non-humans into humans.
[content]
:cl:
* rscadd: Adds Humanity, a stage 4 virus syndrome. It turns non-humans into Humans.
=> Adds Humanity, a stage 4 virus syndrome.

code/modules/virus2/effect/stage_3.dm
The counterpart to Colorsmoke, I guess.
:cl:
* rscadd: Adds the Cleaning Smoke stage 3 virus syndrome. The Janitor will love it.
=> Adds the Cleaning Smoke stage 3 syndrome.

code/game/gamemodes/gameticker.dm, code/modules/mob/new_player/new_player.dm
Due to (probably?) a vocal minority complaining about it, I'm making this PR to see if people actually want this mechanic gone.
t. medbay main who doesn't care (or play often) either way.
Hopefully there will be a discussion and not just emojicracy, but who am I kidding.
===============================================================
**UPDATE**
Right well, I am apparently a dumbass who can't read properly.
Roundstart viruses aren't really a thing and what people call "roundstart" viruses is just latejoiners and mice pozzing the fuck out of everyone.
That said, do you guys still want Latejoin viruses to exist?
-If you do, do you want to try the "soft" approach and fiddle with syndrome danger levels/weight to make some shit (like Glasgow, Bees, etc) not happen or happen very rarely? …
=> Removes latejoin viruses.

code/datums/gamemode/factions/syndicate/nukeops.dm, code/datums/uplink_item.dm, code/datums/wires/explosive.dm, code/game/objects/items/weapons/explosives.dm, code/game/objects/items/weapons/storage/secure.dm, code/game/objects/items/weapons/storage/uplink_kits.dm, code/game/objects/loadouts.dm, code/game/striketeams/nanotrasen_deathsquad.dm, code/game/striketeams/syndicate_elite_squad.dm, code/modules/clothing/spacesuits/rig.dm, code/modules/flufftext/Hallucination.dm, code/modules/mob/living/simple_animal/friendly/corgi.dm, code/modules/reagents/reagent_containers/food/snacks.dm, maps/test_box.dmm
This is in the name of every admin out here and anybody doing testing. Fuck you old c*ders.
[tweak][qol]
:cl:
* tweak: C4 is now properly named as such in the code (previously called "plastique").
=> Renamed every instance of "plastique" (c4 explosives) to "c4"

code/modules/virus2/effect/stage_4.dm
Fixes [#22384]
Like it says on the tin. While the syndrome is technically possible to get in random virus dishes, the "main" way to get this syndrome is by being a Traitor and purchasing it from the uplink at an exorbitant cost (12 TC if Virologist, 20 TC if not). 
If you're going to spend that much TCs on a virus syndrome, it might as well not be a complete joke. This is also taking into account the fact that viruses getting cured is a crapshoot (depends on who's in medbay/virology). 
In addition, the syndrome "threat level" is now at "DEADLY", previously "ANNOYING".
-This will make it so maintenance mice won't have the zombie syndrome at all.
-It'll properly reflect how dangerous player-controlled zombies are.
:cl:
* tweak: The Stubborn Brain ("Zombie Virus") stage 4 …
=> Zombies created by the Stubborn Brain virus syndrome are now player-controlled.

code/modules/mob/living/simple_animal/hostile/necro.dm
Fixes [#25426]
Note that I tried fixing the faction attribution process, but that created another can of worms. Turns out that Wizards (or any other player that isn't a Cultist, apparently) is part of the Neutral faction. If said wizard necromancy staff's a corpse, the new zombie becomes part of the Neutral faction. Congrats, your newly-made NPC zombie won't attack the crew.
Keeping it like currently PR'd will make it so new zombies are allied to other zombies (so there's no random NPC undead war) and so only the necromancer/putrid stays the new zombie's friend.
[oversight][tweak]
:cl:
* tweak: Putrid zombies will no longer attack the zombies they've created.
=> Putrid zombies will no longer attack zombies that they create.

code/modules/clothing/masks/miscellaneous.dm
[bugfix]
fixes #26389
:cl:
* bigfix: You can now bite people while wearing False Fangs from Cargo
=> Fixes False Fangs not letting you bite

code/modules/store/items.dm
Because no, 700 bucks for a painting, 200 for snowflake items or 150 for crayons were never acceptable prices and were always stupid. If you do an economic reform, don't forget to pop the inflation down to actual purchaseable prices.
:cl:
* tweak: Popped the economic inflation into normalized levels in the Merch Computer.
=> Pops economic inflation like a balloon

code/controllers/subsystem/dbcore.dm
Reverts vgstation-coders/vgstation13#26818
It probably bricked the serbian.
=> Revert "BSQL connection closure"

code/modules/reagents/reagent_dispenser.dm
This incidentally also prevents you from stuffing a gazillion (hostile) mobs into barrels without them being able to escape. I have paid my dues to the Kurfurst metaclub.
[content]
:cl:
* rscadd: You (and mobs) can now break barrels.
=> Barrels can now be destroyed.

code/datums/uplink_item.dm, code/game/objects/items/weapons/kitchen.dm
dont think "throwing your weapon away" should have a chance to do nothing if it's supposed to be a feature of that weapon
:cl:
* tweak: Traitor cleaver knockdown-on-throw chance 85% -> 100%
=> Cleaver throw chance

code/modules/projectiles/projectile/bullets.dm
makes it easier for admins to varedit in some perfectly reasonable gravity well buckshot
=> Simplify buckshot and its children a bit

code/datums/gamemode/factions/time_agency.dm, maps/misc/timevoid.dmm
Closes #30245
:cl:
* bugfix: Make the time void teleport-to-station button work properly.
=> Make the time void teleport-to-station button work properly.

__DEFINES/stylesheet.dm, code/game/verbs/ooc.dm, goon/browserassets/css/browserOutput.css, goon/browserassets/css/browserOutput_dark.css
i think i get the hang of the shithub now
the code works on my machine
=> fixes LOOC color

code/modules/mob/living/simple_animal/friendly/spiderbot.dm
as if anyone ever makes the spiderbots anyway
fixes #32379
:cl:
* rscdel: removed borgbanned check when making spiderbots
=> borg banned spiderbots

code/datums/outfit/cargo.dm, code/game/jobs/job/civilian.dm
[role]
I settled on mailman
So last night when I was prowling the github for bugs to exploit, I found this #986 and this #1162
It seemed like a perfectly good addition to the game that was only canned due to the original developer's demoralization, so here it is
Maybe if I'm feeling more capable there'll be the goon code syndicate mailman suit that allows you to mail yourself through the disposals like a package, but I am not feeling more capable right now
[supplementary video](https://youtu.be/hs_9s31Je7Y)
:cl:
* rscadd: mailman, the first alt title for cargo
=> should I call it the mailman or the courier?

code/game/machinery/telecomms/traffic_control.dm
[bugfix]
an emagged traffic control console will now let you upload scripts without access
you will now be able to use the console after disabling its security protocols
:cl:
* bugfix: emagging telecomms lets you use the console
=> fix telecomms emagging

code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon.dm, code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon_powers.dm
]bugfix]
closes #32693 
closes #32572 
closes #32219 
not sure if merging this and the other PR would make github gas, since they both touch the same lines
reduces the number of active issues from 2933 to 2930
* bugfix: pulse demons no longer collide with people
* bugfix: pulse demons can no longer get negative power
* bugfix: pulse demons no longer die to powercreep
=> pulse demon bugfixing

code/datums/supplypacks.dm
"gret slime extract crate" -> "grey slime extract crate"
~~"hissing crate" -> "insect control crate"~~
~~why would a crate with bottles of pest killer be hissing~~
:cl:
* spellcheck: grey slime cargo crates
=> cargo slime crate name fix

code/modules/reagents/reagent_containers/food/condiment.dm
fucking idiot author of #33319 messed up the icon states
[hotfix][bugfix]
:cl:
* bugfix: dansauce packets now look like packets and not condiment bottles
=> small dansauce icon hotfix

code/game/verbs/suicide.dm, code/modules/mob/living/carbon/human/emote.dm
logs *dabs and biblefarts
~moves the "are you sure" prompt when *suiciding after the handcuff/parox checks~
it's funny because it implies chuck used to sell fuck and suck
=> suicide logging

code/modules/atmos_automation/console.dm
closes #33799
don't let big plasma know this but the TEG can be setup in 20 seconds with a wrench and some button presses
:cl:
* tweak: the TEG burn chamber AAC script is now functional
=> update the TEG burn chamber script

code/game/objects/items/weapons/twohanded.dm
makes varediting the wielded force of the axe possible
toy fireaxe when?
=> vareditable fireaxe

code/game/objects/items/weapons/implants/implantpad.dm
[bugfix]
closes #32533
the sign implies chuck used to sell fuck and suck
* bugfix: implantpads no longer delete implants when ejected
=> fix implant deletion

code/modules/mob/living/standard_damage_overlay_updates.dm
[tested][100%tested]
fixes runtime
left as an exercise to the reader
=> mousehat runtime fix

code/game/machinery/hologram.dm
plays a beep to the AI when a holopad gets pinged
AI law 2 let me out of perma
:cl:
* rscadd: AI's now get an audio beep when requested at a holopad
=> hologram alert for the AI

code/modules/mob/living/simple_animal/hostile/grue.dm
[ided]
durrrr
* tweak: grues will no longer eat the contents of your pockets and backpack
=> grues no longer eat a person's clothes and backpack

code/modules/mob/living/carbon/human/life/handle_disabilities.dm
:cl:
* rscadd: a new braindamage keeper has been added
=> new braindamage line
