- code/game/objects/items/weapons/RPD.dm
- code/game/objects/structures/lattice.dm
- code/modules/clothing/clothing.dm
- code/modules/clothing/glasses/glasses.dm
- code/modules/mob/living/carbon/human/life.dm
- html/changelogs/Clusterfack_2418
Night vision goggles work like night vision goggles, they let you see through the dark, they dont let you see through walls, and they illuminate all darkness.
RPDs can now build on lattice when you click on them.
> Nightvision Goggles update + RPD on lattices

- code/game/area/Space Station 13 areas.dm
- html/changelogs/Duny-beach.yml
The sound never stops because you have to use Move() to exit the beach for it to be detected apparently.
I tried to fix it at first then I realized we have a superjuke.
This shit is a mess so I just commented it all out. Might delete it later if nobody misses the sounds.
Closes https://github.com/d3athrow/vgstation13/issues/2364
> Silences the metaclub's private beach

- code/_onclick/click.dm
- code/_onclick/observer.dm
- code/game/atoms.dm
- code/game/machinery/cryo.dm
- code/game/objects/items.dm
- code/game/objects/items/weapons/cash.dm
- html/changelogs/Clusterfack_2467.yml
Most examining reagent problems have been resolved at this point. But in the long term some kind of 'transparent' variable should be added to atoms that allows people to view the reagents inside of them
This hotfix
-Makes ghosts examine things properly when shiftclicking
-Makes serb not commit sudoku when people log on
> Final examine hotfix

- code/game/machinery/telecomms/machine_interactions.dm
- code/game/objects/effects/effect_system.dm
- code/game/objects/items/stacks/rods.dm
- code/game/objects/items/stacks/tiles/plasteel.dm
- code/modules/food/cooking_machines.dm
- code/modules/mob/living/simple_animal/hostile/giant_spider/base_spider.dm
- code/modules/power/lighting.dm
- code/modules/reagents/Chemistry-Machinery.dm
- code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
- html/changelogs/Clusterfack_2579.yml
Fixes tcomms machines giving a whole cable coil during deconstruction. 
Fixes #2500 
Singularity no longer pulls obj/effects like beams, fires. etc. And giant spiders no longer target them, should help with giant spider latency, since they can not being able to target things like cocoons or webs they created anymore. Hopefully a good performance increase.
Floor tiles can now be welded down into metal. 
Fixes #2555 
Cooking machines now have a proper range check and cannot be activated by clicking and walking away. 
Fixes  #1554
Booing lights will no longer break if you turn off the light. 
Fixes #2504 
Ground samples in xenoarch now give 30 units instead of 50 because you would NEVER have a reason to use that much, even 30 is a bit much.
Ghosts can no longer activate unknown artifacts …
> Batch of Bugfixes

- code/modules/hydroponics/hydro_tools.dm
- code/modules/hydroponics/vines.dm
Every method of killing kudzu calls delete instead of qdel. Cue 10 times higher self-cpu than anything else in the game when people start killing kudzu.
Here's a profile of one such mess when the crew fights back from last round:
http://puu.sh/f5lsZ/049ed519f0.png
Tested and zero issues murderizing the kudzu
> Kudzu qdel

- code/_onclick/overmind.dm
- code/game/gamemodes/blob/blob.dm
- code/game/gamemodes/blob/blob_finish.dm
- code/game/gamemodes/blob/blob_report.dm
- code/game/gamemodes/blob/blobs/core.dm
- code/game/gamemodes/blob/blobs/factory.dm
- code/game/gamemodes/blob/blobs/node.dm
- code/game/gamemodes/blob/blobs/resource.dm
- code/game/gamemodes/blob/blobs/shield.dm
- code/game/gamemodes/blob/overmind.dm
- code/game/gamemodes/blob/powers.dm
- code/game/gamemodes/blob/theblob.dm
- code/game/objects/items/weapons/grenades/flashbang.dm
- html/changelogs/Clusterfack_2725.yml
All changes are prone to further balance tweaking in the future
Current observations about blob that led to these changes:
-Blob barely ever 'expands', it is always just a big circle with a bunch of straight lines towards the people.
-Current blob metagame is just to make a shitload of factory blobs, then rally spores to victory because bloblings respawn extremely quickly
-Blob is extremely weak early game and powerful late game
Therefore these are my suggested changes:
-Nuke has a chance at being allowed once the blob comes very close to victory
-Normal blob health reduced by 1/3rd, Blobling's health reduced by 1/4th
-Factory blobs produce bloblings 4x slower and can only support two maximum at once
-When a factory blob dies the bloblings it is supporting die as well
-The Blob Overmind's …
> New blob Part 1 of (until its fixed)

- code/game/turfs/space/space.dm
- code/modules/mining/mine_items.dm
- code/modules/research/research_shuttle.dm
- html/changelogs/Clusterfack_2826.yml
Fixes #2631, the nuke disk can no longer be taken off by either shuttle to the asteroid
Fixes #1675, people riding vehicles can no longer take the nukedisc off the zlevel with them
> Nukedisk fixes

- code/datums/supplypacks.dm
- code/game/gamemodes/game_mode.dm
- code/game/gamemodes/gameticker.dm
- code/game/gamemodes/wizard/raginmages.dm
- code/game/mecha/mech_fabricator.dm
- code/game/objects/structures/crates_lockers/closets/fireaxe.dm
- code/modules/mob/living/silicon/mommi/mommi.dm
- code/modules/mob/living/silicon/mommi/mommi_modules.dm
- code/modules/mob/living/silicon/robot/robot.dm
- code/modules/mob/living/silicon/robot/robot_modules.dm
- code/modules/reagents/Chemistry-Machinery.dm
- code/modules/research/designs.dm
- html/changelogs/Clusterfack_2874.yml
Fixes #2724, adds pill collector to medical crate. 
Fixes #2617, scrubs genetic defects from roundstart antagonists and newly spawned raging mages. 
Fixes #2817, upgrade modules are now under upgrade. 
Fixes #2807, stun arm should now spawn instead of toy sword.
Fixes #2059, fireaxe lockers started out locked as standard so mappers dont have to varedit. 
Fixes #2807 fully, makes stun arm not be missing, also makes emag items not appear twice in the list. 
Gives tablepass flag to the all in one grinder as well. 
Standardizes mommi to use emag_act as well.
Grinders have the tablepass flag
> Bunch of Fixes

- code/game/turfs/simulated/floor_types.dm
Plating's start with floor tiles. This returns them to the pool and set's their reference to null.
This is problematic for the reasons
-crowbaring up tiles from platings without tiles
-being unable to place wires on plating until you crowbar up the tile
> Hotfix for floor plating

- code/modules/media/broadcast/receiver.dm
- code/modules/media/broadcast/transmitter.dm
This reverts commit 4839176ecc0363dbb1d51d7237c1910786816b9c, which removed the sound systems on the station.
> Return Sound systems

- code/ATMOSPHERICS/atmospherics.dm
- code/ATMOSPHERICS/datum_pipeline.dm
- code/controllers/shuttle_controller.dm
- code/game/gamemodes/cult/hell_universe.dm
- code/game/gamemodes/cult/trash_machinery.dm
- code/game/gamemodes/endgame/supermatter_cascade/universe.dm
- code/game/gamemodes/events/power_failure.dm
- code/game/machinery/lightswitch.dm
- code/game/machinery/suit_storage_unit.dm
- code/modules/media/jukebox.dm
- code/modules/mob/mob.dm
- code/modules/power/singularity/narsie.dm
- html/changelogs/Clusterfack_3209.yml
Well I finally came back to this, a little wiser and much more experienced. And this time I can honestly say I think these changes should really FEEL different and like they made a large impact on the performance.
-Fixes narsie double consuming all atoms in range
-Commented out see_narsie until someone fixes it causing narsie double vision
-Instead of deleting pipelines, narsie will now set them to invisible
-Fixes #2587, powernet shutdown should work perfectly well now
-As above, fixes apcs recharging somewhat during different events like narsie, supermatter cascade,and powerfailure and then starting things back up
-Absolute pathed datum_pipeline.dm
-Disallowed shuttle controller deleting narsie/singulo on entry
-Added better lag logging for setting the universal state to hell_universe …
> Narsie Optimizations + Power Failure Fix

- code/datums/uplink_item.dm
- code/game/machinery/camera/camera.dm
- code/game/machinery/doors/airlock.dm
- code/game/machinery/machinery.dm
- code/game/machinery/mommi_spawner.dm
- code/modules/admin/verbs/randomverbs.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/living/carbon/brain/MMI.dm
- code/modules/mob/living/carbon/human/life.dm
- html/changelogs/Clusterfack_3332.yml
-Improves become_mommi button for observers, gives an option of all the areas in which mommi spawners that are ready to spawn are located
-Fixes a bug where mobs with a mind would not be transferred into a built mommi from a mommi spawner
-Fixes a few typos
-Removes the 'you have no lungs panic and tell a coder' message, since you can actually have no lungs now
> Mommi Spawn Improvements

- baystation12.dme
- code/ATMOSPHERICS/atmospherics.dm
- code/ATMOSPHERICS/components/binary_devices/binary_atmos_base.dm
- code/ATMOSPHERICS/components/binary_devices/circulator.dm
- code/ATMOSPHERICS/components/binary_devices/valve.dm
- code/ATMOSPHERICS/components/trinary_devices/t_valve.dm
- code/ATMOSPHERICS/components/trinary_devices/trinary_base.dm
- code/ATMOSPHERICS/components/unary/portables_connector.dm
- code/ATMOSPHERICS/components/unary/unary_base.dm
- code/ATMOSPHERICS/datum_pipe_network.dm
- code/ATMOSPHERICS/datum_pipeline.dm
- code/ATMOSPHERICS/pipes.dm
- code/__HELPERS/datumpool.dm
- code/__HELPERS/experimental.dm
- code/game/machinery/camera/camera.dm
- code/game/objects/items/devices/radio/radio.dm
Adds a datum pooling proc, shamelessly stolen from regular object pooling
Applies datum pooling to pipelines and pipenetwork for major performance improvements in their deletion.
These improvements should be especially noticeable in anything that deletes pipelines/networks once per tick, ie singulo narsie and supermatter, narsie will actually have no improvement because trying to solve this same issue I made him simply not delete pipes and set them to invisible instead
Removes the camera/radio wires qdel, just why
Before: http://puu.sh/gJVR4/a72a508961.png
After: http://puu.sh/gJSKv/96e79f9ea6.png
> Optimization

- code/__HELPERS/datumpool.dm
Runtime fix that should stop the following runtime:
runtime error: illegal use of list2args() or named parameters
proc name: getFromDPool (/proc/getFromDPool)
source file: datumpool.dm,39
Fix another issue where the GC would collect a datum before it makes it into the pool.
Fixes https://github.com/d3athrow/vgstation13/issues/3542
> Datumpool runtime fix

- code/ATMOSPHERICS/datum_pipe_network.dm
- code/ATMOSPHERICS/datum_pipeline.dm
- code/__HELPERS/datumpool.dm
- code/__HELPERS/experimental.dm
- code/game/objects/effects/decals/Cleanable/humans.dm
Another datum pooling initialization hotfix. Initial does not actually create lists causing type mismatches after being pooled.
See: http://www.byond.com/forum/?post=76850, reported to byond 5 years ago but never fixed
Causes the following runtimes:
runtime error: type mismatch:  += the digital switching valve (/obj/machinery/atmospherics/trinary/tvalve/digital/mirrored)
proc name: build network (/obj/machinery/atmospherics/trinary/build_network)
source file: trinary_base.dm,128
usr: null
src: the digital switching valve (/obj/machinery/atmospherics/trinary/tvalve/digital/mirrored)
call stack:
the digital switching valve (/obj/machinery/atmospherics/trinary/tvalve/digital/mirrored): build network()
the digital switching valve (/obj/machinery/atmospherics/trinary/tvalve/digital/mirrored): …
> Datum Initialization Hotfix

- code/ATMOSPHERICS/components/unary/thermal_plate.dm
- code/ATMOSPHERICS/datum_pipe_network.dm
Optimization to the radiation of thermal plates. 
Instead of each thermal plate calling radiate() every single tick, thermal plates in the same network (which equalizes all gases within every tick) will simply copy over the gases once the first radiate() is called. Then the networks radiate() value will then be reset. If the network is destroyed between ticks it wont matter, as then the thermal plates will instead all call radiate() as they would usually.
> Thermal Plate Optimization

- baystation12.dme
- code/ATMOSPHERICS/datum_pipe_network.dm
- code/ATMOSPHERICS/datum_pipeline.dm
- code/__HELPERS/datumpool.dm
- code/__HELPERS/global_lists.dm
- code/controllers/Processes/disease.dm
- code/controllers/Processes/event.dm
- code/controllers/Processes/machinery.dm
- code/controllers/Processes/mob.dm
- code/controllers/Processes/obj.dm
- code/controllers/Processes/pipenet.dm
- code/controllers/Processes/power_machinery.dm
- code/controllers/Processes/powernet.dm
- code/datums/mixed.dm
- code/game/gamemodes/meteor/meteor.dm
- code/game/objects/explosion.dm
- code/game/objects/items/stacks/cable.dm
- code/global.dm
- code/modules/power/apc.dm
- code/modules/power/cable.dm
- code/modules/power/power.dm
- code/modules/power/powernet.dm
- code/modules/power/singularity/emitter.dm
- code/modules/power/singularity/narsie.dm
- code/modules/power/singularity/singularity.dm
- code/modules/power/smes.dm
- code/modules/power/solar.dm
- code/modules/power/solars/control.dm
This sets to put right the 'optimization' someone made to powernets a long time ago so that they could handle large explosions. Unfortunately the "defer powernet rebuild" never actually rebuilt the powernets causing them to simply pretend powernets were connected when destroyed by explosions or singularities.
At some point this problem has been further exacerbated to the point where disconnecting powernets doesn't work in the first place. So this PR aims to take a hybrid of the pipenet method of datum networks.
1. Expand properly when adding something to the powernet (pipenets currently dont do this for shame)
2. When the powernet is destroyed by cutting or explosions or something, null the powernet out and store some data about it in the cables
3. When the powernet is used by a …
> Complete - (Not an actual) Powernet Optimization

- code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
- html/changelogs/Boxe-plasmaman_goliathhides.yml
you can upgrade plasmaman mining suits with goliath hides
takes 6 hides to reach 90 melee DR
normal mining rigs take 5 hides to reach that amount
Fixes #3716
> Plasmaman Mining Suits & Goliath Hides

- code/modules/power/singularity/emitter.dm
Addresses #3770 by making emitters turn BACK ON after the powernet they are connected to has power again, as opposed to shutting off permanently.
(This seems to have been the intended behavior originally from the code)
> Emitterfix

- code/game/machinery/atmoalter/portable_atmospherics.dm
- code/modules/hydroponics/hydro_tray.dm
When machinery/hydroponics became -> machinery/portable_atmospherics/hydroponics it didn't get the machine flags transferred over
> Fixes #3985

- code/game/gamemodes/blob/blob.dm
- code/game/gamemodes/blob/blob_report.dm
- code/game/gamemodes/blob/theblob.dm
They weren't properly being sent to the station communication consoles, both directive 7-10 and directive 7-12 which gives the station the nuke code during its final moments.
> Fixes blob intercepts

- code/modules/hydroponics/vines.dm
We were using a master controller object for vine spreading, where the start location of the vines was where the master controller object was spawned. However it's location was never set to null after that so it just stayed there. Also the sanity checks on the object not having any vines didn't work because it was a list which would still exist even with zero vines.
> Fixes #3177

- code/game/objects/items/weapons/tanks/jetpack.dm
- html/changelogs/clusterfack_3992.yml
Jetpacks wouldn't regard trace gases as gases, therefore any jetpack using trace gases like N2O would break when there's really no reason for it to disallow trace gases at all.
> Fixes #2702

- code/modules/power/smes.dm
Fixes #4095, why exactly was it just checking if there was ANY POWER and then draining MORE POWER THAN EXISTED in the powernet? Better question, how did it ever work properly like this in the past?
Fixes #4076, lastout wasn't being set to 0 when smes stopped outputting
Obviously SMES are delicate special snowflakes so make sure to look this over carefully
> Fix SMES issues

- code/game/machinery/computer/buildandrepair.dm
Fixes #3987, the only issue was it wasn't named properly. It was called disease splicer instead when it actually wasn't.
> Fix Isolation Centrifuge Board

- code/game/objects/items/weapons/storage/storage.dm
Fixes #3752, prevents the exploitation of menus not closing when bags are thrown to transfer items over distances. Also checks adjacent before placing items into bags in the first place, solving the issue for any further potential exploits.
> Bag Exploit Fix

- code/game/objects/items/devices/taperecorder.dm
Fixes #3896, the issue with the tape recorder was that it was using visible message, which sends the message to all seeing mobs but not hearing ones. Fixed that and prettied up some of the duplicated code in the file.
> Fix taperecorder

- code/_onclick/hud/monkey.dm
Fix #3916, monkeys can now swap their hands using their hud switch hands button. It was previously unclickable because it was a button of the wrong type.
> Fixes monkey hand swapping

- code/game/objects/items/devices/mat_synth.dm
Fixes #3508, the issue was pretty clearly a result of the fact it uess typepaths the way it does. Since only [src] would give a name instead of a typepath, the [material_type] was displaying the actual typepath instead of the name.
> Makes mat synth display name instead of type

- code/modules/food/customizables.dm
Fixes #3509, it was accidentaly set to wine instead of ale. Bet someone copypasted this.
> Fixes ale in still

- code/WorkInProgress/pomf/spacepods/spacepods.dm
Fixes #3517, apparently the stat() for spacepod cells checked that the battery has an object of type cell within it. But since spacepods typecast their cell for specific initialization of a high power cell, the istype(S.battery) check fails if you placed a different type of cell into it. Causing it to instead display no cell detected.
> Fixes spacepod cell stat() bug

- code/modules/power/smes.dm
- code/modules/power/terminal.dm
An issue as yet unreported on github, SMES can be crowbar destroyed before their terminal is destroyed leaving an immortal terminal. Also adds a way to deconstruct terminals that have been left behind by a machine without getting destroyed for the purposes of sanity.
> Fix a terminal issue

- code/modules/mob/living/simple_animal/friendly/mouse.dm
Addresses #4071, the real name of mice wasn't being set and therefore when talking in deadchat they were simply being called 'mouse'
> Gives dead mice different names

- code/modules/power/power.dm
Fixes #4119, while connect_to_network was just checking to see if a powermachine was on a turf, get_cable_node was also doubly making sure it was on a simulated floor. Making it impossible to allow power machines to work while on catwalk.
Fun fact, this MAY fix solar trackers. Because while solars are currently placed on a regular simulated turfs, solar trackers were built upon catwalks. After dylan made catwalks into a nonturf they were no longer connecting to any powernets and doing literally nothing anymore.
> Power Machines can connect to powernets on all turfs

- code/__HELPERS/datumpool.dm
- code/__HELPERS/experimental.dm
Debugmin wins
Fixes #3251
Fixes #3898
Probe helped me figure out this one because I saw the wires teleporting around after a singularity ripped him a new one. It had to be a double pooling issue, and since I couldn't replicate it normally I started testing around the singularity specifically. 
I added
>ASSERT(!(AM in masterPool["[AM.type]"]))
to experimental.dm line#87, which confirmed my suspicions when I loosed a singulo.
Turns out someone added extra sanity to singularity act to make sure it destroys objects, however both ex_act(1) and qdel(src) use returntopool, thus double pooling.  I'm sure this is the cause of anytime someone has objects mysteriously disappear on them (if they are the type that are pooled).
> Fixes extremely mysterious and incomprehensible pooling bug

- code/datums/supplypacks.dm
Resolves #3880, security barriers is now security checkpoint equipment crate, it also holds a mr valid in addition to the deployable barriers.
> Adds Mr Valid to barrier crate

- code/modules/mob/mob_movement.dm
Fixes #3771 
Process_spacemove intentionally makes you slip even when doing checks to see if you can move, so added an argument to ignore slipping, and removed some colons from the code.
> Fix click dragging

- code/_onclick/observer.dm
- code/modules/mob/mob_movement.dm
Fixes #4151, ghosts were managing to get to nullspace by click teleporting to the edge of the map. This resolves that issue by making it so click teleporting calls entered just like any other and all other forms of movement.
> Fixes ghosts getting to nullspace

- code/modules/admin/admin_verbs.dm
Removes debug messages
Uses ckey(ckey), I was looking at comparative database queries and other logging styles, and it seems you need to put a ckey variable into ckey() for it to be usable
> Probably fix readminself

- code/game/machinery/computer/crew.dm
- code/game/machinery/computer/medical.dm
- code/game/machinery/doppler_array.dm
- code/game/objects/items/devices/PDA/PDA.dm
- code/game/objects/items/devices/PDA/cart.dm
- code/game/objects/items/weapons/teleportation.dm
- code/global.dm
- code/modules/research/xenoarchaeology/tools/tools.dm
- code/modules/research/xenoarchaeology/tools/tools_depthscanner.dm
- code/modules/telesci/gps.dm
- code/modules/telesci/telesci_computer.dm
- code/world.dm
Resolves #4319.
Adds a zlevel drift for all zlevels at roundstart. Hopefully it doesn't go list index out of bounds or something. Also stopped a method for determining zlevel drift using only the teleport computer and inputting 6 values to bisect the possible offsets until you find the specific one.
> Adds Local Zlevel Drift

- code/modules/mob/mob_movement.dm
The old system would go from have x1 move delay to like x5 on a ticklag that is only half of the original. Which is pretty shit and forces you to disable tick compensation if you want to be able to move at a reasonable speed on low ticklags.
This just makes move delay inversely proportional to ticklag directly. Which ideally would preserve the move delay at any ticklag.
Fixes #4289
> Change ticklag compensation

- code/game/mecha/mecha.dm
Fixes #4464. It required a much simpler list than I thought of the objects mecha hold in their contents, thank god some old coder knew to hold mecha things under a subset of item called mecha_parts.
> Fixes Mecha Item Dropping

- code/game/machinery/atmoalter/canister.dm
- code/modules/admin/admin.dm
Shamelessly rips off the APC's sweet ass method of dealing with overlay updates in update_icon and applies them to canisters, helping with the odd occasion where canister's starting chewing through cpu cycles.
> Uses APC's update_icon for canisters

- code/ATMOSPHERICS/components/unary/thermal_plate.dm
- code/ATMOSPHERICS/he_pipes.dm
Fixes #2864
Fixes #4078
They would radiate and make ultra cold gas under 10 moles, 10 moles is about 10kpa at 20C, which is simply way too high.
They now will radiate at less than .01 total moles only, less than the standard moles for a standard airless tile. And to similarly limit unnecessary gas exchange procs being called pointlessly, will only intermix with at least 1 mole in the atmosphere.
> Fixes h/e pipes and thermal plates

- code/game/objects/effects/effect_system.dm
- code/game/objects/structures/vehicles/wizmobile.dm
Because soft deletes are all fine and well but 8000 of them is just too much when there are only ever 10 or so instances of the object at a time.
> Pool Ion Trails

- code/modules/mob/login.dm
This fixes spellmasters being lost upon reenter corpse and any other login due to it being deleted in reset_screen() instead of preserved
> Fix spellmaster loss

- code/_onclick/hud/screen_objects.dm
- code/_onclick/hud/spell_screen_objects.dm
- code/modules/mob/login.dm
- code/modules/mob/mob.dm
- html/changelogs/Clusterfack_4820.yml
Fixes #4605
Fixes #4628
I found out why these were being improperly pooled, thanks to skowron for producing a case to reproduce and view the variables of. On login or when reset_screen() was called for a mob that had an inventory open the inventory obj/screen's were being pooled and being reused elsewhere on other objects.
Hilarity ensues!
Updates the spellmaster fix to bring it in line with the new system to prevent improperly pooled screen objects.
> Fixes inventory bugs

- code/modules/mob/living/carbon/alien/special/alien_embryo.dm
Fixes #4588, xeno larva will now never get permanently trapped inside the contents of an object if their impregnated mob is inside a sleeper, dna machine, adv scanner, other alien, et cetera et cetera.
> Fix xeno larva from getting stuck in anything ever

- code/controllers/Processes/lighting.dm
Better fix #4880 and turn the lights back on, 
!L.destroyed check was nested in a L.destroyed check
> Turn the lights back on

- code/modules/lighting/light_source.dm
Might be an issue where you actually want to have a lighting overlay but dont. PJB should look it all over when he gets back.
runtime error: Cannot execute null.update lumcount().
proc name: remove lum (/datum/light_source/proc/remove_lum)
source file: light_source.dm,189
usr: null
src: /datum/light_source (/datum/light_source)
call stack:
/datum/light_source (/datum/light_source): remove lum()
lighting (/datum/controller/process/lighting): doWork()
lighting (/datum/controller/process/lighting): process()
/datum/controller/processSched... (/datum/controller/processScheduler): runProcess(lighting (/datum/controller/process/lighting))
> Runtime fix for lighting

- code/__HELPERS/experimental.dm
- code/__HELPERS/game.dm
Initial costs about 1e-5 to 1e-6, whereas an operation that just sets a variable in an associative list using another variable in an associative list has a negligible cost even at extremely high calls. Therefore all the variables are initialized only once in a single associative type list holding all the vars.
Currently it checks all atom/movables within view which is can be up to 225 lighting overlays in view, and checks each of these atom/movables recursively and then uses the list OR operator to add them in due to possible overlap. Instead recursively checks turfs only once and adds them to the found list due to eliminating the possibility of overlap.
> Optimizations

- code/game/turfs/space/space.dm
Mommis and shit cant escape the derelict anymore. 
Recursive type check only takes single typepaths, search contents for accepts and returns lists.
> The Great Escape

- code/game/verbs/suicide.dm
- code/modules/mob/living/carbon/brain/MMI.dm
- code/modules/mob/living/carbon/brain/death.dm
- code/modules/mob/living/carbon/brain/posibrain.dm
Fixes #4949
Posibrains have their sprite reset back to the original and have a death message now. Neat.
> Fix posibrain death

- code/game/objects/items.dm
- code/modules/mob/living/silicon/mommi/inventory.dm
- code/modules/mob/living/silicon/mommi/life.dm
Fixes #4812
Mommi low power mode has been broken since its inception.
It now properly makes you unequip everything, and disallows equipping items while in the low power mode.
> Fix mommi low power mode

- code/game/supplyshuttle.dm
- html/changelogs/Clusterfack_5047.yml
Fixes #5031
-Regular plastic flaps were not originally meant to be airtight, they can now be made airtight with a crowbar and anchored/unanchored with a wrench.
-They now use canpass instead of EDITING THE TURF AIR BELOW IT to set airtight qualities.
-They now have examine text and a different name/desc to show if they are anchored/airtight or not
-Wrench anchors/unanchors as it does with most equipment
> Fixes plastic flaps

- code/_onclick/hud/mommi.dm
- code/_onclick/hud/robot.dm
- code/modules/mob/living/silicon/mommi/mommi.dm
- code/modules/mob/living/silicon/robot/robot.dm
Patches up another obj/screen leak, this time with robot hud storage. Obj/screen pooling breaks when pooling objects aren't refreshed by a new hud in mob/login(), due to the fact all objects currently on the client.screen are pooled so they can be refreshed at login()
Robot module huds were not replaced properly by this thanks to someone *cough* ririchiyo *cough* putting them in new() instead of where all other hud elements are kept.
> Robot hud element

- code/game/machinery/constructable_frame.dm
- code/game/machinery/machinery.dm
- code/game/machinery/telecomms/machine_interactions.dm
- code/game/objects/structures/displaycase.dm
- code/modules/hydroponics/biogenerator.dm
- code/modules/paperwork/photocopier.dm
- code/modules/power/pacman2.dm
Fixes #4942
Makes setting a build state use a proc which automatically updates the icon of the machine frame so nobody accidentally sets build state without updating the look of the machine frame.
Improves some of the machine frame's attackby code, including - and this is beautiful, a system by which it spawns every object required to build when a circuit board is attached, reads the name, then deletes it immediately.
> Improves Machine Frame

- code/ATMOSPHERICS/components/unary/vent_pump.dm
- code/ATMOSPHERICS/components/unary/vent_scrubber.dm
- code/game/atoms.dm
- code/game/atoms_movable.dm
- code/game/machinery/alarm.dm
- code/game/machinery/camera/camera.dm
- code/game/machinery/door_control.dm
- code/game/machinery/doors/door.dm
- code/game/machinery/lightswitch.dm
- code/game/objects/items/blueprints.dm
- code/game/objects/items/mommiprints.dm
- code/game/turfs/turf.dm
- code/modules/power/apc.dm
Addresses #2914, adds renaming for several more machinery types that take their name from the area. 
Unfortunately does not work properly as it should be readding the vents/scrubbers to the new area as well as renaming all the machinery properly from space. If someone could let me know how I fucked up the procs I added to create area that they would not readd vents/scrubbers or rename that would be great because I've been banging my head against it for a few hours.
> Adds more blueprint functionality

- code/modules/mob/delays.dm
- code/modules/mob/mob_movement.dm
Fixes #4528 
"Arbitrarily high numbers" need to actually be high if you don't want to break my future shit nexis
Literally does nothing but raise an arbitrary cap to move delays imposed by nexis, because low ticklags require high delays.
> Fixes mob delayers at extremely low ticklags

- code/__HELPERS/datumpool.dm
- code/__HELPERS/experimental.dm
Makes material datums not lag by not calling del() when a datum pool is overrun, instead just cutting the oldest one loose from the pool. This can be fixed if/when qdel() for datums is EVER FIXED.
Made the pull from earlier called 'optimizations' work properly, this method is almost identical except it works fully and is just as efficient.
-Instead of looping through the exclusion lists every time, it only loops through the variables. 
-Instead of calling initial every time, it merely copies a value from an associative list.
> Fixed Optimization

- code/__HELPERS/unsorted.dm
- code/game/objects/items/devices/PDA/apps.dm
- code/game/turfs/turf.dm
- code/game/turfs/turf_flick_animations.dm
- code/modules/mob/death.dm
- code/modules/mob/living/carbon/alien/death.dm
- code/modules/mob/living/carbon/brain/death.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/human/death.dm
- code/modules/mob/living/carbon/monkey/death.dm
- code/modules/mob/living/silicon/death.dm
- code/modules/mob/living/silicon/mommi/death.dm
- code/modules/mob/living/silicon/robot/death.dm
- code/modules/mob/mob_movement.dm
- code/modules/mob/transform_procs.dm
Makes mobs gibbed or dusted not force del and also makes the atom/movable/overlays they use for their death animation not force del.
Also removes the call() from client/move because WHY THE FUCK was it there.
> Various small optimizations

- code/game/machinery/doors/door.dm
- code/game/objects/structures/tables_racks.dm
- code/game/turfs/turf_flick_animations.dm
- code/modules/mob/living/simple_animal/hostile/bat.dm
- code/modules/mob/living/simple_animal/hostile/creature.dm
- code/modules/mob/living/simple_animal/hostile/faithless.dm
1. Found the major leak of atom/movable/overlay deletions, it was being caused by door/cultify
2. Found the last major source of regular deletions, it was being caused by table/New() deleting any prior tables when cultify intentionally spawned tables on top of the tables
3. Commented out horde because it barely works, it adds little since everything is already dead by this point, and it uses over 100% of the cpu of any server to run even normally.
Related: http://www.byond.com/forum/?post=1288063
> Fix lag during Hell Universe

- code/ATMOSPHERICS/pipes.dm
Destroy was using disconnect to null the reference to them but not nulling their own reference causing pipes to not GC properly
:panic:
> Make pipes GC

- code/__HELPERS/game.dm
- code/game/atoms_movable.dm
- code/game/machinery/bots/buttbot.dm
- code/game/objects/items/weapons/implants/implant.dm
- code/game/say.dm
- code/modules/mob/hearing/virtualhearer.dm
- code/modules/mob/login.dm
- code/modules/mob/logout.dm
- vgstation13.dme
Every hearer in the game is now attached what I call a virtualhearer. These are mobs that are set at the hearers location. The virtualhearers have max invisibility, alpha at 0, name = "", so by all rights they are full undetectable to a normal player. They have an attached var to the hearer they represent, and when that normal hearer is destroyed it will find its attached hearer and pluck it back into pooling.
These virtualhearers will all update their location when either hearers_in_view, (regular say), or get_mobs_in_radio_ranges, (radio code) is called. Updating each loc has a relatively small cost, on my slower private server about 6e-6. They will update only every .5s at most to prevent spam calls.
The advantage to these virtualhearers is that get_hear is no longer a requirement. …
> Experimental Saycode Optimization

- code/modules/research/xenoarchaeology/finds/finds.dm
The reference to the inner object wasn't nulled before being before the strangerock was being deleted, therefore it was getting deleted too.
Fixes #5402
> Fix strangerocks

- code/ZAS/Airflow.dm
- code/game/data_huds.dm
- code/modules/mob/hearing/virtualhearer.dm
- code/modules/spells/spell_code.dm
- code/modules/spells/targeted/ethereal_jaunt.dm
Details:
Jaunt with a low enough cooldown would allow you to double cast jaunt making it flip the fuck out, so instead your spells are now silenced during jaunt. Your click and attack delayers as a jaunter are now delayed until the end of the jaunting session.
Airflow now checks for flags & invulnerable, which is the flag that is meant to prevent effects from occurring to that atom. This should fix an issue I've been seeing since hellish ZAS was recently turned on from virtualhearers and jaunters being blown into things.
Also fixed another reported bug that huds would report on invisible people, they lacked the see_invisible check that mechs had.
> Jaunt fix + airflow fix

- code/_onclick/hud/ai.dm
- code/modules/mob/living/silicon/ai/login.dm
- code/modules/mob/living/silicon/mommi/mommi.dm
- code/modules/mob/living/silicon/robot/robot.dm
- code/modules/mob/logout.dm
- code/modules/mob/mob.dm
- code/modules/projectiles/targeting.dm
Alright let's see
- Added a thing to remove screen obj references to logout in addition to being called in destroy instead of relying fully on the reset screen obj proc.
- Moved some hud creation from AI to the hud datums where it should have been, might fix an issue or two
- My teeth still hurt from the dentist so there's that
- Adds robot module backgrounds to one of the screen objs that should be removed on logout as well so all screen objs should always be accounted for going in/out
Man you have to be reeeally careful with pooling about this kind of shit.
> Probably stops huds breaking

- code/modules/mob/living/simple_animal/borer.dm
Borers have new objects which prevent them from ventcrawling, this adds them to the canenterventwith exception list
> Fix borer ventcrawling

- code/modules/research/xenoarchaeology/artifact/artifact_communication.dm
Fixes my xenoarch artifact that broke thanks to a change to wrenchanchor which doesn't call power_change unless a machine has the fixed2work flag.
> Fix artifact

- code/game/dna/dna2_domutcheck.dm
- code/game/dna/genes/gene.dm
- code/game/gamemodes/setupgame.dm
- code/modules/mob/living/carbon/human/life/handle_mutations_and_radiation.dm
- code/modules/mob/living/carbon/human/update_icons.dm
- code/modules/mob/living/carbon/species.dm
- code/modules/reagents/Chemistry-Reagents.dm
Imagine: loop through ALL possible genes, only to loop through ALL active genes to see if we have them for each one. So thats already a possible genes * active genes loop for each mob.
Instead we loop through active genes only and grab the gene through an associative list. So loop of 54 * x is now a loop of x maximum.
Now dna_genes is an associative list if that isn't clear.
1. Removes the is_active proc entirely 
2. Speeds the FUCK out of handle_mutations_and_radiation by **extremely** lowering looping
> Speeds up some human loops

- code/ATMOSPHERICS/atmospherics.dm
- code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
- code/modules/supermatter/supermatter.dm
- html/changelogs/Clusterfack_5762.yml
- You can now put supermatter crates onto tiles where supermatters exist
- This allows you to put a supermatter back into a crate and close it, AS LONG AS THE SUPERMATTER HAS NOT TAKEN DAMAGE
- Also fixes a GC issue with ventcrawling
> Neat things

- code/_onclick/hud/spell_screen_objects.dm
Spell screen objects weren't being removed from client screen after being pooled
> Probably fix boo icon

- code/modules/mob/dead/observer/observer.dm
Observers are now dextrous, we already have checks for ghost sanity so there's no concern here.
Fixes #5971
> Observer Dexterity

- code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
Yeah so the arguments for the base child proc were different so that caused it to functionally always return true (thanks to the parent proc).
Fixes #6211
> Fix SM Crate

- code/game/machinery/transformer.dm
- code/modules/mob/living/silicon/mommi/mommi.dm
- code/modules/mob/living/silicon/robot/robot.dm
- code/unused/hivebot/hivebot.dm
The procs return before irreparably breaking everything because they are handling a null input as though it were a real option
> Fixes #6453

- code/game/machinery/doors/firedoor.dm
Only areas connected to a firedoor by a floor will be recongized as an area in which the firedoor exists.
i.e. A firedoor connected to a wall of another area will not trigger that firedoor
> Fixes #4027

- code/game/objects/items/weapons/cards_ids.dm
- code/game/objects/items/weapons/switchtool.dm
- code/modules/research/designs/medical.dm
- html/changelogs/ShiggyPiggy_medical.yml
The surgeon's switchtool now can be constructed at R&D with proper tech
levels and the CMO has maintenance access. (Revised and resubmitted to remove commit
madness)
> Some medical tweaks

- code/modules/reagents/Chemistry-Reagents.dm
- html/changelogs/ShiggyPiggy_4.yml
Not really a bug, but it's the only reagent whatsoever that has a double name.
The description's the same, so it wouldn't be a problem for anyone not familiar with the name.
> [Autism] Anti-toxin (Dylovene) renamed to Dylovene

- code/ZAS/Fire.dm
Pomf cannot into configs so we will change the actual code to prevent ignition at lower than the plasma visible setting
> Fixes #6667

- code/modules/html_interface/map/map_shared.js
You can no longer break the UI for the crew monitor causing it to disappear by improperly changing zlevel
> Fix #5563, Fix #5477

- code/_onclick/cyborg.dm
Fixes #5967
Robots can once again alt click on turfs and it will bring up the alt click menu. It was previously broken for turfs but worked for objects. It now works for both.
> I JUST MASH ON THE KEYBOARD AND IT WERKS

- code/modules/projectiles/gun.dm
Guns now check user.loc, if user.loc is not a turf they will not fire. So you shouldn't be able to fire while inside a locker or recharger station or what have you.
> Fixes #4129

- code/modules/medical/computer/cloning.dm
Needs more testing at the moment which I don't know how to pull off myself.
The more stringent check of find_dead_player wasn't occurring because a previous change tried to growclone BEFORE the find_dead_player, thus if something passed the growclone checks it would get cloned even if there was no dead player associated with the ckey.
> Could fix #6641

- code/defines/obj/weapon.dm
- code/game/gamemodes/nuclear/nuclearbomb.dm
- code/game/gamemodes/nuclear/pinpointer.dm
- code/modules/admin/player_panel.dm
Nuclear disk no longer wallows in the GC, it GC's properly now when a pinpointer is pointed towards it. Also, it can respawn on destroy() as well as del() so that it doesn't NEED TO be deleted to respawn.
Did some other things:
- Nuclear disk now uses the object process scheduler instead of its own hacked together system of spawn() call itself (which in theory could create multiple threads doing the same thing if you spammed it)
- It is now more obvious that the pinpointer can tell you if the nuke is ticking or not, a functionality it always had but nobody knew about
> Fixes #6768

- code/datums/supplypacks.dm
Removes an extra "/" that prevented the crate from being orderable.
> Waifu crate hotfix

- code/_onclick/hud/_defines.dm
- code/_onclick/hud/movable_screen_objects.dm
- code/_onclick/hud/spell_screen_objects.dm
Movable screen elements are now also locked to a corner so that they can change position with view size changes, it can be forced to hook to a wall with encode screen and the original value can be re-obtained using decode
http://puu.sh/lE3a0/11fc50d3a4.webm
> Relativity for Movable Screen Elements

- code/game/objects/structures/docking_port.dm
- code/modules/lighting/lighting_overlay.dm
Lighting overlays no longer just HAPPEN TO STAY THERE FOREVER when theyve been pooled up to poolings max item limit.
Docking ports are no longer just pulled and eaten by singularities, because yes that was a thing.
> Fixes Singlo Shit

- code/modules/admin/verbs/adminpm.dm
Fucking special tab.
Forces special tab to be selected and opened when a non-admin with the special tab setting on receives an adminpm.
> Special Tab

- code/controllers/garbage.dm
- code/game/gamemodes/changeling/changeling_powers.dm
- code/modules/admin/admin_verbs.dm
- code/modules/admin/verbs/mapping.dm
- code/modules/html_interface/map/adv_sec/adv_camera.dm
- code/modules/nano/nanomapgen.dm
- maps/_map.dm
Deals with the 6 or so verbs that show up when you aren't an admin
1. Both nano map generators have been moved to mapping (debug verbs) tab so that they aren't seen by everyone needlessly.
3. The hard del() checking proc was fixed (it did NOTHING for months), improved, and moved to debug verbs as well
4. The check mob list is now hidden, can still be accessed by typing the verb with . infront of it in case it is necessary
5. The debug verb for cameras, view datum, is commented out because it's debug code for testing a specific thing
6. Set base turf given to admins instead of being a verb for everyone because why wouldn't it be
7. Fixes a bug where admin verbs of mod level weren't being removed even when de-adminned.
> Removes the Debug and Server tab for non-admins

- code/game/turfs/turf.dm
- code/game/turfs/turf_flick_animations.dm
Recodes it in such a way that the spawn shouldn't break if the turf undergoes a changeturf during the animation.
> Fixes #5746

- code/datums/shuttle.dm
- code/game/turfs/space/space.dm
- code/game/turfs/space/transit.dm
- code/game/turfs/turf.dm
By adding another argument to changeturf to specially allow changeturf to be called on hyperspace transit turfs, we prevent anything but shuttles changing the turf of these hyperspace transit turfs. Fixing the issue by preventing this kind of thing from being changed.
> Fixes #6950

- code/modules/assembly/proximity.dm
- code/modules/mob/dead/observer/observer.dm
Nothing that I can see that uses PROXMOVE flag necessitates observers to have this flag, and in fact, most of the things using it had to make an exception for observers as a result.
> Observers lose PROXMOVE flag

- code/modules/mob/living/silicon/mommi/life.dm
- code/modules/mob/living/silicon/robot/life.dm
For robots makes the state of being 'unconscious' only applicable to lacking a cell, which puts you in a state of being almost totally nonfunctional similar to the 'unconscious' (critical) state of humans.
Low power mode does disable some functionality such as module use, but does nothing to your vision and overall movement. This fixes #7215, whereby it was assuming a low power mode borg was in crit and thus ejected it.
> Low charge =/= unconscious

- code/game/objects/items/stacks/rods.dm
Makes assembling a grille show the progress bar in the correct location
> Rods do_after change

- code/__HELPERS/game.dm
- code/game/machinery/machinery.dm
- Fixes #7265, the topic() check uses in_range which now uses Adjacent instead of a distance check
- In_range internally does a TK check (which seemed to be the original intention of the proc from the comments)
> Modifies in_range

- code/modules/reagents/reagent_containers/food/snacks.dm
When the object gets qdel()-ed, the reagents reference is nulled immediately. Therefore anything that was spawned to occur just after the reagents refrence gets nulled runtimes.
However if we let ourselves hold a manual reference to the reagents contained in the object, we will have a real reference and reagents wont be qdel()-ed until we are finished using it here.
> Fix Snacks Runtime

- code/game/objects/items/devices/chameleonproj.dm
Fixes #7321
You can now scan boxes and shit
Fixes #7305
The proc that disrupts the projection is now spawned so that the projector will fall into the dummy before the dummy gets emptied out and deleted
> Chammy Projector

- code/ZAS/Airflow.dm
Fixes #7125, airflow uses setweakened instead of modifying weakened manually so people drop instantly instead of the next life tick.
> Fixes airflow stuns

- code/modules/mob/living/carbon/brain/posibrain.dm
- code/modules/mob/mob.dm
Ghostize(0) is a form that doesn't let you reenter your corpse as a ghost
Fix #7234, posibrains wont permanently force ghost you when the mob dies
> Fix reentering destroyed mobs

- code/modules/reagents/reagent_containers/food/snacks.dm
It's fucking back, so I've fixed it in a similar way to the way I fixed the other runtimes
runtime error: Cannot read null.total_volume
proc name: On Consume (/obj/item/weapon/reagent_containers/food/snacks/proc/On_Consume)
source file: snacks.dm,35
usr: Sharon Luvire (/mob/living/carbon/human)
src: Warm Donk-pocket (/obj/item/weapon/reagent_containers/food/snacks/donkpocket)
call stack:
Warm Donk-pocket (/obj/item/weapon/reagent_containers/food/snacks/donkpocket): On Consume(Sharon Luvire (/mob/living/carbon/human))
Warm Donk-pocket (/obj/item/weapon/reagent_containers/food/snacks/donkpocket): attack(Sharon Luvire (/mob/living/carbon/human), Sharon Luvire (/mob/living/carbon/human), null, 0)
> Snacks runtime

- code/modules/reagents/Chemistry-Reagents.dm
This is distinct from removing alcohol's toxicity. Alcohol poisons you in 4 stages each with varying effects of slurring speech up to damaging your liver and you with toxins. However deadrum/absinthe (which covers almost all alcohols) will begin toxing you above 30u, the reagents_overdose point, whereas normal alcohol shouldn't be damaging you until 450u.
This PR instead removes >30u toxins damage, and to compensate lowers the pass_out (normal toxins damage level) to 350u for variants of deadrum/absinthe instead while increasing the tox damage at that level.
Closes #7129
Fixes #7115
Arthur wasn't making my suggested changes quickly enough/at all
> Removes alcohol overdose

- code/modules/mob/living/carbon/human/life/handle_chemicals_in_body.dm
- code/modules/reagents/Chemistry-Holder.dm
- code/modules/reagents/Chemistry-Reagents.dm
Fix #7482 I expect
fixes #7479
Since these reaction procs were spawned off reagents clear was being called BEFORE the reagents were reacting. 
This sets waitfor = 0 for these procs so that they will automatically spawn off instead of delaying the reaction if sleep() is used in them, but still let's them react before clear_reagents is called.
> Reagent stuff

- code/modules/mob/living/silicon/mommi/inventory.dm
- code/modules/mob/living/silicon/silicon.dm
Using named args for procs without defining them for all versions of the proc runs into problems because byond doesn't see them as defined for those children procs or some shit I can't explain it.
> Fix drop item runtimes

- code/modules/mob/mob_helpers.dm
- code/modules/projectiles/projectile/special.dm
Fixes #7468
This changes the shake camera function to use client.pixel x/y instead of manually modifying the client eye. The reason it never used this before is simply that client.pixel x/y didn't exist until recently, but this should give functionally identical code.
Someone should still probably check it out and check that it is the same before/after though.
> Changes shake_camera

- code/controllers/master_controller.dm
- code/game/turfs/turf.dm
- code/modules/awaymissions/zlevel.dm
- code/modules/lighting/lighting_system.dm
- code/modules/mining/mine_turfs.dm
- code/world.dm
Moves turfs list creation to initialize
Moves some mine turfs work to initialize
Fixes bugs from last try:
Initializes turfs before the process scheduler begins so it will probably set up it's processes
> Faster Startup take 2

- code/modules/supermatter/supermatter.dm
You can already close the crate on the supermatter, you can also already move the supermatter onto the crate's tile and close the crate on the supermatter.
The only problem I can think of is that the crate collides with the supermatter when moved onto the supermatter's tile, now it wont and you can move it onto the supermatter's tile.
> Fix #7873 I guess

- code/game/machinery/mommi_spawner.dm
I don't know precisely the full plans that N3X15 had for derelict mommis to be more Russian-ized, but they were incomplete and we have no way of knowing if they will ever be completed at this point. 
Therefore, unless N3X15 comes back to finish whatever rework he had planned I am changing the type of mommi spawned on the derelict back to the standard type (with namepicking)
Fixes #6848
> Regular mommis on derelict again

- code/modules/mob/living/silicon/robot/robot.dm
- code/modules/mob/mob.dm
- code/modules/mob/mob_movement.dm
While attack self is called by some of the standard hotkeys, a few of the macros manually call this proc instead. Instead of changing every macro (and potentially letting new macros break it as well), this is a better place to place the attack delayer.
Fixes #8069
> Moves attack self delayer to centralized proc

- code/modules/mob/mob.dm
- code/setup.dm
Huh, didn't realize that the combo of lying that != 1 and that using a bitflag with it that sets it to a value other than 1 would trigger this.
> Fixes #8094

- code/modules/supermatter/supermatter.dm
- html/changelogs/CptWad.yml
Other notes
1. Toxins test site moved back per request
2. New toys scattered around the map, collect them all!
3. Thing in space was scrapped _for now_
4. Fixes #2287 #3420 #7745 #7853 #8124 #8174 and #8178
5. Monkey room was remade, check below
5. Supermatter now does not broadcast shit off z-level, thanks @PJB3005 
6. put in all of @NigglyWiggly 's pets, besides the spider. Thanks dylan
7. Moved atmos's lightswitch somewhere it can be reached
8. Increased the size of virology, added a newscaster.
9. Another pill collector and some antibody scanners
> [box] Expanded maint and goonecode containment. Some bugfixes too

- code/defines/obj.dm
- code/modules/mob/mob_movement.dm
Instead of mobs checking timestopped in client/move(), being timestopped sets your move delayer until the time when the timestop will end.
Also removes the mob check because seriously if a client doesn't have a mob it gets removed from the game and if that is still runtiming then its a serious byond bug.
> Another move optimization

- code/modules/mob/mob.dm
If you can no longer stand, it stands to reason that you should be lying, since lying is the state in which you are not standing, and thusly if you are lying you are not moving, since that is how the game works.
Fixes #8671
Fixes #6029
Fixes #7021
> Updating Canmove

- code/modules/reagents/Chemistry-Reagents.dm
Fixes #8684
The dangers of spawning shit off are illuminated.
Spawn (6 seconds) -> spawn cyber horror at the mobs loc
Mob tick called ~3 times within that time frame
1 cyber horror spawned on the mobs loc, gib called
~2 more cyber horrors spawned on the mobs loc later for the already gibbed mob with gib() being called again each time
> Prevents Cyber Horror Nullspace spam

- code/modules/mob/living/carbon/human/life.dm
- code/modules/mob/living/carbon/species.dm
Fixes #8712
I'm not sure who decided separating a global species holder from the real species datum each person holds would be a good idea, when fucking everything that uses species references the local species variable.
> Fix for genetics whatever

- code/game/machinery/vending.dm
Typecasting a variable as an /obj didn't allow it to access the associative list index where a typepath was the index. This is literally the first I've ever heard of this, it's almost worthy of a bug report.
> Byond fucked up

- code/game/gamemodes/endgame/supermatter_cascade/blob.dm
- code/game/objects/items.dm
- code/game/objects/objs.dm
It no longer bluespacifies when growing
A supermatter trying to eat them no longer does anything fixes #9714
Singularities also check invulnerability before pulling/eating objects
> Fix supermatter tiles

- code/__HELPERS/unsorted.dm
- code/modules/html_interface/voting/voting.dm
Fixes #9755 
Fixes #9469
by not putting any nulls into the voting list, puts in debug information to find out how this occurred in the first place
> Debug Voting

- code/__HELPERS/datumpool.dm
- code/modules/admin/admin_verbs.dm
I think pooling is a thing that has very few bugs due to the way I've simplified it to the extreme and thus this debug verb in an ideal world shouldn't be needed.
But we don't live in an ideal world as you can clearly see
http://www.byond.com/forum/?post=2080853
This lets you view all the stored variables for a pooled variable type (assuming it has already been pooled at least once)
> Adds debug verb for pooling

- code/game/gamemodes/blob/blobs/core.dm
Blob points are now changed to be distributed based on the time since the last life() tick instead of having a set amount per life() tick. This stops lag from lowering the number of points received from blob life() of cores, though lag will still affect things like pulse() which affect both resource/factory nodes. 
Incidentally this will about double the base generation rate of points for a single blob core, which seems needed both for beginning blobs as well as extra overminds that often barely get any points at all.
> Makes blob point collection lag immune

- code/_hooks/events.dm
- code/_onclick/click.dm
- code/modules/spells/spell_code.dm
If you had multiple spells that could be channeled you could freak the system out by some convoluted combination of using each one.
While it was previously thought to be sane, not intercepting attacks after spells were cast were causing some insane behaviors, (such as picking up food after using matter eater on it), so now a spell being cast successfully will intercept attacks.
> Fixes 2 spell channeling bugs

- code/__HELPERS/lists.dm
- code/setup.dm
Using isnum is unreliable for detecting nonstandard formats of already associative lists. Causing them to be overriden with the type cache.
Checking isnull instead will allow us to detect strings, numbers, lists, typepaths, basically everything that we want to check to make sure this isn't already an associative list.
Fixes #10225
Fixes #10224
> Repair is type in list

- code/modules/mob/mob.dm
show_message was using a message limit cap which was being flouted by bicon which encodes image data into a long string, a string so long that it would overflow that max message limit size and the rest of the message would be cut off by the internal sanity of show_message.
I don't even feel satisfied, this was a stupid bug.
Fixes #10002
Fixes #10171
> Something I wasted 3 days on

- code/modules/html_interface/map/adv_sec/adv_camera.dm
- code/modules/html_interface/map/crew/crew.dm
- code/modules/html_interface/map/interactive_map.dm
There was an issue due to the fact the mapname I was using was a directory name, which browse_rsc() ignores all for the last portion of, and the js was trying to read the full name with the directory.
This makes it just use the nameShort of the map which has no directory which to be truncated.
@Exxion this fixes the problem you reported in my last pr
> Fix html not loading currently

- code/game/atoms_movable.dm
Crossed() is now only called on turfs within forcemove
Fixes the stacking bug I think, would have been caused by the one that lets you drag tiles over other tiles. Probably combined with the inventory rework which probably made it use forcemove.
> Fixes a few bugs

- code/game/objects/items/devices/paicard.dm
I fixed this literally in a dream, woke up, applied the fix, and didn't even remember what bug I fixed originally until I looked at it.
This fixes the eamine bug where if you examine a pai you would get a sheet of icon states, apparently in byond when you add a string icon state to an overlay it stores the entire dmi in the icon. I don't know why this happens, and I don't know how I fixed it while asleep.
> Fixes pai examine

- code/modules/mob/mob.dm
I never realized this had it's own proc even though it was right next to it, this is why AIs couldn't see a lot of mob behavior like being attacked and stuff.
> Fix up visible message for mobs

- code/game/gamemodes/blob/blob.dm
- code/game/gamemodes/meteor/meteors.dm
- code/modules/events/event_dynamic.dm
- code/modules/events/meteors.dm
- code/setup.dm
Sets blobs to a standard proportion of how many players need to be ingame per blob spawned. 
Lowered that quantity from 30 people required to blob to 20 per blob, applied that same proportion to the event dynamic (which previously did not check the number of people per blob spawned).
> Limits blob cores by population

- code/WorkInProgress/pomf/spacepods/equipment.dm
Spacepods would fire two shots from both sides facing the direction you are firing, however the second projectile would wait for the first projectile to finish before firing. So the second projectile would fire from the original location a second later, thus if you had moved forward in the second it took for the first projectile to finish firing the second projectile would collide with your spacepod and damage you.
> Fix spacepod weapons

- code/WorkInProgress/pomf/spacepods/spacepods.dm
Lets you mousedrop out of spacepods onto any tile adjacent to the spacepod
> Spacepod mousedrop

- code/modules/mob/living/living.dm
Resting now delays your next move by 1 second
Resting now checks if your movement is delayed before allow you to rest
Effects:
1. Resting is still instant
2. Resting does not let you move just after getting up
3. Resting does not let you get up/drop down just after having used the rest verb
> Changes rest somewhat

- code/_hooks/events.dm
- code/modules/mob/mob.dm
- code/modules/mob/mob_movement.dm
- code/modules/spells/targeted/ethereal_jaunt.dm
1. Adds invocation to jaunt and group jaunt
2. Creates an adminbus group jaunt spell, gives everyone jaunting for double the time of regular jaunt with a double cooldown as well in a 3 tile range
3. Group jaunting makes an image so all jaunters can see each other
4. Group jaunt adminbus only and maybe will be placed on a secret map or away mission or vault some day so it requires no robes
> Makes a group jaunt spell

- code/game/atoms_movable.dm
- code/modules/mob/hearing/virtualhearer.dm
- code/modules/mob/logout.dm
- code/modules/mob/mob.dm
This should nail down one or two of the three possible reasons why virtualhearers could be losing their attached.
> Virtualhearer debug code

- code/game/atoms_movable.dm
- code/modules/mob/login.dm
- code/modules/mob/logout.dm
- code/modules/mob/mob.dm
Moved virtualhearer removal from destroy() to del(), but to be honest I'm not sure why this would resolve any problems since we SHOULD be using qdel() for everything, and nothing is going be garbage collected while a virtualhearer is holding a reference to them anyway.
There may have been an issue with HEAR_ALWAYS since I cant find anywhere where HEAR_ALWAYS mobs were getting a virtualhearer removed, which would only affect AI eye and poly.
> May help virtualhearers somewhat

- code/game/gamemodes/vampire/vampire.dm
- code/game/gamemodes/wizard/rightandwrong.dm
- code/game/gamemodes/wizard/spellbook.dm
- code/game/machinery/wishgranter.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/hearing/virtualhearer.dm
- code/modules/mob/living/carbon/alien/humanoid/life.dm
- code/modules/mob/living/carbon/alien/larva/life.dm
- code/modules/mob/living/carbon/brain/death.dm
- code/modules/mob/living/carbon/brain/life.dm
- code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
- code/modules/mob/living/carbon/monkey/life.dm
- code/modules/mob/living/silicon/ai/death.dm
- code/modules/mob/living/silicon/ai/freelook/eye.dm
- code/modules/mob/living/silicon/ai/life.dm
- code/modules/mob/living/silicon/mommi/death.dm
- code/modules/mob/living/silicon/pai/death.dm
- code/modules/mob/living/silicon/pai/pai.dm
- code/modules/mob/living/silicon/robot/death.dm
- code/modules/mob/living/silicon/robot/life.dm
- code/modules/mob/living/simple_animal/constructs.dm
- code/modules/mob/login.dm
- code/modules/mob/new_player/login.dm
- maps/RandomZLevels/wildwest.dm
Adds a wrapper proc for changing sight flags
When sight flags are changed, it checks if the sight flags have actually been changed and then if so modifies the virtualhearer's sight flags.
> Fixes virtualhearers sight flags

- code/ZAS/Airflow.dm
Inertia was causing objects to overshoot their airflow destination. By checking if things can spacemove, we will know if they are already undergoing inertial movement and therefore we can stop them from being airflow pushed further.
Works pretty well from my testing.
> Fixes zas pushing things back and forth in space

- code/modules/mob/spells.dm
So all the spells were being added properly to the new mob just as intended. But as a quirk of add_spell() code, only spells that were added when there was no spell master were getting their holder var set to the new mob they were added to.
Fixes #11537
> Fix mindswap the rest of the way

- code/modules/mob/mob.dm
Now that virtualhearers inherit sight flags we need to fix the visible message system which uses viewers(get_turf(src)), since anything with SEE_TURFS sees any turf, any and all visible messages are visible when you have SEE_TURFS.
Now the visible message will depend on the turf level atom, either the turf or the mob or the object or the object holding the object or the mob holding the object or the object holding the mob, et cetera.
Fixes #11642
> Improves visible message behavior

- code/game/area/areas.dm
- code/game/sound.dm
- code/modules/admin/verbs/playsound.dm
- code/setup.dm
Dear shouldn't hear any sound coming directly from play sound, which should be the wrapper proc for most every sound.
Put defines on the ambience channel and the admin played music channel.
Deaf people can no longer hear any regular sound, but they'll still be able to hear ambience, admin music, and jukeboxes.
Fixes #11632
Fixes #11631
> Changes the way deaf hear sounds

- code/game/say.dm
Forcemove accidentally destroyed my hyper fast saycode system. ALSO, while I was at it - changed the sethearing to the final ultimate get_turf code, and reduces the resethearers cooldown, which was previously set to half a second only because we didn't know how fast it would be.
> Remodifies sethearing

- code/modules/spells/targeted/targeted.dm
Yeah I passed the list of things in range to is valid target, but forgot to include an exception for regular spell channeling for targetted spells which doesn't pass a list of options.
> Fix wait for click for targetted spells

- code/__HELPERS/lists.dm
So yeah it could runtime if trying to read type from a typepath
> Fix istype in list runtime

- code/datums/supplypacks.dm
- html/changelogs/Isaac.yml
Changes the spec-ops bundle to contain no parapen and no box of incendiary grenades, replaces it with silenced pistol and ammo for said pistol.
Adds a new bundle, Russian weapons crate, which costs 150 credits and gives you three random items, which can be a mosin nagant, ammo for this mosin nagant, empty ammo for the gun and laser aks.
@isaac cant into github so he asked me to PR it
> Adds one and changes one Emagged cargo console supply packs ala @isaac in discord

- code/game/jobs/job/civilian_chaplain.dm
Adds new shit for chaplain deity choice
1. Firstly, re-instated the old bible/booze object from eons ago. Now when selecting certain (less than morally binding) religions you start with the old bible filled with booze and money.
2. Updated and fixed a few old religions.. IE: Norse now has more ways to trigger getting it (typing vikings at start will get you norse gods) and has a wider array of gods that it will choose.
3. Added three new religions. Roman, Clown and Mime.
4. Added items that will now spawn with certain religions (syndicate religion now gets the full fake space suit and malf religion gets full cardborg) so on and so forth.
> Chaplain religion update

- code/modules/RCD/schematics/tile.dm
Since you cant change the painting type while you are currently painting easily, and they're simply no balance reason that 'painting' would ever need a delay.
> Removes tile painter paint delay

- code/game/jobs/job/captain.dm
- code/game/jobs/job/security.dm
- html/changelogs/Wamp.yml
Can't have no shit birds leading our glorious NanoTrasen stations, nosirree.
I was considering restricting all heads of staff from nonhumans. But only restricting implanted heads seems like an okay compromise.
> Disallow nonhumans from taking HOP HOS Captain.

- code/game/machinery/computer/ai_core.dm
- html/changelogs/Wamples.yml
Can card traitor AIs, law 0 does not show there. Bit odd for an antag check to exist for that reason.
> Permit carding malf AIs before code delta.

- code/world.dm
Stops uncloseable HTML UIs from persistenting between rounds
> Closes HTML UIs on reboot

- code/game/gamemodes/steal_items.dm
- code/game/jobs/job/science.dm
- html/changelogs/cptwad.yml
1. adds four new items to steal, all of which hard to find or get. This includes: The Telebaton, the planning frame, the CE's fancy belt and a TTV.
2. Tweaks which jobs can or cant get certain steal objectives. Captain can no longer wander into a head of staffs office to snag a jumpsuit and vox traders don't get the steal a jetpack objective, etc. The changes are easy to read off the code if you want to know specifics but its mostly against the captain and jobs that have direct access to the item(s).
3. Roboticists no longer have toxins access
> Traitor steal objective tweaks

- code/modules/organs/blood.dm
Fixes #12068
The monkey blood change was easily circumvented by feeding the buggers dexplus, which was easily acquired by the type of people that did this "exploit", scientists and medical. The change broke virology and unbreaking it while leaving the monkey oxyloss in would either entail giving all carbons a blood vessel (even carbons that do not use blood) or making monkey a child of human (spooky), both of which make code more complex for insufficient gain.
And 'infinite' blood has no practical use anyway so there you go. No need to break virology over a nonissue.
> Lets dead monkeys donate.

- code/modules/clothing/accessories/storage.dm
This allows you to decontruct the webbings for research in a Destructive Analyzer and allows mechanics to scan and reproduce
:cl:
* tweak: Webbings can now be deconstructed with a research value of materials 2
* tweak: Mechanics can now scan and reproduce webbings
> Makes webbings have a tech value of materials 2

- code/game/gamemodes/cult/ritual.dm
- code/game/gamemodes/cult/runes.dm
Another buff to hopefully get people to use the runes more, along with keeping Free Cultist in line with Summon Cultist.
:cl:
* tweak: "Free Cultist and Teleport Other runes now require 2 invokers instead of 3."
> Makes Free Cultist and Teleport Other require 2 invokers instead of 3.

- code/game/machinery/suit_storage_unit.dm
- code/game/objects/structures/watercloset.dm
- code/modules/clothing/spacesuits/miscellaneous.dm
fixes #14914
fixes #14911
fixes #14913
fixes #14910
fixes #14908
fixes #14907
fixes #14899
fixes #14886
fixes #14883
fixes #14878
fixes #14885
fixes #14881
fixes #14870
fixes #14912
fixes #14884
fixes #14874
New SOFTsuits for prisoners on gulag. Currently use orange syndie suit sprites since I have no sprite talent and someone who does and wants to make one can easily change it.
:cl:
- bugfix: Various bugfixes on Bagelstation
- rscadd: Added new Prisoner Space suits that have terrible protection and are orange.
- rscadd: Gave puddles a description since they were lacking such before.
- experimental: Vox traders now have no ion pistols and secvendor but now have a pimped out medbay good for experimenting on catbeasts
> Bagelstation fixes

- code/game/turfs/simulated/floor.dm
Fixes #15781
Removes the light floor overlay when someone clicks to turn a light floor off, and adds a check when crowbarring to do the same if it's removed. Lemme know if this is fucked or whatever.
:cl:
* bugfix: Light floors now properly turn off and can be removed without leaving a sprite behind.
> Light floors now turn off properly, removes overlay when crowbarred

- html/changelogs/Duny.yml
>1800 open issues, can't even sort by label reliably
smh tbh fam
Decided to take a look at the issues I can actually fix, starting with deff. Making a PR for just this one to begin with because I'm not convinced trying to cram a pod bay in deff is worth the trouble in the first place. I mean, who cares right? Mechanics should just be a subtype of engineer as god intended anyway, upgrading and maintaining things, not playing around in space. :^)
Here's my best attempt:
It's just enough to the left to not get squished by the trader shuttle and to get a two tile hallway, and not too much to preserve the strip club.
I don't know shit about pods so if I forgot anything tell me. I don't think there is any other good place for a pod bay on deff. It's close to the mechanics, near space (and I'm …
> Adding a pod bay to Defficiency.

- html/changelogs/TempDunMeta.yml
Closes https://github.com/vgstation-coders/vgstation13/issues/13620
Here's a free PR to apply (or decide not to) the proposed change to Meta's medbay by @9600bauds in the issue above, change on which I have no personal opinion; feel free to read the issue for the reasoning behind it. (tl;dr: moving the fridge this way will reduce crowding in the small entry hallway a lot, plus the paramedics are better placed as a result)
Before:
After:
I'm a big boy who knows how to swap areas around without fucking up, but I have been known to forget a pipe here and there so here's the piping:
Tested briefly, all the APCs charge properly and nothing appears to be out of place.
I can move things around a bit if needed, just ask.
Also fixes the fucked up icon state of the light fixtures on the entire map …
> Meta's medbay switcheroo: no longer just a switcheroo edition [ready for review/merge/whatever]

- code/game/machinery/embedded_controller/airlock_controllers.dm
- code/game/objects/items/mountable_frames/airlock_controller_frame.dm
- html/changelogs/Duny.yml
- nano/templates/pressure_regulator.tmpl
Fixed cargo shuttle buttons opening the wrong door.
Fixes https://github.com/vgstation-coders/vgstation13/issues/15430
Fixed Ian spawning as christmas Ian. It's fucking september.
Fixes https://github.com/vgstation-coders/vgstation13/issues/15099
The salvage shuttle's inner airlocks now start unbolted.
Resolves https://github.com/vgstation-coders/vgstation13/issues/15059
Now for starting to fix https://github.com/vgstation-coders/vgstation13/issues/14675 and https://github.com/vgstation-coders/vgstation13/issues/14354:
- Added the pressure regulator, an embedded controller used only to depressurize or pressurize a room on demand using vents and an airlock sensor (Has only 3 buttons: Pressurize, Depressurize and Abort; can't be linked to airlocks). Can be built using an airlock controller …
> Small fixes for Deff and addition of the pressure regulator to fix mass drivers.

- html/changelogs/DunyTemp.yml
Fixes https://github.com/vgstation-coders/vgstation13/issues/14967
Fixes https://github.com/vgstation-coders/vgstation13/issues/14388
Fixes https://github.com/vgstation-coders/vgstation13/issues/15916
An IAA player filed a detailed complaint to me about why they are buttblasted at the sight of Metaclub's IAA office and courtroom, so I went ahead and reworked it with it in mind and I come to you with this:
Before:
After:
I have never in my life played IAA/Lawyer (well, randomed it once, but I killed myself in the bar) so give me all that juicy feedback.
I forgot a pipe (screenshot taken after adding it) and a fire alarm which I will add in a future commit. I also noticed the extra intercomm.
> Meta's IAA Office and Courtroom rework plus small fixes (Ready for merge)

- maps/defficiency/jobs.dm
New medbay only has room for one geneticist, also adding a third medical doctor spawning area to be in line with the available slots.
Fixes https://github.com/vgstation-coders/vgstation13/issues/15954
> Limits geneticists to one slot and adds a missing Medical Doctor spawning area on Deff.

- code/game/machinery/vending.dm
Because cracking a Code One :tm: with the boys shouldnt cost you 50 credits, cant have the good greyshits go broke buying beer cans.
Changed all normal beer cans to 15, didnt touch greyshit vodka at all.
🆑 
* rscadd: Reduced prices on the Off World Off License vendor, enjoy lower prices for lower quality beer.
> Reduced Off-World Off-License vendor prices

- code/game/machinery/vending.dm
Lets face it, 20 credits for a can of cheap space cola is just silly, 10 credits per can of cancer is big enough that IED making wont skyrocket and more sensible than 20 anyways, promissed to make this change after beer change got merged, so here we are.
🆑 
* tweak: Reduced prices on soda machines
> Reduces Robust Softdrink Prices

- __DEFINES/planes+layers.dm
- code/_onclick/hud/parallax.dm
- code/game/turfs/space/space.dm
- code/game/turfs/space/transit.dm
This kind of shit is why I stopped working with byond at all. Apparently for SOME FUCKING REASON having a fucking plane master with mouse opacity fucks up the plane when you take turf appearances. I have NO FUCKING IDEA why this would possibly occur but it does.
Also fixes space not being clickable thanks to celt
> Fuck byond

- code/datums/supplypacks.dm
That little thing kept bugging me everytime I saw glock crates, which I assume whoever changed glocks from .45 to .380 must have forgotten about.
:cl: 
* tweak: Renamed the .45 glock gun & ammo crates to .380 instead.
> Changed the glock pack and ammo crates names to .380 instead of .45

- code/modules/reagents/Chemistry-Reagents.dm
Asked by Yred.
The metabolism used to be 0.5, and like everyone else, nobody uses it as an actual debuffing chem, so it's getting a buff to 0.2 metabolism.
:cl: 
* tweak: Cryptobiolin metabolism has been reduced to 0.2
> Slowed down the metabolism for Cryptobiolin to 0.2

- code/game/gamemodes/cult/runes.dm
Instead of making the person who activates the rune, take all the damage.
Fixes #18008
:cl: 
* bugfix: Free Cultist splits damage between invokers like Summon Cultist instead of focusing damage on one.
> Spread Free Cultist damage between invokers.

- code/game/machinery/computer/law.dm
Previously it only played when admins hit the send-laws button specifically. Didn't play when admins hit add-laws, either.
:cl: 
* bugfix: Law update sound plays when silicons receive a law modification, as it should.
> Make law update sound play properly.

- code/game/gamemodes/cult/runes.dm
Bit more debatable than the previous patch. Free Cultist now deals a sum of 20 brute, Summon Cultist deals a sum of 30 brute. Previously, Free did 10 damage to each and Summon did 15 to each, minimum 2 invokers.
2 invokers: Free 10 damage to each; Summon 15 to each.
3: 6.6 // 10
4: 5 // 7.5
And so on.
The other alternative to the current system that I see, is to make only the activator and one other random person next to the rune the invokers that take the damage. The current state where it damages everyone standing next to the rune for no particular reason, is sort of goofy.
:cl: 
* tweak: Free and Summon Cultist spreads a flat amount of damage between invokers instead of dealing 10/15 damage to each.
> Make Free and Summon Cultist rune damage flatter.

- code/game/gamemodes/cult/ritual.dm
It was a decent experiment. But in practice, it's just another fiddly thing to deal with in a mode that has enough fiddly things going for it. You can deal with it by stockpiling fat stacks of food or making 10+ 50u iron pills roundstart or pocketing a stack of metal and a mortar and a soda can, sure. But you have to wonder if that sort of addition makes cult more interesting for cultists or noncultists. I don't think it does.
And while cult 3 will re-add the blood cost, it will also remove one fiddly thing (word research) and it will add some ways to steal blood from victims, so I'm willing to give cult 3's blood costs a shot when it's implemented.
:cl: 
* rscdel: Removes cult rune blood costs.
> Revert "Blood runes now actually cost blood" (7957319..adca572)

- code/modules/hydroponics/seeds.dm
Fixes #7915
Destroying angels DID GET amanatin when amanatin was implemented (https://github.com/vgstation-coders/vgstation13/commit/8841386f75ff4#diff-1d0bb0a151770f8688f9922b70cd2e14R871), but it was removed in https://github.com/vgstation-coders/vgstation13/commit/512b106f0f098d#diff-1d0bb0a151770f8688f9922b70cd2e14L871
Given the circumstances, I think that was unintended.
:cl: 
* bugfix: Re-adds amanatin to destroying angels and reduces potency.
> Re-adds amanatin to destroying angels, reduces potency.

- code/game/gamemodes/cult/runes.dm
The final "QOL" for Summon that I can think of: Appending (Present) if the invoker can see the choice or (Dead) if the choice is dead, to the list of cultists produced when Summon Cultist is invoked with a buddy cultist.
Minor information leak compared to solo invoke Summon Cultist, in that solo only tells you that X person is deconverted, braindead or actually dead by their omission from the list of active cultists. I'm willing to compromise on that if necessary and remove the (Dead) notice, but I think the (Present) bit is important due to how obnoxious it is to use the damn rune when there's a lot of buddies milling about in your base.
:cl:
* tweak: Double-invoked Summon Cultist rune now tells you whether each choice is dead or near you.
> Make Summon Cultist display visibility or dead status when actually summoning.

- code/game/gamemodes/cult/cult.dm
- code/game/gamemodes/cult/runes.dm
- code/game/gamemodes/cult/talisman.dm
Addresses #18093 (partially)
Comms talismans can be used 5 times now. While I'm still not sure that it's sufficient to address some of the bits I raised (particularly the early game for new dudes, and telling them what all to avoid), it's at least something.
:cl:
* rscadd: Comms talismans can now be used 5 times.
> Comm talisman buff

- code/modules/hydroponics/seed_machines.dm
Microlasers reduce seed/genome degradation, manips speed up the machines. Speed upgrade is a bit wonky due to time ticks; is the round() for action_time required?
:cl:
* rscadd: Makes upgraded parts influence xenobotany machines' efficiency.
> Add effects for xenobotany machine upgrades.

- code/modules/reagents/Chemistry-Reagents.dm
For an unknown reason, Adminordrazine can set Radiation to 0, but not rad_tick, which is the real issue. This PR will drop rad_tick to 0 to be consistent.
> Adminordrazine will now set rad_tick to 0

- code/modules/telesci/gps.dm
- nano/templates/gps.tmpl
Instead of e.g. the coords for your held GPS being buried under 20+ GPS printed for vaulthunting.
:cl:
* tweak: The GPS you are looking at will always display its coords at the top of the coords list.
> Make GPS coord listing always display the activated GPS first.

- __DEFINES/reagents.dm
- code/modules/reagents/Chemistry-Reagents.dm
- code/modules/reagents/Chemistry-Recipes.dm
We're not quite at the point of botanist self-sufficiency, but this is close enough to unstable mut right?
Anyway, botany chems and chem reactions received little to no love after the plant chem rework deal, so here's something I read about from goonstation and implemented lazily. Feel free to suggest other more creative chems I guess.
:cl:
* rscadd: Adds untable mutagen, produceable with phenol formic radium. It uns tables.
> Adds untable mutagen.

- code/_onclick/click.dm
- interface/interface.dm
Right-clicking to point at things is pretty bad, especially if that thing is moving. I tested the only other distance-altclicks I'm aware of (silicons turning vpumps et al without mucking about with the menu, and AI doorshocks) and this didn't interfere with that; let me know if there's other distance altclicks to test I guess.
edit: welp, mmb used instead of alt-click
:cl:
* rscadd: shift+mmb-click on things at a distance to point at them.
> Shift-MMB on things at a distance makes you point at them.

- code/modules/clothing/glasses/scanners.dm
No goggles:
New goggles:
Current goggles:
It makes my eyes tired to look at that much green for an extended period. Also, I've heard that newcop NVGs saw a considerable drop in use since the green change. Not like I can guarantee whether that's true or no, but I guess it's worth asking how often ops use them now as a measure of the effect.
:cl:
* tweak: Make NVG overlay less green.
> Make night-vision goggle overlay less green.

- code/game/machinery/doors/mineral.dm
Closes #18313. Resin doors have 1.5 hardness; 5 30-burn lasers or 3 60-damage combat shotgun slugs to destroy. I considered adding bullet_act to all mineral doors, but that can be changed later if someone wants it.
:cl:
* tweak: Xeno doors can now be destroyed with lasers and bullets.
> Make resin doors take damage from lasers and bullets.

- code/modules/projectiles/projectile/bullets.dm
Closes #18435.
With the previous version of buckshot, clicking at 2 tiles away would have a huegely wide and shitty spread compared to clicking at the edge of the screen (and you could get even tighter groupings if you had something to increase your vision radius). This fixes that.
Point blank through 3 tiles, ~1 tile possible
4 tiles, ~3 tiles possible
7 tiles, ~4-5 tiles possible.
:cl:
* tweak: Make buckshot spread independent of the distance you click at.
> Make buckshot spread independent of the distance you click at.

- code/__HELPERS/unsorted.dm
- code/game/gamemodes/gameticker.dm
Fixes #4864
The pAI bit was untested due to difficulty but I'd imagine it works the same. Also, this does not list silicons that are gibbed or whatever; seems you use ticker shit for that, so maybe I'll list gibbed silicons after antag datums are merged or something.
:cl:
* tweak: Silicon ckeys are displayed even if the silicon ghosts.
> Show silicon ckeys at roundend even if they ghost.

- code/datums/ai_laws.dm
Fixes #9432 by taking the easy way out. The traitor AI/borg law is displayed in red, which I don't see much of an issue with. What's slightly more iffy is that it also displays onehuman, emag-law-0, and whatever else happens to occupy that slot in red as well.
That could be avoided by checking for malfitude at line 86, but that involves ticker shit or whatever.
> Make malf law not state html to chat, make all law zeroes appear red.

- code/modules/telesci/gps.dm
still need to look at why someone dying causes the unendin Half Life spam but them getting stripped makes all the sounds happen simultaneously
:cl:
* bugfix: Makes SPS sound off the proper numbers, and makes them play concurrently instead of consecutively
> SPS announces now use the (proper) number wavs.

- code/modules/projectiles/projectile.dm
- code/modules/projectiles/projectile/bullets.dm
Fixes #18554
Only buckshot, whips, and shrapnel currently use launch_at, and whips didn't have any observable bugs after testing with the fix in place. One interesting thing I did notice that may or may not be a bug, is that both before and after the fix bullwhips get no point-blank bonus.
:cl:
* bugfix: You can now shoot at resting mobs and point-blank mobs with buck shot properlike.
> Buckshot can now hit lying mobs, and gets the proper point-blank damage bonus

- code/game/objects/items/devices/PDA/cart.dm
I assume this is a leftover from the days where Chemistry was part of Science. Toxin's job hasn't had to do with chemicals for a very long time.
:cl:
* tweak: Removed reagent scanner from Toxins PDA cartridge.
> Removes reagent scanner from Toxins PDA cartridge

- code/modules/mob/mob.dm
It'd be fun to point at your ID when someone asks you why you're in their office.
Also, the Show Held Item verb is very useful but annoying to use, and this adds an easier way to do that.
:cl:
* rscadd: You can now point (shift+middle mouse button) at your equipped items.
* rscadd: Trying to point at an item in your hands will instead use the Show Held Item verb.
> Can point at equipped items, pointing at an item in your hands uses Show Held Item instead

- code/modules/reagents/machinery/reagentgrinder.dm
This is so a botanist can grind 12 chili, but not 8 pizzas.
:cl:
* tweak: Updated reagent grinder item limit to use item sizes instead of flat amount.
> Updates reagent grinder item limit to use item sizes instead of flat amount

- code/modules/mob/mob.dm
This was weird when pointing at wall-mounted items.
> Pointing arrow spawns on top of the pointed item rather than the center of the tile

- code/modules/reagents/machinery/chem_master.dm
No matter what you enter in the dialog, nothing happens anyways, so all it does is annoy you.
To make this possible while preserving current functionality I also added a "Create empty bottles" button.
Also, you can select pill icon while beakers are not loaded, so you can recolor already created pills easier.
> Prevent chemmaster dialog if buffer is empty

- code/game/machinery/kitchen/smartfridge.dm
Items added to a fridge now start on the second shelf to make it a little easier to organize, literally no change if you don't care about this kind of thing
:cl:
* tweak: Items added to a fridge now start on the second shelf
> Chemistry is no longer top shelf

- code/datums/supplypacks.dm
For these reasons:
A) Screw having to sort out the ablative vests from a crate that's used to get guns. The current blob "meta" on the crew's side is to amass eguns as fast as possible, not sift through vests.
B) There's already another crate that can get you Ablative Vests, so if a cargonian really wants to rebel, then he's going to pay for it instead of getting it for "free".
C) The primary members of the Cargo metaclub have allowed this.
**EDIT:** The crate cost has been reduced to 30$, down from 50$.
:cl:
*tweak: NT has decided to cut costs on ablative vests and has removed them from their Experimental Energy Gear crates.
> Removes the ablative vests from the Experimental Energy Gear crate

- code/game/dna/dna_modifier.dm
- code/game/machinery/OpTable.dm
- code/game/machinery/Sleeper.dm
- code/game/machinery/adv_med.dm
- code/game/machinery/cryo.dm
See changelog
Small problem: Rollerbeds count as dense when locked so sometimes it seems like it doesn't work
because technically the rollerbed blocks you
:cl:
* rscadd: Rollerbeds now auto-unbuckle patients when trying to put them inside Medbay machinery via clickdrag (meaning you don't have to unbuckle them anymore before loading them).
* rscadd: Rollerbeds now auto-buckle patients when ejecting them from Medbay machinery via clickdrag (meaning the patient comes out already buckled).
> Makes rollerbeds not shit

- code/modules/mob/living/carbon/human/life/handle_mutations_and_radiation.dm
- code/modules/reagents/Chemistry-Reagents.dm
You know, for species that are supposed to be immune to the effects of what they're supposed to be immune to, they still get fucked because of what they had before switching.
:cl:
*Tweak: Turning into a ghoul or slimeperson now sets clone damage to 0.
> Turning into a ghoul or slimepeople sets cloneloss to 0.

- code/modules/reagents/reagent_containers/pill.dm
Interestingly this variable seems to only apply to attacking mobs, so you can't spam attack messages by attacking windows with pills or anything like that
:cl:
* tweak: Pill pilling now causes no attack delay.
> Pills cause no attack delay

- code/ATMOSPHERICS/components/binary_devices/binary_atmos_base.dm
- code/ATMOSPHERICS/components/binary_devices/valve.dm
Fixes #19069
:cl:
* bugfix: Nanotrasen has stopped outsourcing Atmospherics maintenance to mice.
> Stops mice from altclicking atmos pipes

- __DEFINES/planes+layers.dm
- code/WorkInProgress/Cael_Aislinn/Rust/fuel_compressor.dm
- code/WorkInProgress/Mini/ATM.dm
- code/game/machinery/kitchen/juicer.dm
- code/game/machinery/kitchen/microwave.dm
- code/game/machinery/kitchen/monkeyrecycler.dm
- code/game/machinery/kitchen/smartfridge.dm
- code/game/machinery/machinery.dm
- code/game/machinery/vending.dm
- code/modules/food/cooking_machines.dm
- code/modules/reagents/machinery/reagentgrinder.dm
It turns out a lot of machines were already doing this anyways so what can go wronger?
Fixes #19064
:cl:
* experimental: Items are now always layered on top of machinery by default. Please report any issues this might cause!
> Machinery is always layered under items by default

- code/modules/research/xenoarchaeology/tools/bunsen_burner.dm
This is only noticeable with bunsen burners that had a custom pixel offset which was not possible ingame so no changelog
> Bunsen burner overlay fix

- code/modules/research/xenoarchaeology/tools/bunsen_burner.dm
So if you drag them off you can drag them on
:cl:
* tweak: You can now drag bunsen burners back onto a table, just like a microwave or grinder
> Gives bunsen burners PASSTABLE

- __DEFINES/subsystem.dm
- code/ATMOSPHERICS/atmospherics.dm
- code/WorkInProgress/Cael_Aislinn/scp_173.dm
- code/controllers/subsystem/machinery.dm
- code/game/atoms_movable.dm
- code/game/machinery/bots/cleanbot.dm
- code/game/machinery/bots/draculabot.dm
- code/game/machinery/bots/ed209bot.dm
- code/game/machinery/bots/floorbot.dm
- code/game/machinery/bots/mulebot.dm
- code/game/machinery/bots/secbot.dm
- code/game/machinery/doors/door.dm
- code/game/mecha/mecha.dm
- code/game/objects/items/weapons/lance.dm
- code/game/objects/structures/inflatable.dm
- code/game/objects/structures/vehicles/wheelchair.dm
- code/game/objects/structures/window.dm
- code/modules/components/ai/controllers/movement.dm
- code/modules/events/immovablerod.dm
- code/modules/media/machinery.dm
- code/modules/mob/living/silicon/ai/freelook/eye.dm
- code/modules/mob/living/simple_animal/bees/bees_mob.dm
- code/modules/mob/living/simple_animal/friendly/cat.dm
- code/modules/mob/living/simple_animal/hostile/hostile.dm
- code/modules/mob/living/simple_animal/hostile/retaliate/cluwne.dm
- code/modules/mob/living/simple_animal/parrot.dm
- code/modules/power/cable.dm
- code/modules/power/singularity/singularity.dm
- code/modules/reagents/reagent_containers/food/snacks/meat.dm
- goon/code/obj/machinery/bot/chefbot.dm
Fixes #17053
Fixes #17493
Tested some simple mobs, most if not all of their behavior should work with this but there still exists the possibility of some minor floatiness if they use weird internal logic
Also, what's the deal with throwing up? You don't throw up, you throw down!
:cl:
* rscadd: Added smooth movement for simple mobs, bots, singulo, mechs, ventcrawling, and motor wheelchairs. Ride a mech without throwing up! Stare like an idiot at Beepsky's smooth slowwalking! Shit your pants at the Singularity's ominous, deliberate floating!
> Smooth movement for simple mobs, bots, ventcrawling, singulo, mechs, and motor wheelchairs

- code/modules/events/immovablerod.dm
- code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
- code/modules/projectiles/guns/projectile/constructable/railgun.dm
- code/modules/projectiles/projectile.dm
- code/modules/projectiles/projectile/bullets.dm
- code/modules/projectiles/projectile/special.dm
- code/modules/spells/targeted/projectile/fireball.dm
- code/modules/spells/targeted/projectile/magic_missile.dm
- code/modules/spells/targeted/projectile/pie_throw.dm
- code/modules/spells/targeted/projectile/projectile.dm
There were four fucking variables to do this. FOUR.
I went and manually set them all to be the exact same as before or as close as possible (only difference will be the hèêëcate and the lawgiver rapid fire which will be very slightly slower since they previously teleported 2 tiles at a time)
> Standardizes projectile speed

- code/modules/reagents/machinery/chem_master.dm
Bluespace beakers are often brought to Medbay but unfortunately, their usefulness is limited by the fact that they require machinery upgrades to be used efficiently at a chemmaster.
I think it's overkill that you need both machinery upgrades AND beaker upgrades (both together being harder to get than any other regular machine upgrade) just to click slightly less, especially since it still doesn't allow you to do anything you couldn't do before. Machinery upgrades are still highly desirable for the bigger pills and bottles.
:cl:
* tweak: Chemmasters now start with increased buffer size.
> Chemmasters start with increased buffer size

- code/modules/clothing/clothing.dm
- code/modules/clothing/glasses/glasses.dm
- code/modules/mob/living/carbon/alien/humanoid/life.dm
- code/modules/mob/living/carbon/alien/larva/life.dm
- code/modules/mob/living/carbon/brain/life.dm
- code/modules/mob/living/carbon/complex/life.dm
- code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
- code/modules/mob/living/carbon/monkey/life.dm
- code/modules/mob/living/silicon/robot/life.dm
- code/modules/mob/mob.dm
We have to update the entire HUD because HUD code is not yet at the point where we can update ONLY the things glasses change, but I set an autoclicker to click every 1ms equipping and unequipping a pair of medHUDs as fast as possible and the profiler said it was still 1/3 as resource-intensive as Poly picking up a pen
> Glasses update HUD instantly when equipped/unequipped

- code/game/machinery/vending.dm
So you can check if you're about to get memed. I really like how this works out for airlocks but vending machines don't do it
:cl:
* rscadd: Shocked vending machines will spark when bumped by a metallic item, just like airlocks
> Shocked vending machines spark when bumped by a metallic item, just like airlocks

- SQL/players2.sql
- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
- code/modules/migrations/SS13_Prefs/012-add-pull-pref.dm
- code/modules/mob/mob.dm
Toggle pull (default behavior, same as before):
When ctrl+clicking something you're already pulling, you will stop pulling.
Always pull:
When ctrl+clicking something you're already pulling, you will continue pulling (nothing happens).
I wanted this for a long time since I forget I'm pulling people sometimes and when I click them again I accidentally let go.
:cl:
* rscadd: Added a client preference that lets you choose to ignore ctrl+clicks on things you were already pulling, so you don't accidentally let go of them.
* tweak: Trying to pull yourself is now a shortcut to stop pulling.
> Adds a client preference to switch between "toggle pull" and "always pull"

- code/modules/mob/living/carbon/carbon.dm
Having between 20 and 40 brute made check-self tell you your limb was BLEEDING!! which led a few times to people bitching at me for not bandaging them and me having no IC way to tell them check-self-for-injuries was just misleading
It also was quite spammy so I made it not say anything for limbs that are OK
:cl:
* bugfix: Check-self-for-injuries no longer gives false positives about bleeding, and now only tells you about injured limbs instead of flooding your chat with my legs are OK entries.
> Improves check-self-for-injuries

- code/modules/mob/living/carbon/human/examine.dm
- code/modules/mob/living/carbon/monkey/examine.dm
I got dared to do this stupid PR and also because nobody uses digital camo because it completely outs you immediately (((not sure if AIs can still follow Unknown if camo lings appear as Unknown on cameras, IIRC))). Changeling rework when?
:cl:
* tweak: Changeling digital camouflage no longer has an examine text indicating that the user is a changeling.
> Digital Camouflage no longer has a "Please collect valids" examine text when a changeling uses it.

- code/modules/research/destructive_analyzer.dm
- code/modules/research/rdconsole.dm
It's weird that printing yourself a pneumatic cannon + chemsprayer + the lube for your chemsprayer requires no access, but raising tech levels does. Given that the latter is somewhat more benign than the former, I think there's no reason for it to stay that way.
Mostly targeted towards miners that end up having to do research all by themselves just to get their drill but getting access just for that one button is a pain in the ass.
This is 100% a balance change and if people don't want it I'm OK with closing it.
:cl:
* rscdel: By popular demand, the Destructive Analyzer no longer requires access, meaning miners and assistants alike can help raise tech levels if they find their way into R&D.
> Destructive analyzer no longer requires science access (also fixes href exploits)

- code/game/objects/items/weapons/shields.dm
Fixes #19770
Spess is saved!
Also inb4 femsec and femcaptains decide to use the baton again and we get Sawbones-disarm-spams-sec 2: Telescopic boogaloo.
:cl:
* rscadd: You can now bash riot shields with telescopic and classic batons to intimidate your foes
> Spessmen can now bash their (riot) shield with a telescopic baton.

- code/modules/reagents/Chemistry-Recipes.dm
So botany can make it again (like it used to be able to), instead of relegating it to be nearly exclusive to research botanists.
:cl:
* tweak: In Nitroglycerin recipe, replace sacid and pacid with formic and phenol.
> In Nitroglycerin recipe, replace sacid and pacid with formic and phenol

- code/game/gamemodes/wizard/artifacts.dm
- code/game/objects/items/weapons/storage/bags.dm
Now that potion bags are a thing, it's time to make use of it for pure !FUN!. This bundle costs 100 points & contains 50 murky potions, which is to say, you don't know what they are or what they do until you chug/throw them. The lesser bundle costs 20 points and contains 10 murky potions. What could potionly go wrong?
:cl:
* rscadd: Adds the (lesser) chaotic potion bundle for wizards. Dare you enter my alchemical realm?
> Adds the chaotic potion bundle for wizards.

- code/datums/uplink_item.dm
- code/modules/clothing/under/chameleon.dm
The quick vent jumpsuit is a child of the chameleon jumpsuit. Its functionally identical but has it's heat_conductivity variable set crazy high. This will make their temperature rapidly drop which functionally  will just sleep the person who wears it in a second or two and after a little while they'll start taking burn damage.
As of this last commit, here's the changes
The chameleon jumpsuit is functionally the same. Absolutely 0 changes as to how it works
the vent suit however starts off like the chameleon jumpsuit, but by using it in your hand you can register itself as it's user and toggle the Change Color verb.
What this means gameplay wise is, when you spawn in the suit it'll be like a regular chameleon suit. then by using it in hand you lock the change color verb away so that no one …
> adds a new traitor item: the quick vent jumpsuit

- code/datums/gamemode/role/vampire_role.dm
- code/game/objects/items/weapons/null_rod.dm
- code/game/objects/items/weapons/storage/bible.dm
- code/modules/reagents/Chemistry-Reagents.dm
Note: in the context of the code, a high-blood or "mature" vampire has 400 or more total blood.
As it currently stands, low-blood vampires get absolutely ASS-BLAST-USA'd by holy effects (Holy Water, chapel, blessed tiles, null rod & bible slaps from a chaplain, etc). This leads to fun things like a chaplain "accidentally" slapping a vampire once or twice with his rod/bible and leading to an immediate outing. In addition, I believe that the more unholy you are, the more SMITE-worthy you should be, while being "more human" should make you less SMITE-worthy in the eye of the universe. 
This coincidentally also makes it so low-blood vampires can go around in space without too many issues, while high-blood vampires get booty-blasted. Currently, a high-blood vampire can sit in space for a good …
> High-blood vampires now get ass-blasted by holy effects. Low-blood vampires are more resistant to holy effects.

- code/datums/gamemode/role/role.dm
ANYTIME someone gains or loses antag status it's clearly logged. This includes HAVING ALL ROUNDSTART ANTAGS BECOME LOGGED which was not the case before and a nightmare to figure out.
In some cases, this will generate 2 messages since for example thralling already has this, but more redundant is better than not enough redundant.
> Hyper-redundant become antag/unbecome antag logging

- __DEFINES/_macros.dm
- code/__HELPERS/unsorted.dm
Nonantag:
```
<span class="admin"><span class="prefix">ADMIN LOG:</span> <span class="message">Guest-2833213637/(Colton Knapp) shot *no key*/(Captain) with a /obj/item/projectile/beam/captain (<A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=31;Y=146;Z=1'>JMP</a>)</span></span>
```
Antag:
```
<span class="admin"><span class="prefix">ADMIN LOG:</span> <span class="message">Guest-2833213637/(Colton Knapp) <span title='traitor'>(A)</span> shot *no key*/(Captain) with a /obj/item/projectile/beam/captain (<A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=31;Y=146;Z=1'>JMP</a>)</span></span>
```
This will hopefully make it easier for both admins and nonadmins to investigate stuff.
> key_name() logs now show (A) next to any antag's name

- code/controllers/configuration.dm
- code/game/sound.dm
- config-example/config.txt
Useful if you use guest keys to multiaccount-test stuff, since you can't use client preferences for those.
> Adds NO_LOBBY_MUSIC config

- code/datums/uplink_item.dm
- code/defines/obj/weapon.dm
- code/game/objects/items/devices/uplinks.dm
So an Assistant can buy superglue and a briefcase full of bees if he damn wants to.
Job-exclusive items are an interesting design choice with its pros and its cons. Here are the pros and cons I see of removing that exclusivity:
(+) Traitors have more options available at their disposal, meaning more round variety and a slight general buff to the traitor role
(+) Traitors who get job changes aren't cucked out of their new job's exclusive items
(+) People won't instantly metagame that the botanist is 99% guaranteed to be the traitor when they spot spiritbreaker
(+) New exciting gimmicks not possible before
(-) New exciting gimmicks not possible before
(-) Some items (particularly E20, chef's sauce, and maybe the memechair) are kind of """balanced""" around the previous exclusivity and will …
> Turns traitor job-exclusive items to job-discounted items (can buy tator items of any job by paying extra)

- code/datums/gamemode/factions/bloodcult/bloodcult_items.dm
There was a second declaration of the cult hood's power boost where the shoes' should have been.
:cl:
* bugfix: Fix a bug that decreased cult hoods' and cult shoes' cult power boost by 10.
> Give cult shoes their 10 cult power boost, raise hood power boost from 10 to 20

- code/game/machinery/doors/windowdoor.dm
Because jesus fuck, for what is essentially just a reinforced window, even the most basic of windoors manages to have 100 HP while a normal reinforced window has 40 HP.
Current window values:
Window = 10 HP
Reinforced window = 40 HP
Plasma window = 120 HP
Reinforced plasma window = 160 HP
Old values:
Normal windoor = 100 HP
Secure/brigdoor (requires inserting plasteel) = 200 HP
Plasma windoor = 300 HP
Secure plasma windoor = 400 HP
New values:
Normal windoor = 60 HP
Secure/brigdoor (requires inserting plasteel) = 100 HP
Plasma windoor = 150 HP
Secure plasma windoor = 200 HP
[balance][qol][tweak]
:cl:
* tweak: Nerfs health of all types of Windoors by 40-50% depending on type.
> Nerfs health of all types of Windoor

- code/game/striketeams/syndicate_elite_squad.dm
Because somebody thought it'd be a great idea to have a gun that deals 60 brute and ricochets spawn in the Squaddie's active hand the moment he spawns.
NDs ensues.
[qol][tweak]
:cl:
* tweak: Syndicate High Command educated their Elite Squad about the benefits of holstering their rifle when they become active and hopes there will be less negligent discharges in the future.
> Syndicate Elite Squaddies's rifle now spawns in their backpack instead of in their active hand.

- code/datums/uplink_item.dm
- code/game/objects/items/devices/uplinks.dm
Basically title. I said I would do this in my "job-discount" PR and it got merged before I did. Hopefully this will make it seem more worth it and hopefully more FUN.
One thing to consider is that random item was essentially nerfed with the changes to job-discounted items since there's a sizable chance they will give you a non-discounted item for another job.
:cl:
* tweak: The 'Random Item' button on Syndicate uplinks now gives you a 50% discount on the item you get.
* bugfix: Fixed 'Random Item' button giving you nukeop items
> Random Item uplink deal gives 50% discount (plus doesn't give nukeop items anymore lol)

- code/modules/reagents/reagent_containers/food/snacks.dm
[grammar]
It's fun when food names have a space between them.
IE: "winepear" is now "wine pear" and etc.
> More pear typos

- code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
I looked through the threat rolls across rounds for a while now and received input from people and have come to the conclusion that 40/30 threat required for traitors at 0-4/5-9 isn't very likely to happen. This combined with the Grinch antag requiring less threat at 5-9 makes the "mini-antag" more likely to cuck the round out of traitors.
tl;dr happy new year spessmen fuck extended most of the time.
[gameplay]role]
:cl:
* rscadd: Lowered the minimum threat required to spawn roundstart traitors for lower population ranges.
> Traitors are now more likely to spawn at roundstart on lower population.

- code/modules/ext_scripts/watchdog.dm
- code/world.dm
This should fix #21529
And potentially some super-esoteric server thingies nobody really noticed before. Maybe.
**Unforeseen Consequences:**
Unknown
> Makes Watchdog call a few world shutdown thingies it wasn't calling before

- code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
[balance][role]
I understand that Vampire more or less rolls often because apart from Traitor, it's just about the only other antag that has a "low" cost to fire, so its current weight doesn't matter as much in the grand scheme of things. That said, I'm not a big fan of every round or two in a row containing 1+ vampire instead of something else.
-Weight changed from 3 to 2.
-Cost changed from 18 to 25
-Theat cost changed from (80,60,40,20,20,10,10,10,10,10) to (80,60,50,30,20,10,10,10,10,10)
:cl:
* tweak: Vampire is less likely to roll at roundstart and moreso on lower populations (15 or less).
> Makes vampire less likely to fire at roundstart (especially on lower populations).

- code/game/objects/structures/mannequin.dm
- code/game/turfs/turf.dm
- code/modules/reagents/reagent_containers/food/snacks.dm
Fixes #21540
Thanks @Exxion again
I modified 2 behaviors that obviously worked on the previous broken functionality. The proximity sensor remains the same, which may be a balance change in its own right, discuss if you like
:cl:
* bugfix: Fixed proximity sensors not detecting (or detecting in extremely buggy ways) anything that wasn't a mob. This may have slight balance implications since you can chuck a pen towards them to activate them, so do definitely make a bug report if you think this shouldn't be intentional.
> Fixes HasProximity() extreme fuckiness

- code/game/objects/items/weapons/storage/bags.dm
Companion PR to #21632
So apparently this was supposed to hold up to 21 trash items. It even had a sprite for reaching 21.
I made it hold 21 combined_w_class instead. Works for me.
However if it's too full, it will slow you down when worn (won't slow you down if you're just carrying it or if you clip it to your janicart)
:cl:
* bugfix: The Janitor's trash bag can now hold up to 21 items, as intended. To prevent it from becoming the ultimate belt slot container, it will slow you down if it's too full and worn on belt slot (won't slow you down if you're just carrying it or if you clip it to your janicart)
> Janitrashbag revival

- code/game/objects/items/weapons/cigs_lighters.dm
- code/game/objects/items/weapons/storage/fancy.dm
Fixes #19526
:cl:
* rscadd: Folded notes now fit in cigarette packs. You can now light matches using other matches again. You can now put coins and burnt matches back into matchboxes (don't try to put a lit match back inside!)
> Folded notes fit in ciggypacks, coins fit in matchboxes

- code/datums/uplink_item.dm
Why?
+ Increases player agency. Each player that gets a bundle will now be able to use said bundle slightly differently, rather than playing out pretty much the same every time.
+ Makes bundles more reliable so you're not totally out of luck if you can't make it work.
+ Bundles have historically always seemed to be thought of as underpowered when people discuss them
+ This was effectively already a thing back when we had the extra telecrystals from THEPAPERTM. I would honestly prefer EITHER #21296 OR this to happen, not both.
:cl:
* tweak: Syndicate bundles now cost 14 telecrystals, down from 20. This is to make them a little more reliable and less repetitive.
> Syndie Bundles cost 14 TC, down from 20

- code/game/gamemodes/wizard/artifacts.dm
- code/game/objects/items/weapons/storage/bags.dm
Why?
+ Bundles have historically always seemed to be thought of as underpowered when people discuss them
+ Maybe you can upgrade one of your spells now, for even more possibilities!
+ Makes them a bit more reliable since, well, you're out of luck if you don't get a mobility/defensive spell. Which translates to "everyone will take blink with their bundle since blink is so horrendously OP", but I can't nerf blink in the same PR as this one
:cl:
* tweak: Wizard spell bundles now cost 80 spellpoints, down from 100. This is to make them a little more reliable.
> Wizard spell bundles cost 80 spellpoints, down from 100

- code/game/gamemodes/wizard/spellbook.dm
Status quo: Major truesight is 10 points for 5 minutes of X-ray.
Cost readjustment: 5 points for 5 minutes.
Reason: The orb of scrying is 20 points for permanent X-ray. The potion's discount seems pretty low, given that one of the big draws of potions (no robes required) is also replicated by the permanent version (scry).
The lesser truesight potion could also use a duration buff perhaps. Personally, I think I'd find it hard to use potions with such brief durations in general since the 2-second onset is awkward.
:cl:
* tweak: Halve the cost of the major truesight potion, from 10 points to 5.
> Halve the cost of the major truesight potion.

- code/game/jobs/job/assistant.dm
- code/game/jobs/job/job.dm
- code/game/jobs/job/security.dm
- code/game/jobs/job_controller.dm
- code/game/machinery/computer/labor.dm
- code/modules/admin/admin_verbs.dm
- code/modules/admin/topic.dm
- code/modules/admin/verbs/randomverbs.dm
- code/modules/mob/new_player/new_player.dm
Through the magic of OOP
Fixes #21580 fully since 1 of the 2 things there isn't a bug
:cl:
* bugfix: Fixed the Labor Administration Console allowing you to set the assistant job limit to 0. Also, the Assistant job now will always have a minimum of 2 slots available.
> Refactors assistant job limit for labor console compatibility

- code/game/objects/items/potions.dm
Because skeletons are for fags and xenos, who are also fags. Also I was promised OG zombies, not meme skeletons that never seem to happen.
[gamemode][qol]
:cl:
* tweak: The wizard zombie potion now has a 100% chance to create a zombie instead of 50% if the target is human.
> The zombie/exanimis potion now has a 100% chance to create a zombie if the target passes the isjusthuman check.

- code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
And you get a roundstart Bleb and YOU get a roundstart Bleb and YOU get a roundstart Bleb!
I vaguely understand that Bleb's weight was put at 5 for experimentation raisins, but in lights of our glorious roundstart bleb overlords, let's tone the weight down to 3. This changeroni will make it more in line with the others as opposed to being more likely to roll often roundstart and put the gamemode down the path of MALF's tired gamemode of a laundry list.
[balance][gamemode][tweak]
:cl:
* tweak: Blob's roundstart weight has been reduced, making it a bit less likely to roll at that time.
> Blob is less likely to roll at roundstart

- code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
MALFIE makes more sense as a midround antag than roundstart for a few reasons:
1 - AIs somehow manage to be instantly malfunctioning when the shift begins.
2 - Nobody likes the very likely instant or soon-to-be instant plasmaflood before anybody can prepare or whatever.
3 - MALF AIs aren't supposed to occur often, so the requirements to roll it will follow that logic.
3.5 - I got dared to do this, sort of.
[balance][gamemode][tweak][controversial]
:cl:
* tweak: Malfunctioning AIs can now occur dynamically midround with incredibly low odds. Dead/Low Lowpop can't roll midround MALF.
> MALF AIs now have a chance to roll midround with very low odds.

- code/game/machinery/ammolathe.dm
It's okay when I decry ~~griff~~ FUN that pertains to other departments, but not when others do it to my departments.
On a slightly more serious note, I should have paid more attention to the Ammolathe PR, because good lord this is a case of Vectors being borked and the c*der behind it powercreeping his content intentionally. For the record, you can currently take magazines meant for guns that are intended to be adminbus/wizard/traitor-only (NT12 and Automag) and load them into a Vector. Said vector just so happens to be semi-auto and have a really nice burst-fire feature. You know what regular shotguns don't have? Semi-auto and burst-fire. I lurv me some 120 brute in half a second (quoting Sonix here). The only shotgun that doesn't quite get rendered obsolete by the Vector is the Combat …
> The Ammolathe can no longer print NT12 and Automag magazines.

- code/game/machinery/ammolathe.dm
Reverts vgstation-coders/vgstation13#22084
There's something something about a 3 day minimum wait time for [BALANCE] changes, along with the fact that people could have had time to argue about this change and propose modifications or alternative solutions to the Ammolathe/Vector problem.
When I was coding the NT12, I went around and considered maybe adding it to the armory or something, but then this begs the question: what's the point of the regular 4-round pump action if the NT12 exists? Are people fine with that change? Or does adding it to the Ammolathe with a huge material price involving NEVER-EVER mats from science instead make it a balanced (TM) addition? Or how about just ask for Glass+Metal instead? Would that be fine?
Slimes may call me grudgecoding on the previous PR because …
> Revert "The Ammolathe can no longer print NT12 and Automag magazines."

- code/datums/gamemode/dynamic/dynamic_rulesets_midround.dm
I know we've had that PR to standardize antags weight and whatnot, but ever since midround Blobs have been able to force the station into quarantine, things have gone slightly out of hand. I daresay that the quarantine happens fairly quickly, as midround Blobs get a bunch of free tiles to kickstart the progress to quarantine. 
Also I have my doubts regarding the theory behind "midround blobs being weak because they start exposed to space" and "the crew is armed and prepared", because the latter part isn't always true and negates the former. Then the Blob(s) quickly run out of control because nobody established emitter lines from space or 3+ guys with eguns came around to immediately zap the Blob(s) into submission. Then the shuttle gets canned because [QUARANTINE ENABLED, BUT THE AI WON'T …
> Reduces Midround Blob weight and ups threat cost & threshold.

- code/game/objects/items/weapons/storage/secure.dm
Fixes #22487
🆑 
* bugfix: Fixes secure safe UI not updating
* experimental: Vox cloaca has been removed from the permissible items to use in the vaporizer from the cigarette machine.
> Fixes secure safe UI not updating

- code/game/machinery/machinery.dm
Also shows parts if the panel's open but no upgrades are done.
:cl:
* tweak: Bluespace RPEDs now displays machine parts when they can't upgrade.
> Bluespace RPEDs now display machine parts when they can't upgrade.

- code/game/machinery/iv_drip.dm
- code/modules/reagents/reagent_containers.dm
- code/modules/reagents/reagent_containers/pill.dm
as requested in #22695
The "decoy" empty pills don't actually deplete themselves so they remain indefinitely
> Empty pills delete themselves in IVs

- code/modules/projectiles/projectile/special.dm
[tweak]
maybe Im stupid?
rather than setting the damage to 30, I made the PKA add 15 to whatever value the damage was before. 
It changes nothing in-game, as the base PKA damage is 15 but I figured this was better if there's different stacking damage sources in the future.
> small edit to the PKA projectile

- code/modules/projectiles/guns/lawgiver.dm
Because lets be honest, having the words on the description itself isnt bad at all, and having to consult the wiki is kinda baloney for something that should atleast be learnable within the game itself. Not everybody watches every single pr on the github you nerds.
:cl:
* rscadd: Altered the desc of the Lawgiver to include the words needed to switch ammo types.
> Adds desc text to Lawgiver

- code/game/objects/items/weapons/storage/secure.dm
Fixes #22873
hacks upon hacks upon hacks of shitty unmaintainable oldcode lead this kind of shit to happen and take 20 minutes to debug entirely
did you know the proc most oldcode machines use to update UI is literally a disguised attack_hand()? but wait, I need attack_hand() for something else! OK, I'll just write my UI in attack_self() and write the update UI as a hackish snowflake code that makes people within 1 tile of me call attack_self(). but wait I also made a safe which can't use attack_self() since it can't be picked up and for some reason I decided should inherit this mess anyways and also should be an anchored item instead of a structure. that's OK I'll just make its attack_hand() return attack_self() and this will Just Work
> Fixes secure briefcase HUD not updating

- code/modules/reagents/Chemistry-Reagents.dm
Eventually someone was gonna have to do something about people drinking 900u antitoxin.
I want antitoxin's OD to be something that does not fuck up the day of someone who is given too much by a newbie doctor, but still dissuasive enough that people won't WANT to 900u antitox anymore.
Vomiting removes antitoxin from blood and fucks up your ratios if you're combining it with other powergay chemicals like creatine and synaptizine, but it doesn't fuck your day up otherwise. So I think it's a good solution.
Oh it also makes your screen shake an ever so tiny bit. Not enough to be debilitating in any way but still annoying enough to make you fucking hate it.
:cl:
* tweak: Antitoxin now overdoses at 60 units. It will still heal, but it will also occasionally make you throw up.
> Antitoxin OD (>60 units) makes you throw up (this removes a lot of anti-toxin and fucks up your powergay ratios)

- code/datums/uplink_item.dm
[wiki][balance]
Incomplete list:
> modified flaregun: seen in 3 out of 1606 traitors
banannon: seen in 3 out of 1606 traitors
box of living long balloons: seen in 4 out of 1606 traitors
syndicate atmospherics tape: seen in 4 out of 1606 traitors
syndicate engineering tape: seen in 5 out of 1606 traitors
evidence forger: seen in 5 out of 1606 traitors
feldbischof's bible: seen in 5 out of 1606 traitors
uplink implant: seen in 6 out of 1606 traitors
inflatable decoy: seen in 6 out of 1606 traitors
power gloves: seen in 7 out of 1606 traitors
trophy-belt: seen in 7 out of 1606 traitors
"does not tip" database backdoor: seen in 8 out of 1606 traitors
instant smoke bombs: seen in 9 out of 1606 traitors
bug detector & camera disabler: seen in 9 out of 1606 traitors
quick vent jumpsuit: seen in …
> Reduces cost of some of the least popular tator uplink items

- code/modules/maps/spawners/spawners.dm
In doing #22775 I noticed that other maps have 8+ Maint random loot spawners, Box has only 2 and both walled in
Given that these loot spawners almost always spawn pure crap like dresses, pens, and 2-nutriment snacks, I figure it should be good to add slightly more junk to maint
[box]
:cl:
* rscadd: Added a bit more random loot to Box maint. Still less than other maps.
> Adds slightly more maint loot spawners to Box

- code/modules/mob/living/carbon/human/human.dm
The zombie staff was the only thing that did it properly, because it didn't actually use make_zombie.
:cl:
* bugfix: Exanimis potions and anything that uses default make_zombie can now produce player zombies.
> make_zombie now can produce zombies controlled by players.

- code/modules/mob/living/simple_animal/hostile/necro.dm
Closes #22953
I like it more this way, and it fixes the "NPC zombies from gluttons will attack the glutton and the master necro". To restate:
1. Exanimis potions will now be able to produce a full PC zombie infestation, instead of a buggy NPC zombie infestation.
2. Same for the zombie virus with some futzing around (NPC glutton chewing on a player corpse). This specifically can be addressed if people want it.
:cl:
* tweak: Glutton zombies can now create player zombies instead of NPC zombies.
> Glutton zombies can now create player zombies.

- code/game/machinery/computer/cargo.dm
- nano/templates/supply_console.tmpl
i literally just did what https://github.com/vgstation-coders/vgstation13/pull/22010#issuecomment-486917293 says because the OP was literally spoonfed how to finish their PR and still didn't do it
5 minute hackjob
1% tested
closes #22010
:cl:
* tweak: Soldering the Cargo Supply Console board will remove the access requirement to approve/deny orders and to call/return the supply shuttle.
> revives #22010 - Supply Consoles no longer require cargo access to use 2: SOLDERING EDITION. 

- code/modules/admin/topic.dm
Admins would consistently forget the linebreak so it's automatic now.
> Babbyproofs credit disclaimer admin button

- code/game/gamemodes/scoreboard.dm
- code/modules/credits/episode_name.dm
if(score["dimensionalpushes"] > 0)
dat += "<B>Dimensional Pushes:</B> [score["dimensionalpushes"]]<BR>"
if(score["assesblasted"] > 0)
dat += "<B>Asses Blasted:</B> [score["assesblasted"]]<BR>"
if(score["shoesnatches"] > 0)
dat += "<B>Pairs of Shoes Snatched:</B> [score["shoesnatches"]]<BR>"
if(score["buttbotfarts"] > 0)
dat += "<B>Buttbot Farts:</B> [score["buttbotfarts"]]<BR>"
if(score["shardstouched"] > 0)
dat += "<B>Number of Times the Crew went Shard to Shard:</B> [score["shardstouched"]]<BR>"
if(score["lawchanges"] > 0)
dat += "<B>Law Upload Modules Used:</B> [score["lawchanges"]]<BR>"
if(score["gunsspawned"] > 0)
dat += "<B>Guns Magically Spawned:</B> [score["gunsspawned"]]<BR>"
if(score["nukedefuse"] < 30)
dat += "<B>Seconds Left on the Nuke When It Was Defused:</B> …
> Adds a few more stats to the roundend screen

- code/modules/maps/spawners/spawners.dm
- code/modules/mining/surprises/tg.dm
- code/modules/mining/surprises/vg.dm
[tweak]
The space spawner that made guns sometimes, and the vaults that you find on the asteroid now all spawn plasma cutters instead of plasma torches. to make them a little less lame
:cl:
* rscadd: the asteroid vaults now spawn plasma cutters instead of plasma torches
> spawners that made plasma torches now make plasma cutters

- code/game/machinery/iv_drip.dm
- code/modules/reagents/machinery/chem_master.dm
- code/modules/reagents/reagent_containers.dm
- code/modules/reagents/reagent_containers/food/snacks.dm
- code/modules/reagents/reagent_containers/pill.dm
Fixes #23210
Fixes #23211
Fixes https://github.com/vgstation-coders/vgstation13/pull/23194#issuecomment-500421796
Does https://github.com/vgstation-coders/vgstation13/pull/22849#issuecomment-490727832
:cl:
* bugfix: Fixed pill crushing and pill IV drips.
* tweak: People will now only see you crush pills into drink glasses etc. if they're within 2 tiles, rather than anywhere on screen.
* rscdel: Removed the 'make empty pills' button from chemmasters, since it was buggy and taking up space and let's be honest you can just make 0.1u water pills for the same effect.
> Fixes pill crushing, pill IV drips etc, removes "make empty pills" button in chemmaster

- __DEFINES/planes+layers.dm
- code/modules/hydroponics/spreading/spreading.dm
Closes #23016
I tried to test it but I couldn't varedit on my local server for some reason.
:cl:
* tweak: Creeper vines show under things instead of over now.
> Creeper vines show under things instead of over.

- code/modules/projectiles/projectile/bullets.dm
Nothing to see here folks, move along.
[administration][honk]
> Adds an admin-only projectile variant of Buckshot.

- code/modules/credits/credits_clientprocs.dm
No more will your ears be blasted at the end of a calm round. Fixes #23718 
:cl:
* bugfix: Credits/Jingle Volume now applies to jingles if credits are disabled.
> "Credits/Jingle Volume" now actually works with jingles

- code/modules/hydroponics/hydro_tray.dm
Fixes #24677
:cl:
* bugfix: Makes hydro trays unable to be opened at a distance with alt-click.
> Hydrotray altclick fix

- code/modules/reagents/reagent_containers/food/snacks.dm
[bugfix][tweak]
The inheritance on a couple items in snacks.dm was fucked, giving some items a stunning amount of nutriment. This also ends up fixing Banana Chips, which had a misspelling that caused the recipe to not provide Honk Serum since at least March 2015.
This nerfs several foods, but brings them down to the level of their parents:
Synthetic Burger: 12 -> 6 Nutriment
Synth-kabob: 16 -> 8 Nutriment
Synthmeat Steak: 8 -> 4 Nutriment, 2 -> 1 Sodium Chloride, 2 -> 1 Black Pepper
Flatdough: 6 -> 3 Nutriment
Plain Chips: 7 -> 5 Nutriment
Xeno Chips: 17 -> 10 Nutriment
All Other Chips: 13 -> 7 Nutriment
Cooked chips are 2 nutriment higher than vending machine chips, and flavored chips are 2 nutriment higher as well. Xeno Chips were supposed to be 10 nutriment from the start I believe. …
> Fixes some unintentional food buffs & Banana Chips

- code/game/machinery/kitchen/smartfridge.dm
[tweak]
Fixes #25287
:cl:
* tweak: Honeycomb can now be put in SmartFridges
> Honeycomb can be put in SmartFridges

- code/modules/virus2/effect/stage_3.dm
Which probably will mean that roundstart mice won't be shitting up maint. And won't show up as often in roundstart viruses.
[tweak][gameplay]
:cl:
* tweak: The "colorsmoke" virus symptom shouldn't appear in maintenance mice or roundstart viruses as often.
> Ups the danger level of the "Colorsmoke" virus symptom.

- code/modules/clothing/suits/plate_carrier.dm
Because they're currently hilariously terrible and damage bleedthrough is a pain in the dick, thanks nu-damage resist code. Note that on rare occasions, the plates will break at a much lower damage threshold, because damage resist code isn't 100% consistent with plate code. The below results are the most consistent I've been getting.
Currently:
-Ceramic (default) plates tank NO ballistic shots (they don't reduce or absorb any damage) and can tank one (1) laser shot.
-Plasteel (ballistic) plates tank one (1) shotgun/revolver round and break, leaving you with 30 brute + bleeding.
-Ablated Ceramite (laser) plates tank seven (7) laser shots, leaving  you with 30 burn.
Buffed:
-Ceramic (default) plates tank one (1) shotgun/revolver round and break, leaving you with 6 brute and no bleeding. It …
> Buffs the plates for the plate carrier

- code/defines/obj/weapon.dm
For what purpose? Because it should be a reliable tool and it apparently has a 10% chance to fuck up because reasons.
As a side note, thanks Comic for commenting on the proc chance.
:cl:
* tweak: Security Bolas now has a 100% chance to trip, instead of the old 90%.
> Security Bolas now has a 100% chance to trip instead of 90%

- __DEFINES/setup.dm
- code/game/striketeams/nanotrasen_deathsquad.dm
- code/modules/mob/language.dm
Language key is ~%~ &. Thinking of speech/ask/exclaim verbs to use.
:cl:
* rscadd: Deathsquad can now talk in a phonetic language with :&
> Adds the NATO phonetic alphabet as a default language for deathsquads.

- code/game/machinery/ammolathe.dm
- code/modules/projectiles/guns/projectile/automatic.dm
This adds the following to the stock vector receiver's blacklist
-Gyrojet mags
-Uzi mags (just .45 but with more bullets)
-.45 pistol mags
-.50 mags
-762 mags (behead those who merged this shit)
All of these mags with the burst fire feature were able to crit in one hit, or  simply did enough damage to near crit someone and have them die soon after because of bleeding, or did enough to put them into pain crit. 
With this the vector should stop being gunk and can enjoy a nice niche  as the burst fire glock which is pretty ok imo.
Ive left these magazines and ammo in the ammolathe, in case an admeme gives them to the crew or they spawn through spellbooks so that fun!!! can still be had. But I've left a warning for the aspiring coders of tomorrow in the ammolathe file
+
closes #25895
:cl:
* …
> Unretards the vector

- code/modules/mob/living/silicon/pai/recruit.dm
I tested it for a few minutes with no apparent fuckups.
:cl:
* tweak: "Teleport" button produced by people querying ghosts for a pAI, now makes the clicking ghosts follow the pAI instead of just teleporting to it.
> Make the ghostchat 'Teleport to pAI' button, follow that pAI

- maps/snaxi.dm
0% tested. I'm not sure I've ever played in a snaxi ling round, but it doesn't sound good, and I've heard some bitching about it every now and then.
:cl:
* rscdel: Remove ling from snaxi.
> Removes ling from snaxi.

- code/game/centcomm_orders.dm
[bugfix]
Fixes #26321 and fixes #25407
The must_be_in_crate var was always in the code for cargo requests, but never used. The popout/large cake never fit in crates and sending it back normally wouldn't do anything. This fixes that.
It also makes poutine citadels not need to be in crates either, despite fitting in them, since players probably won't think it'll fit (not like anyone will waste one of those by sending it to centcomm)
:cl:
* bugfix: Central Command Requests at Cargo for large cakes no longer require crates.
> Fixes Central Requests at Cargo for large cakes

- code/modules/security levels/keycard authentication.dm
[tweak]
The keycard auth devices in head offices will now provide feedback when you swipe your card, tell you that an ERT was successfully requested, and will now instantly approve the alert/access/ERT when a second person swipes, instead of waiting a few seconds.
Fixes #26298
:cl:
* tweak: Keycard Authentication Devices now have no delay between the second person swiping and having something happen.
* tweak: Requesting an ERT with the keycard device will now display a message if you successfully request one.
> Keycard Authenticator Devices have no delay and now provide actual feedback.

- code/datums/religions.dm
[bugfix]
It's time to slam now.
Fixes #26436
:cl:
* bugfix: Fixes the Chaplain's athletic shorts if you choose Slam as your religion.
> Fixes missing athletic shorts sprite in the Slam religion

- code/datums/religions.dm
[tweak]
Also adds a couple new keywords. Fixes #26454 
:cl:
* tweak: Chaplains can now use deities to select a pre-made religion, instead of just keywords.
> Lets Chaplains use deities when picking a pre-made religion, instead of just keywords

- code/game/machinery/ATM.dm
[bugfix]
Every ATM (except a few on Meta that I'll fix) is offset from its source to fit on walls instead of being on the walls themselves. Right now dispensing cash can have it go awkwardly to the side on some ATMs (see #26755). Dispensing cash on the ATM's source turf instead will always dispense it in front of the ATM. Tested on Box
I don't think I've ever seen the throw code used by ATMs? I can just re-add it if it's useful.
Fixes #26755
:cl:
* bugfix: ATMs will now print money directly into your hands. Failing that, it'll be at your feet.
> ATMs now print cash directly in your hands

- code/game/objects/items/devices/radio/headset.dm
PR pushed on behalf of @jakmak6, ask him for reasons. He said he tested this.
:cl:
* bugfix: Fixes a bug where changing headset freq to a department freq while that headset has an encryption key for the department, would make that department's chat key (.e, .s, etc.) stop working.
> Recalculate channels when a headset's frequency is changed.

- code/game/objects/items/devices/radio/encryptionkey.dm
- code/modules/mob/language.dm
- code/modules/mob/living/say.dm
PR pushed on behalf of @jakmak6, ask him for reasons. He said he tested this.
:cl:
* rscadd: Add a Common channel mode to headsets, .o, function identical to ;. Makes it more convenient to e.g. use custom telecomms channels.
> Add a Common language mode to headsets, .o, function identical to ;

- code/game/objects/items/devices/radio/radio.dm
Fixes #27262
Sorry for the wait. I tested with captain and assistant headsets, xenos and constructs' inherent channels, and :h versus ;. No runtimes or apparent issues.
* bugfix: Make :h speak over departmental instead of common channel again.
> Make :h speak over departmental instead of common channel again.

- code/datums/gamemode/factions/bloodcult/bloodcult.dm
- code/datums/gamemode/role/cultist.dm
Closes #28150
PostMindTransfer is being used for roundstart cultists instead of OnPostSetup. Tested this change, it werks. I'll see if I can find out later why that's the case if it's not intentional, but adding the notes to that function works in the meantime.
:cl:
* bugfix: Add the starting runes to roundstart cultists' notes.
> Add the starting runes to cultists' notes.

- code/datums/gamemode/factions/bloodcult/bloodcult_runespells.dm
Two issues:
1. It would display the animation three tiles up and right from the cultist that should see it, instead of being centered on the noncult that causes the animation
2. More importantly, the animation is visible to the noncult.
I'll try to get it working as intended (and the other part of the effect that shows the person that walked on the rune to cultists does work as intended), but for now might as well make it not expose the cult.
:cl:
* rscdel: Remove the buggy walk-over animation from the reveal rune.
> Remove the buggy walk-over animation from the reveal rune.

- maps/roidstation.dm
- maps/snaxi.dm
- maps/tgstation-sec.dm
not tested but it should werk
tgstation-sec banned malf, but forgot to call the parent where ling is banned
banning ling explicitly is redundant for snow and roid for the same reason
> Remove ling from castle.

- code/modules/mob/living/simple_animal/constructs.dm
0% tested, I'll do that a little later, I guess dont merge in the interim. also need to make clicking the wraith spell inform the person that 'z' also works.
:cl:
* tweak: Let wraiths use their jaunt spell by pressing the "use inhand item" button.
> Allow wraiths to jaunt on pressing 'z'

- code/modules/projectiles/projectile/ricochet.dm
- code/modules/reagents/reagent_dispenser.dm
[consistency]
closes #28994
If the parent of a projectile has damage, such as ricochet electrodes (child of ricochet bullets) and shot syringes (child of bullets), the nodamage var won't do anything if the object hit isn't a human or silicon. The actual check is in bullet_act, so everything but those two would get damaged by the ricochet taser's electrodes since it was being passed off as bullets. Syringes already are set to 0 damage.
:cl:
* tweak: Ricochet tasers no longer blow up fuel tanks or kill animals.
> Ricochet taser projectiles no longer blow up fuel tanks, kill animals

- code/game/machinery/recharger.dm
[bugfix]
Closes #29111 
Takes about 23-24 seconds to charge from empty, compare to 10 seconds for the regular taser.
:cl:
* bugfix: The Stun Helmet can now be recharged.
> Lets stun helmets be recharged

- code/modules/food/recipes_microwave.dm
<bugfix>
Fixes #27840
:cl:
* bugfix: Donut Burgers can now be made with human meat
> Donut Burgers can now be made with human meat

- code/game/striketeams/nanotrasen_deathsquad.dm
Closes #29662
It was removed with the outfit datums PR, since the equip_deathsquad proc where the language was added, was deleted.
:cl:
* bugfix: Re-add NATO alphabet language to deathsquaddies.
> Re-add NATO alphabet language to deathsquaddies.

- code/modules/spells/aoe_turf/fall.dm
Closes #30247 and #30237
:cl:
* bugfix: Remove invisible dense mob after generating timestops with items.
> Clean up an invisible mob after using /proc/timestop

- code/modules/clothing/masks/miscellaneous.dm
last night I was in a round's dead chat and we were talking about past rounds when someone said to me "belet its times like that where I wish I could just muzzle you to shut up" and I responded with "so why did you not" and they responded "because you're a plasmaman and you would die"
while on one hand I was pleased that their personal desires did not get in the way of my character's safety, on the other hand a part of me felt like their interaction was being limited because of that
when I brought this point up someone else referenced a [tg pull request that solved this](https://github.com/tgstation/tgstation/pull/58330)
however the referenced PR adds a completely new item which sounds like a lot of work which is a thing I am not very interested in, but if you think what the referenced PR …
> muzzle internals

- code/datums/gamemode/dynamic/dynamic_rulesets_roundstart.dm
[tweak]
You remember lowpop vampires? Thankfully we don't see them very much nowadays, because dynamic threat costs scale with population, and now vampires require more of it to spawn at lowpop
Vampires require 80 threat level at 0-4 players, 70 at 5-9, 60 at 10-19, 30 at 20-24, 20 at 25-29, and 10 at 30+
however,
Changelings require 80 threat level at 0-4 players, 60 at 5-9, 40 at 10-19, 20 at 20-29, and 10 at 30+
That seems kinda small, changelings are somehow less threatening than vampires are, which doesn't really feel right, at the very least they should be equivalent, which is what I'm doing here
:cl:
* tweak: changelings threat level is bumped up a bit (equivalent to vampire threat)
> changelings threat level is bumped up a bit

- code/modules/mob/living/carbon/combat.dm
- code/modules/mob/living/silicon/mommi/mommi.dm
- code/modules/mob/living/silicon/robot/robot.dm
[bugfix]
the self uprighting module now activates after being tackled
crabs can now be made vertical again instead of being headpatted
undid the balance changes. watch the tackleniggers downboat this because tackled borgs will now fix themselves in 5 seconds
#30720
#32327
> horizontal silicon fixing

- code/datums/supplypacks.dm
[tweak]
a response to #30403 and #30365
30 feels too high for such an order, that's more expensive than the crate of surgical tools and the crate with the fireaxe, you can literally get security weapons for the same amount of money that you can get a single fuel tank for
Water and silicate decreased to 10 per tank, 15 for fuel and acid
as an aside, I have not noted a single mass fueltank gimmick between now and the cost increase
:cl:
* tweak: reagent tanks cost less
> Reagent tank costs are a bit more sensible

- code/modules/mob/living/carbon/human/update_icons.dm
[tweak]
this seemed like a bit of a depreciated feature ever since you could just resist out of both of them
-->
:cl:
* tweak: putting a straitjacket on someone who is handcuffed no longer automatically uncuffs them
> straitjackets no longer automatically remove handcuffs

- code/modules/mob/living/carbon/brain/brain_item.dm
- code/modules/organs/organ_objects.dm
Examining brains will now give you a slightly better indication on whether they're revivable or not
brain examine messages are very misleading currently
:cl:
* rscdel: examining organs(ie kidneys) will no longer inform you if they were sentient or not
* tweak: improved brain examine messages
> better brain examine messages

- code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon.dm
[balance][tweak][bugfix]
makes your max charge limited to the SMES output, as opposed to your current charge+chargespeed
uncaps max charge when sucking APC's
each APC will add double its cell charge to the demon's maximum charge(stock APCs are 2500, and will give you 5000 power)
makes the numbers make more sense(you'll get 50kw max charge in a stock SMES instead of a random amount)
sucking all of the station APC's is now recommended because you get more powerful with each(maxpower previously capped at 25k for stock APCs)
:cl:
* bugfix: fixed pulse demon SMES draining
* tweak: pulse demon sucking APC's now always add charge
> pulse demon SMES and APC draining tweak

- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/dead/observer/spells.dm
by update i mean it changes it to hide all ghosts, not just yours
you can still hide only yourself by typing "hide-sprite" into the commandbar, or using the "hide sprite" verb in the ghost tab
i feel that you want to hide all ghosts more often than just yourself, so having it on the HUD makes more sense
uhhh ummmmmm uhhhhhh ehhhmmmmm
makes observers have a less miserable experience(FUCK the observer metaclub)
:cl:
* tweak: ghost "hide sprite" spell has been replaced with "hide ghosts". you can still hide just yourself using "hide-sprite"
> update ghost hide sprite spell

- code/modules/mob/dead/observer/verbs.dm
makes toggledarknes no longer hide ghosts
adds two intermediate darkness states, between dark and fullbright
closes #33108, #32212, #29623, #6671
reduces active issue count
makes observers have a less miserable experience(FUCK the observer metaclub)
:cl:
* tweak: ghosts can now see other ghosts while toggling darkness
* rscadd: ghost toggledarkness now has two extra modes
> update ghost toggle darkness

- code/modules/reagents/reagent_containers/glass/bottle.dm
tested this locally and the chemmaster works, and bottle subtypes with larger volumes work too
i'm not sure if calling bottle/new() without giving it a volume arg will error because missing argument, but it doesn't seem to
closes #33262
sneed
:cl:
* bugfix: upgraded chemmasters now properly dispense larger bottles, instead of just upgrading the label
> fix upgraded chemmaster bottling

- code/datums/next_map.dm
Reverts vgstation-coders/vgstation13#33150
brings back line
it's fucking october
> Revert "Removes Line Station from the voting pool"

- code/game/machinery/atmoalter/gas_mine.dm
~- [x] connects the miner to the grid when wrenched on top of a wire node~
~- [ ] connects the miner to the grid when a wire is built under it~
~- [ ] shows the miner's power draw on the power monitor~
~- [ ] shows the miner's power draw when multitooling consistently~
~- [x] reduces the mining speed back to default if the power wire gets cut while running~
~- [x] can by abused by #33737~
i dunno you tell me
:cl:
* rscadd: gas miners now show their output speed
* rscadd: gas miners can now draw additional power set via rightclick
* rscadd: gas miners now mine faster and with a larger pressure limit the more power they consume
> gas miners scale with power MK2

- code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon.dm
- code/modules/mob/living/simple_animal/hostile/pulse_demon/pulsedemon_powers.dm
[balance]
- reverts the max charge upgrade mechanic added in #33124 - you now get up to 200KW in an SMES, and 5KW per APC sucked(instead of the old "idle inside the SMES while clicking the upgrade button")
- selfsustaining charge is now much cheaper but with a much bigger slowdown
- prevents you from turning off selfsustaining charge when not in a cable - this used to be an instant suicide button
- removes "empower" from most spells, so you can't make them virtually free to cast anymore
- changes the spell unlock and upgrade costs
**new unlock costs**
**new upgrade costs**
i ded nerf pulsedemon NOW
:cl:
* tweak: pulse demons must now suck APC's/SMES to get more power
* tweak: pulsedemon spell unlock and upgrade costs
> pulse demon tweaks

- code/datums/outfit/medical.dm
[tweak]
Changes the roundstart loadout of Brig Medics to medic armor (added in https://github.com/vgstation-coders/vgstation13/pull/29642) instead of the standard paramedic vest
It also moves the penlight from the suit storage into the right pocket
seccies get into more violent situation and I think it's better for the role/alt. title, which is more closely aligned with security, to have default gear which makes them a little tougher and not just die the moment they get hit by a stray slug during a cargo raid for example
:cl:
* tweak: Brig Medics now spawn with medic armor
> Brig Medics spawn with medic armor instead of paramedic vest

- code/modules/mob/living/simple_animal/hostile/hog.dm
instead of being paralyzed while standing still, the headbutt will knock you down
you can still crawl away while horizontal
this also fixes the trayhit sound not playing
this field left blank as an exercise to the reader
:cl:
* tweak: hogs now knock you down instead of paralyzing
> fix spacehog headbutts

- code/modules/mob/living/carbon/human/emote.dm
paroxetine prevents suicide
prevents you from dabbing while cuffed if you queue up the prompts 
closes #33728
sneed sells feed and seed
:cl:
* tweak: paroxetine now prevents you from dabbing
* bugfix: being handcuffed now properly prevents you from dabbing
> paroxetine prevents *dab

- code/modules/mob/living/silicon/mommi/login.dm
- code/modules/mob/living/silicon/mommi/mommi_subtypes/sammi.dm
[tweak]
[qol]
This PR does the following for SAMMIs:
1. Gives them a unique welcome message that links to a new wiki page written by @Eneocho instead of the MoMMI welcome message (what the fuck)
2. Makes the cyborg lawsync sound play whenever their laws are changed (this is normally silent for no good reason)
3. Forbids a SAMMI from using a multitool on itself to reprogram its laws and epically self-antag (what the fuck did the original coder mean by this)
4. Lets SAMMIs talk normally and on common
:cl:
* rscadd: Adds a welcome message for SAMMIs and a sound effect for a law change
* tweak: SAMMIs can no longer reprogram themselves
* rscadd: SAMMIs can talk now
> SAMMI tweaks and changes

- code/modules/mob/living/silicon/robot/robot.dm
[bugfix]
Kudos to @Kurfursten for noticing the real culprit and fixing my shitcode fix
Combat borgs using mobility module will now stay in their roll sprite instead of constantly switching between roll and normal sprites
:cl:
* bugfix: Fixes a bug affecting mobility module's "roll" sprites
> Combat borg mobility module sprite fix

- code/datums/supplypacks.dm
- code/modules/clothing/clothing.dm
[tweak]
Adds some medium sized emergency gas tanks (larger than the ones in your box) to the space suit crates in the cargo catalogue
These are already some of the most expensive crates in the catalogue so I'm not too concerned about balance
Not even the captain goes without a spare so why shouldn't we? They're quite a backup
Also I'm tired of having to siphon the yellow oxygen tanks from the blue lockers in maintenance to refill them with plasma like I'm trying to sneak vodka into the high school prom or some shit, I want something that looks nice and purple and matches with the colors
if you want other gas tank creep be sure to inform me here rather than never
:cl:
* tweak: adds some of the medium sized emergency gas tanks to the Space Suit crate, Vox Pressure Suit crate, Plasmaman Suit …
> slips some medium sized emergency gas tanks to space suit crates + your suit storage slot

- code/modules/mob/living/carbon/brain/MMI.dm
[bugfix]
makes the MMI not invisible, so you can see it after the crab is killed
moves the namepick() so the MMI doesn't get sent into the void incase the crab is killed before namepicking
closes #33972
closes #21864
closes #22938
closes #31291
closes #32735
closes #20701
closes #21093
* bugfix: constructed mommis no longer get stuck in purgatory if killed
> mommi MMI fixening

- code/modules/mob/dead/observer/verbs.dm
closes #33558
DUUHHHH DURRRRRRR HHHUUUURRRRRRRR
* bugfix: ghost toggle-darkness now lets you see other ghosts, hide them with "hide-ghosts"
> ghost toggle-darkness no longer hides other ghosts

- code/ATMOSPHERICS/components/unary/outlet_injector.dm
changes the air injectors to measure volume based on standard pressure, instead of the input gas pressure
increases the base pumping speed from 50L to 2500L (one tile's worth of air per tick)
increases the max pumping speed from 200L to 10000L
because i think so
:cl:
* tweak: unary air injectors now inject at a constant rate, regardless of pipe pressure
> air injector tweak

- code/ZAS/Plasma.dm
getting plasma in your eyes no longer completely breaks your eyes, instead stopping 5 damage under the blindness threshold
reduces the amount of eye damage that plasma does from 2.5 to 1 per tick
reduces the duration of temporary blindness you get while in blasma from 40 seconds to 10
the collab he close my PR (#34011) but i respawn
:cl:
* tweak: plasma no longer blinds you permanently after 14 seconds of exposure
> limit plasmaflood eye damage #2

- code/game/machinery/vending.dm
fills the vendors' coin, voucher and holiday item pools when you restock them
closes #11968
* bugfix: vendors will now restock all their categories when restocked, not just the standard+contraband ones
> fix vendor restocking

- code/game/turfs/simulated/floor_types.dm
makes reinforced floors(the ones made with metalrods and plasteel tiles) much stronger
they protect wires and pipes underneath(until they break)
instead of the old 40% chance to breach or stay completely intact, they now break gradually
also fixes a bug where disposals and wires were visible above the floor if you crowbarred off a plasteel tile
:cl:
* bugfix: plasteel tiles no longer make underfloor cables visible
* tweak: plasteel tiles are now more blast resistant
> make reinforced floors more reinforced

- code/game/objects/items/robot/robot_upgrades.dm
- code/modules/events/old_vendotron_event/old_vendotron.dm
adds a borg upgrade to the traders and the old vendotron (and spacemart, since that picks from every existing item)
the ass gets removed if the cyborg gets a module reset
fetish content
* rscadd: cyborg b.r.a.p. upgrades have been spotted in shoal warehouses.
> bootyborg upgrade

- code/modules/reagents/reagent_containers/food/mobcube.dm
adds more stuff to the logs
yeah turns out it isnt logged and i'm guessing that's why the voxsec spaced that assistant yesterday
but we'll never know for sure cause it wasn't logged
> log monkeycube consumption

- code/modules/mob/living/silicon/ai/life.dm
makes AI's that get hit by a mounted flash/flashbang recover in 20 seconds instead of being BTFO eternally
strangely enough flashing the AI with a normal flash doesn't cause this
closes #33793
maybe even #34436
* bugfix: AIs no longer get stunned permanently if flashed
> ai flash fix

- code/datums/gamemode/role/vampire_role.dm
you know how when there's vampires everyone always stutters forever?
this adds a max() in there so that shouldn't happen anymore
Explain why you think these changes are good.
:cl:
* tweak: limit vampire trueform stuttering to 40 seconds
> limit vampire trueform stutter to 40 seconds

- code/game/mecha/mecha.dm
[untested][0%tested]
closes #34978
if spriters make some icons for the posi-mechs i can add em in too
The sign is a subtle joke. The shop is called "Sneed's Feed & Seed", where feed and seed both end in the sound "-eed", thus rhyming with the name of the owner, Sneed. The sign says that the shop was "Formerly Chuck's", implying that the two words beginning with "F" and "S" would have ended with "-uck", rhyming with "Chuck". So, when Chuck owned the shop, it would have been called "Chuck's Fuck and Suck".
:cl:
* bugfix: MMI/positronic mechs should no longer be invisible
> invisible mech fix

- code/game/machinery/computer/aifixer.dm
closes #35038
did you know the restorer has req_access of bridge, captain and robotics? they don't do anything though, the computer is public
* bugfix: AI restorer computers can now be deconstructed
> makes the AI restorer's screen restorable

- code/modules/reagents/Chemistry-Reagents.dm
This change makes it so:
-Sleeptoxin now has an OD amount of 30 units.
-If the chem is in your system for over 8 minutes (480 seconds or 240 ticks), it will nuke your heart.
Requested by Nipples and some other babbymins in the admin metaclub.
Because Sleep Toxin is apparently a badwrong chemical with that can sleep you 5ever with no recourse and no OD.
:cl:
* tweak: Sleep Toxin now has an overdose amount (30 units) that will deal some toxin damage if you go over it.
* tweak: Sleep Toxin will now start destroying your heart if it's in your system for more than 8 minutes.
> Nerfs Sleep Toxin so it has an OD amount and OD timer of 8 minutes

- code/controllers/subsystem/supply_shuttle.dm
:cl:
* tweak: a cargo centcom order coming in while an RC announcement is being written will no longer cancel the announcement
* bugfix: centcom orders will no longer make the entire RC message list bold
> make cargo forwards on the RC consoles less bad

- code/game/machinery/telecomms/multicaster.dm
mechanics get a message when you send a dept. message to engineering
geneticists get a message when you send a dept. message to science
it allows me to morally toolbox the mechanic after i send a message to engineering "where power" and the lights dont turn on
:cl:
* rscadd: mechanic and geneticist PDAs now take both their respective departments into account when receiving multicasted messages
> make CAMO multicast to mechanics and geneticists

- code/modules/mob/living/carbon/human/human.dm
[ided][0%tested]
grab intent stops pulling whoever you're pulling, meaning the spaceman you're grabbing can now crawl away(you can't crawl while being pulled)
this PR makes you unable to crawl if you're grabbed too, so you no longer need to spam ctrlclick and Z for them to not get away
i ded, buff thing NOW
* tweak: you can no longer crawl while being grab intented
> prevent crawling away when you get grab intented
